### ISSUE TITLE
categraf中的net_response和http_response插件获取的code值能否调整一下

### ISSUE THREAD

**Issue by charlesqing** [flashcatcloud/categraf#1003]
看了blackbox的监控取值，发现categraf中的net_response和http_response插件获取的code值是和blackbox相反的，能否调整成一致的

1 = success
0 = failed

**Comment by charlesqing** [comment]
提这个需求不太像话，已经关闭

**Comment by kongfei605** [comment]
这个code是跟telegraf保持一致的，后面不能做issue中这种调整，主要是保持老用户的使用习惯，不然老用户需要批量修改报警了
