### ISSUE TITLE
Categraf-v0.3.60 采集日志文件无法达到采集上限

### ISSUE THREAD

**Issue by luoyuLianga** [flashcatcloud/categraf#1007]
背景：验证Categraf采集日志文件的能力，Categraf采集日志后将内容基于http发送给python服务
           一个脚本将固定的内容以每秒10000次写入到指定的文件，交由Categraf进行采集

问题：发现每次发送的日志数量无法达到默认配置的1000条
如下python脚本进行统计的结果，统计上报的http总数和总的日志条数、本次http上报的条数
![image](https://github.com/user-attachments/assets/3cab6967-acf0-44f8-9a2f-b3d926107ef6)
Total requests: 119, Total messages: 99336, current messages count: 849
Total requests: 统计历史http总请求次数
Total messages: 统计历史总的日志条数（从json解析，提取message）
current messages count: 本次http请求所上报的条数（发现最大是849）

logs插件的配置：
![image](https://github.com/user-attachments/assets/1077ba86-82b8-4400-ae8e-d773a6c56d8c)
默认的一套配置，原则上上报的数量可以达到1000才对
将chan_size和batch_max_size调整为500是可以生效的。将chan_size和batch_max_size调整为1000，batch_max_contentsize=2000000也是无效的

写入文件的脚本：
![image](https://github.com/user-attachments/assets/49eb740e-e4db-4b1b-be82-cce3d65a6b5d)

其他信息：
![image](https://github.com/user-attachments/assets/ddbb4ba9-84ad-4c9c-bec6-12afa1820f16)
也尝试在message full的时候进行打印日志，但是无法看到相关日志的输出

**Comment by luoyuLianga** [comment]
如果将配置调整为500，结果是符合预期的

配置：
![image](https://github.com/user-attachments/assets/7c516195-8d55-464c-9068-46d414b87253)
python脚本接收结果：
![image](https://github.com/user-attachments/assets/1f2d98c4-e3ce-4884-86da-47e8c00588aa)
categraf输出的日志：
![image](https://github.com/user-attachments/assets/f228fca4-1a30-45b8-9e95-632aba3ac15a)

**Comment by luoyuLianga** [comment]
找到问题了：
![image](https://github.com/user-attachments/assets/f1e2a37b-9a9d-487e-83ac-f8f36da6eaff)
![image](https://github.com/user-attachments/assets/82bb54a8-a686-4db0-b95b-7844e561b107)
字符不匹配引起的

**Comment by kongfei605** [comment]
see https://github.com/flashcatcloud/categraf/pull/1008
