### ISSUE TITLE
categraf的ibex的设计请教

### ISSUE THREAD

**Issue by zhanglingxing** [flashcatcloud/categraf#1009]
categraf的ibex的设计agent定期轮询查询server，为啥不能把任务推送到指定的agent？每个agent都轮询查询server，这样对服务端的压力也很大啊？

<img width="857" alt="image" src="https://github.com/user-attachments/assets/66be1f68-0d7b-496b-9200-fb2b1f8d6784">

**Comment by kongfei605** [comment]
方便边缘机房部署，比如，不允许推送，只能拉取中心机房配置的网络环境

**Comment by zhanglingxing** [comment]
感谢解答
