### ISSUE TITLE
使用--intall安装 systemctl 日志输出问题

### ISSUE THREAD

**Issue by cary997** [flashcatcloud/categraf#1010]
# 需求描述
categraf 使用./categraf --install 安装，默认systemctl的配置里的StandardOutput和StandardError是输出到journal+console，导致当出现错误时日志一直输出到终端，非常影响操作和排查

# 问题截图
![image](https://github.com/user-attachments/assets/79433219-0989-49a4-9c11-754dea40778d)

# 建议
建议是否可以改为StandardOutput和StandardError输出到syslog或journal

**Comment by kongfei605** [comment]
已更新 https://github.com/flashcatcloud/categraf/pull/1012
