### ISSUE TITLE
categraf在windows执行脚本，当meta/{id}/stdout文件 有中文的时候，会报错

### ISSUE THREAD

**Issue by zhanglingxing** [flashcatcloud/categraf#1018]
同样的脚本，输出到stdout文件有中文的时候，任务就会一直running，最终timeout，日志会一直打印错误信息，我觉得这个bug挺严重的，希望可以修复。

![image](https://github.com/user-attachments/assets/f6506456-68bc-403c-b3fb-82712722be80)

**Comment by kongfei605** [comment]
感谢反馈，这个问题我来看看

**Comment by zhanglingxing** [comment]
@kongfei605 我发现脚本有中文注释，脚本是可以正常执行的，但是server的状态也是running，然后timeout。
![image](https://github.com/user-attachments/assets/6dca433a-23a8-4513-ae42-591f00fd0806)

错误日志和之前的一样
![image](https://github.com/user-attachments/assets/0d8a7034-9ccf-409f-8f2d-a30d5be7e299)

**Comment by UlricQin** [comment]
升级夜莺到最新版本再试试

**Comment by UlricQin** [comment]
数据库里的 task_xx 那一百张表，用的是什么字符集？

**Comment by zhanglingxing** [comment]
@UlricQin 
数据库表的编码
![image](https://github.com/user-attachments/assets/cd48f116-9b27-4052-9deb-acf4a643d514)

数据库的编码
![image](https://github.com/user-attachments/assets/15eb3a7c-e9f0-4d0d-9680-1d2d93822ed8)

mysql连接串的配置
![image](https://github.com/user-attachments/assets/a63a0165-237b-4a2f-998a-08c9caeecd43)

**Comment by UlricQin** [comment]
那不清楚了，按理说就是字符集的问题：

<img width="638" alt="image" src="https://github.com/user-attachments/assets/4fa5c451-1a2e-4fee-92b2-2e5166cdd00a">

**Comment by zhanglingxing** [comment]
@UlricQin 大佬，那你们有没有测试过，在windows执行对应的脚本，脚本中包含中文，如果你们是可以的，我再排查一下环境。

**Comment by UlricQin** [comment]
我没试，这手头没有Windows，这块代码是社区小伙伴提交的




秦晓辉
***@***.***

快猫星云
联合创始人
18612185520



------------------ 原始邮件 ------------------
发件人: zhanglingxing ***@***.***&gt;
发送时间: 2024年7月31日 18:27
收件人: flashcatcloud/categraf ***@***.***&gt;
抄送: ulricqin ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [flashcatcloud/categraf] categraf在windows执行脚本，当meta/{id}/stdout文件 有中文的时候，会报错 (Issue #1018)





 
@UlricQin 大佬，那你们有没有测试过，在windows执行对应的脚本，脚本中包含中文，如果你们是可以的，我再排查一下环境。

**Comment by zzmark** [comment]
cmd 脚本没法用 UTF-8编码，这方面要做些特殊处理

**Comment by zzmark** [comment]
反馈的 issue 包含两个问题
1. task#start() 阶段，若是出现 error，没有正确设置 status，任务仍被识别为 running
2. cmd 运行脚本，需要使用 ANSI 编码 + CRLF 换行。golang 内部均为unicode编码，没中文的话 utf8 与 ANSI 在 ASCII 范围内一致所以没问题。

这问题不算难搞，稍后我提个patch


其实还有个问题，脚本传入换行为 LF，应该会出现吞命令的，但是你这个却没出现，有点意外，这个脚本难道是从外部粘贴进来的吗？
如果是这样，n9e那边的编辑器需要补个换行符过滤了，避免 Linux 脚本出现 CRLF 导致无法执行。



若是改用 powershell(pwsh)，则可以使用utf-8 + LF，不过改造工程有点大，需要n9e也加表单加字段，链路较长

**Comment by kongfei605** [comment]
golang 会自动处理windows和linux的换行差异
