### ISSUE TITLE
夜莺全套安装教程

### ISSUE THREAD

**Issue by 315xiaoyao** [flashcatcloud/categraf#102]
大佬，能不能出一套全的视频教程，现在查到的资料都是虎头蛇尾的，对于小白很不友好啊。如果可以的话全部使用docker来搭建，配置做一些说明就更好了。非常感谢！

**Comment by UlricQin** [comment]
n9e.github.io 通读文档一定可以搞定，如果实在搞不定，或想知道针对自己企业的最佳落地方案，可以联系我们采购商业技术支持

**Comment by lsy1990** [comment]
肯定不能全用docker：）支持采购商业技术支持：）哈哈
