### ISSUE TITLE
夜莺怎么设置GPU的告警呀？很着急，window  使用了categraf 的dcgm插件 启动categraf 却说 dcgm not support

### ISSUE THREAD

**Issue by leejunl** [flashcatcloud/categraf#1021]
![微信截图_20240806195420](https://github.com/user-attachments/assets/8dcae5b7-4e24-49e4-a17a-71521b82e20a)

![微信截图_20240806195515](https://github.com/user-attachments/assets/01444905-d5f5-4214-8f76-4292a475acb9)

**Comment by kongfei605** [comment]
文档有说明，用with-cgo的版本

**Comment by kongfei605** [comment]
还不支持windows启用dcgm 插件

**Comment by kongfei605** [comment]
> 文档有说明，用with-cgo的版本

with-cgo只有linux版本

**Comment by leejunl** [comment]
> > 文档有说明，用with-cgo的版本
> 
> with-cgo只有linux版本

谢谢，我试下
