### ISSUE TITLE
开源提供本地配置自动热更新

### ISSUE THREAD

**Issue by zhbitzwz** [flashcatcloud/categraf#1030]
应用场景
1、每次本地更新配置都要systemctl  restart categraf.service才能生效，很不方便，希望开源提供接入思路。
2、开源有本地配置自动热更新之后，才能更容易集成其它功能。比如，用exe插件写个脚本动态监控系统用户进程，有新进程就生成新的配置文件，但如果有配置热更新的功能的话就不用重新启动categraf进程了。

**Comment by kongfei605** [comment]
1. 基本思路就是配置更新，input自动reload
2. 这个不依赖配置更新，依赖脚本能不能动态监控了。 exec+ 自动发现脚本，发现新进程上报。

**Comment by zzmark** [comment]
categraf给了热更新的信号量，可以使用 `/bin/kill -HUP $MAINPID`

我这里直接把这命令写入了 systemd，支持执行 `systemctl reload categraf`
```
[service]
...
ExecReload=/bin/kill -HUP $MAINPID
...
```

至于文件变更后自动热更，这个有风险，不推荐内置。

虽然不推荐使用自动重载，不过用 inotify-tools 挂个脚本很简单就能实现
```bash
inotifywait -m -r -e create -e delete -e modify -e move $CONF_DIR |
while read path action file; do
    systemctl reload categraf
done
```
