### ISSUE TITLE
对Anolis OS 兼容问题

### ISSUE THREAD

**Issue by GitHubLoveKe** [flashcatcloud/categraf#1032]
我尝试在Anolis OS上使用categraf，命行启动没有问题，但是systemd管理的时候没数据，我检查了categraf.service，用里面的启动命令在命令行启动没有问题，但是通过systemd 管理的时候没数据，ps -ef能过滤到对应进程，我在机器上通过源码编译后也有这个问题

**Comment by GitHubLoveKe** [comment]
![image](https://github.com/user-attachments/assets/65b5f41c-ed6b-4efc-8bd8-7152a925e89f)

**Comment by kongfei605** [comment]
systemctl cat categraf.service 输出贴下？

**Comment by kongfei605** [comment]
ps -ef |grep categraf

**Comment by GitHubLoveKe** [comment]
![image](https://github.com/user-attachments/assets/d7487378-24c7-4bfe-a465-2986433d2e75)

**Comment by GitHubLoveKe** [comment]
![image](https://github.com/user-attachments/assets/ee02c302-a2d5-42b3-a15b-032e0a333aea)

**Comment by GitHubLoveKe** [comment]
![image](https://github.com/user-attachments/assets/5acbcc4d-bc43-4043-897c-5d37980a1b53)
命令行的时候数据能够上来

**Comment by GitHubLoveKe** [comment]
![image](https://github.com/user-attachments/assets/3fc55bf1-fb3e-436c-b4b1-e94d1a450b14)

**Comment by EdenBob** [comment]
我也遇到了您同样的问题，请问您是怎么解决的呀？
