### ISSUE TITLE
categraf使用input.prometheus，配置consul服务发现，无法采集数据

### ISSUE THREAD

**Issue by gsq0092** [flashcatcloud/categraf#1041]
prometheus.toml内容如下：

```
[[instances]]
## Scrape Services available in Consul Catalog
  [instances.consul]
    enabled = true
    agent = "http://127.0.0.1:8500"
    query_interval = "1m"

    [[instances.consul.query]]
      name = "custom_exporter"
      tag = "custom_exporter"
      url = 'http://{{.ServiceAddress}}:{{.ServicePort}}/metrics'
      [instances.consul.query.tags]
        host = "{{.ServicePort}}"
```

配置了consul服务发现，运行后，没有采集到数据

**Comment by UlricQin** [comment]
可以从 categraf 的日志里找找线索

**Comment by gsq0092** [comment]
![image](https://github.com/user-attachments/assets/bd08c6a6-910c-402f-92aa-556b279aca6d)

**Comment by luoyuLianga** [comment]
要不要试试修改代码验证

**Comment by kongfei605** [comment]
> ![image](https://private-user-images.githubusercontent.com/19235807/363535314-bd08c6a6-910c-402f-92aa-556b279aca6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNzk5MDUsIm5iZiI6MTcyNTI3OTYwNSwicGF0aCI6Ii8xOTIzNTgwNy8zNjM1MzUzMTQtYmQwOGM2YTYtOTEwYy00MDJmLTkyYWEtNTU2YjI3OWFjYTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDEyMjAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmYmViN2ZhMDZjZjg4MTRiYzkwZGM2ZGMyMmU0MWNmNmJhMDhiYjU5NDY1ZDM1NzM4MmI4ZTlhZjZiNTZhOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-_fWsG4zqlEbZu9pt3k2b8uvWsSQUi6ipFYHIRZ1RzA)
> 
> 日志说是从consul添加了抓取的url，但是没有数据，直接访问抓取的url是有数据的 ![image](https://private-user-images.githubusercontent.com/19235807/363536634-d8b7734a-77d9-4ae8-a29c-15f032758302.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNzk5MDUsIm5iZiI6MTcyNTI3OTYwNSwicGF0aCI6Ii8xOTIzNTgwNy8zNjM1MzY2MzQtZDhiNzczNGEtNzdkOS00YWU4LWEyOWMtMTVmMDMyNzU4MzAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDEyMjAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NjkwODMxMzJhMDRlYmFmZGZlNmM4YjljNjc3MGZhMTMzOTljMWVlMWQ5OGE1NzVmNmYwOGQyZGE1ZDFmNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gzo1uz3zmW_Nwe_Xcu5X-gHo4xfkjowrl7SrOyOPr9c)

./categraf --test  --debug --inputs prometheus 跑跑看

**Comment by gsq0092** [comment]
> > ![图像](https://private-user-images.githubusercontent.com/19235807/363535314-bd08c6a6-910c-402f-92aa-556b279aca6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNzk5MDUsIm5iZiI6MTcyNTI3OTYwNSwicGF0aCI6Ii8xOTIzNTgwNy8zNjM1MzUzMTQtYmQwOGM2YTYtOTEwYy00MDJmLTkyYWEtNTU2YjI3OWFjYTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDEyMjAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmYmViN2ZhMDZjZjg4MTRiYzkwZGM2ZGMyMmU0MWNmNmJhMDhiYjU5NDY1ZDM1NzM4MmI4ZTlhZjZiNTZhOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-_fWsG4zqlEbZu9pt3k2b8uvWsSQUi6ipFYHIRZ1RzA)
> > 日志说是从consul添加了抽象的url，但是没有数据，直接访问抽象的url是有数据的![图像](https://private-user-images.githubusercontent.com/19235807/363536634-d8b7734a-77d9-4ae8-a29c-15f032758302.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNzk5MDUsIm5iZiI6MTcyNTI3OTYwNSwicGF0aCI6Ii8xOTIzNTgwNy8zNjM1MzY2MzQtZDhiNzczNGEtNzdkOS00YWU4LWEyOWMtMTVmMDMyNzU4MzAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDEyMjAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NjkwODMxMzJhMDRlYmFmZGZlNmM4YjljNjc3MGZhMTMzOTljMWVlMWQ5OGE1NzVmNmYwOGQyZGE1ZDFmNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gzo1uz3zmW_Nwe_Xcu5X-gHo4xfkjowrl7SrOyOPr9c)
> 
> ./categraf --test --debug --inputs prometheus 跑跑看

./categraf --test --debug --inputs prometheus运行也是说添加了采集的url
![image](https://github.com/user-attachments/assets/bd4da8e8-1285-473c-9777-50ae831c9bd0)

**Comment by Meepoljdx** [comment]
![image](https://github.com/user-attachments/assets/11eb7e48-f014-45a5-986f-ba1ddfa59373)
应该是这里的select，加个default的处理逻辑就好

**Comment by kongfei605** [comment]
> ![image](https://private-user-images.githubusercontent.com/63089130/363895698-11eb7e48-f014-45a5-986f-ba1ddfa59373.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MzY0NTcsIm5iZiI6MTcyNTQzNjE1NywicGF0aCI6Ii82MzA4OTEzMC8zNjM4OTU2OTgtMTFlYjdlNDgtZjAxNC00NWE1LTk4NmYtYmExZGRmYTU5MzczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA3NDkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2ZWVhMzdhYjNiNWQ0NTdhZWZlZjg4NDRhMjQ2MDQ2NjIzNjE5NTBkNDEyODQ3NDJmZDEwZGFlM2NmYjE3NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7MD-245CQrWJcWFUJwzYFmppIrKowZnxX9UU_M-LlCw) 应该是这里的select，加个default的处理逻辑就好

这个不对，那不是再time.After之前就return了

**Comment by kongfei605** [comment]
> > > ![图像](https://private-user-images.githubusercontent.com/19235807/363535314-bd08c6a6-910c-402f-92aa-556b279aca6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNzk5MDUsIm5iZiI6MTcyNTI3OTYwNSwicGF0aCI6Ii8xOTIzNTgwNy8zNjM1MzUzMTQtYmQwOGM2YTYtOTEwYy00MDJmLTkyYWEtNTU2YjI3OWFjYTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDEyMjAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmYmViN2ZhMDZjZjg4MTRiYzkwZGM2ZGMyMmU0MWNmNmJhMDhiYjU5NDY1ZDM1NzM4MmI4ZTlhZjZiNTZhOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-_fWsG4zqlEbZu9pt3k2b8uvWsSQUi6ipFYHIRZ1RzA)
> > > 日志说是从consul添加了抽象的url，但是没有数据，直接访问抽象的url是有数据的![图像](https://private-user-images.githubusercontent.com/19235807/363536634-d8b7734a-77d9-4ae8-a29c-15f032758302.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNzk5MDUsIm5iZiI6MTcyNTI3OTYwNSwicGF0aCI6Ii8xOTIzNTgwNy8zNjM1MzY2MzQtZDhiNzczNGEtNzdkOS00YWU4LWEyOWMtMTVmMDMyNzU4MzAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDEyMjAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NjkwODMxMzJhMDRlYmFmZGZlNmM4YjljNjc3MGZhMTMzOTljMWVlMWQ5OGE1NzVmNmYwOGQyZGE1ZDFmNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gzo1uz3zmW_Nwe_Xcu5X-gHo4xfkjowrl7SrOyOPr9c)
> > 
> > 
> > ./categraf --test --debug --inputs prometheus 跑跑看
> 
> ./categraf --test --debug --inputs prometheus运行也是说添加了采集的url ![image](https://private-user-images.githubusercontent.com/19235807/363813933-bd4da8e8-1285-473c-9777-50ae831c9bd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MzY0NTcsIm5iZiI6MTcyNTQzNjE1NywicGF0aCI6Ii8xOTIzNTgwNy8zNjM4MTM5MzMtYmQ0ZGE4ZTgtMTI4NS00NzNjLTk3NzctNTBhZTgzMWM5YmQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA3NDkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2NjI1YmMwMjhjY2IyZmQxYTYzZDA2YjM4ODUxNzU0Y2VlM2U0NjFmMmZlYjFlYTRhZTRmNzQ0MzFkY2M5NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.maO96znuD14hEgkdlfQFBg4pr8nVLDPIFIxdKuPazCI)

你这边跑了多久？ 看你配置中query interval是1m， 等1m后再看看

**Comment by gsq0092** [comment]
> > > > ![图像](https://private-user-images.githubusercontent.com/19235807/363535314-bd08c6a6-910c-402f-92aa-556b279aca6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNzk5MDUsIm5iZiI6MTcyNTI3OTYwNSwicGF0aCI6Ii8xOTIzNTgwNy8zNjM1MzUzMTQtYmQwOGM2YTYtOTEwYy00MDJmLTkyYWEtNTU2YjI3OWFjYTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDEyMjAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmYmViN2ZhMDZjZjg4MTRiYzkwZGM2ZGMyMmU0MWNmNmJhMDhiYjU5NDY1ZDM1NzM4MmI4ZTlhZjZiNTZhOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-_fWsG4zqlEbZu9pt3k2b8uvWsSQUi6ipFYHIRZ1RzA)
> > > > 日志说是从consul添加了抽象的url，但是没有数据，直接访问抽象的url是有数据的![图像](https://private-user-images.githubusercontent.com/19235807/363536634-d8b7734a-77d9-4ae8-a29c-15f032758302.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNzk5MDUsIm5iZiI6MTcyNTI3OTYwNSwicGF0aCI6Ii8xOTIzNTgwNy8zNjM1MzY2MzQtZDhiNzczNGEtNzdkOS00YWU4LWEyOWMtMTVmMDMyNzU4MzAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDEyMjAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NjkwODMxMzJhMDRlYmFmZGZlNmM4YjljNjc3MGZhMTMzOTljMWVlMWQ5OGE1NzVmNmYwOGQyZGE1ZDFmNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gzo1uz3zmW_Nwe_Xcu5X-gHo4xfkjowrl7SrOyOPr9c)
> > > 
> > > 
> > > ./categraf --test --debug --inputs prometheus 跑跑看
> > 
> > 
> > ./categraf --test --debug --inputs prometheus 运行也说添加了采集的 url![图像](https://private-user-images.githubusercontent.com/19235807/363813933-bd4da8e8-1285-473c-9777-50ae831c9bd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MzY0NTcsIm5iZiI6MTcyNTQzNjE1NywicGF0aCI6Ii8xOTIzNTgwNy8zNjM4MTM5MzMtYmQ0ZGE4ZTgtMTI4NS00NzNjLTk3NzctNTBhZTgzMWM5YmQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA3NDkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2NjI1YmMwMjhjY2IyZmQxYTYzZDA2YjM4ODUxNzU0Y2VlM2U0NjFmMmZlYjFlYTRhZTRmNzQ0MzFkY2M5NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.maO96znuD14hEgkdlfQFBg4pr8nVLDPIFIxdKuPazCI)
> 
> 你跑了多久？看你配置中查询间隔是1m，等1m后再看看

运行时间久一些也没有数据，运行了大概10m

**Comment by kongfei605** [comment]
已提交 https://github.com/flashcatcloud/categraf/pull/1045
