### ISSUE TITLE
如何降低拉取cloudwatch api指标的频率？

### ISSUE THREAD

**Issue by lvai125** [flashcatcloud/categraf#1047]
由于cloudwatch api指标收费太贵，在cloud.toml将默认的period = "5m"改为1m就可以了吗？还有哪些指标可以配置的？

**Comment by kongfei605** [comment]
https://flashcat.cloud/docs/content/flashcat-monitor/categraf/plugin/cloudwatch/ 

采集频率跟interval 和 interval_times 相关， 降低请求次数，就要调大period。 请求次数高，降低period。 总体来说，拉取的指标数量都是一样的。

**Comment by lvai125** [comment]
文档上说interval参数已废弃，另外没找到interval_times参数
我现在将period调为10m，interval改为5m

**Comment by lvai125** [comment]
> https://flashcat.cloud/docs/content/flashcat-monitor/categraf/plugin/cloudwatch/
> 
> 采集频率跟interval 和 interval_times 相关， 降低请求次数，就要调大period。 请求次数高，降低period。 总体来说，拉取的指标数量都是一样的。
--老师，上调了period，用./categraf --test -inputs  cloudwatch测试，发现是1分钟拉取一次，没看到降低频率呢？

**Comment by kongfei605** [comment]
> > https://flashcat.cloud/docs/content/flashcat-monitor/categraf/plugin/cloudwatch/
> > 采集频率跟interval 和 interval_times 相关， 降低请求次数，就要调大period。 请求次数高，降低period。 总体来说，拉取的指标数量都是一样的。
> > --老师，上调了period，用./categraf --test -inputs  cloudwatch测试，发现是1分钟拉取一次，没看到降低频率呢？

interval times是通用配置，放到instance就可以。 https://flashcat.cloud/docs/content/flashcat-monitor/categraf/3-configuration/
