### ISSUE TITLE
categraf在有些情况不能启动，帮忙看一下

### ISSUE THREAD

**Issue by eguotangseng** [flashcatcloud/categraf#1049]
Sep 10 10:50:59 localhost.localdomain systemd[1]: categraf.service: Main process exited, code=exited, status=203/EXEC
Sep 10 10:50:59 localhost.localdomain systemd[1]: categraf.service: Failed with result 'exit-code'.
Sep 10 10:52:59 localhost.localdomain systemd[1]: categraf.service: Scheduled restart job, restart counter is at 5.
Sep 10 10:52:59 localhost.localdomain systemd[1]: Stopped Opensource telemetry collector.
Sep 10 10:52:59 localhost.localdomain systemd[1]: Started Opensource telemetry collector.
Sep 10 10:52:59 localhost.localdomain systemd[1]: categraf.service: Main process exited, code=exited, status=203/EXEC
Sep 10 10:52:59 localhost.localdomain systemd[1]: categraf.service: Failed with result 'exit-code'.
Sep 10 10:54:59 localhost.localdomain systemd[1]: categraf.service: Scheduled restart job, restart counter is at 6.
Sep 10 10:54:59 localhost.localdomain systemd[1]: Stopped Opensource telemetry collector.
Sep 10 10:54:59 localhost.localdomain systemd[1]: Started Opensource telemetry collector.
Sep 10 10:54:59 localhost.localdomain systemd[1]: categraf.service: Main process exited, code=exited, status=203/EXEC
Sep 10 10:54:59 localhost.localdomain systemd[1]: categraf.service: Failed with result 'exit-code'.

**Comment by eguotangseng** [comment]
openeuler系统openeuler2203这个版本

**Comment by kongfei605** [comment]
配置不对吧， ./categraf --test --debug  看看

**Comment by kongfei605** [comment]
https://github.com/flashcatcloud/categraf/issues/1051 参考这个issue
