### ISSUE TITLE
请问categraf支持接受其他categraf节点的数据一起发送到n9e节点吗？

### ISSUE THREAD

**Issue by masterzht** [flashcatcloud/categraf#1072]
**What would you like to be added**:
比如有四台机器需要安装categraf，其中只有一台机器是有网络的支持把数据写到远程n9e节点，当前的categarf能否支持接受其他catagraf节点的数据？
**Why is this needed**:

**Describe the solution you'd like**

**Additional context**

**Comment by kongfei605** [comment]
支持。相对配置pushgateway+调试+答疑，推荐直接搞个nginx 给n9e代理更快。

**Comment by masterzht** [comment]
@kongfei605 您的意思是在比如四台agent前部署个nginx，然后统一走这个nginx写数据到n9e吗？我其实是倾向于用pushgateway的，但是好像其他三台离线服务器的心跳就发送不出去了

**Comment by kongfei605** [comment]
> @kongfei605 您的意思是在比如四台agent前部署个nginx，然后统一走这个nginx写数据到n9e吗？

对的。nginx做proxy，心跳也可以走这个nginx，配置上也更简单。
