### ISSUE TITLE
服务器agent_hostname重复了怎么办？

### ISSUE THREAD

**Issue by masterzht** [flashcatcloud/categraf#1077]
因为部署categraf时就定义了hostname为$ip，后续部署节点多了之后发现会有重复的内网ip，但是在机器列表页只会显示一个，这个应该怎么后置处理？
**What would you like to be added**:

**Why is this needed**:

**Describe the solution you'd like**

**Additional context**

**Comment by UlricQin** [comment]
那就自行确保机器的 IP 不同，对于不得不相同的，可以使用机器名作为标识，或者直接写死一个独特的字符串。
