### ISSUE TITLE
远程脚本下发

### ISSUE THREAD

**Issue by showsmall** [flashcatcloud/categraf#1091]
### Relevant config.toml

```toml
企业版从v0.3.34, 开源版v0.3.62起，支持远程配置脚本(会按照配置创建目录和脚本)

我看文档有说开源版本支持脚本远程下发，相关文档在哪里呀，我没有找到，谢谢！
```

### Logs from categraf

```text
企业版从v0.3.34, 开源版v0.3.62起，支持远程配置脚本(会按照配置创建目录和脚本)

我看文档有说开源版本支持脚本远程下发，相关文档在哪里呀，我没有找到，谢谢！
```

### System info

v0.3.82

### Steps to reproduce

企业版从v0.3.34, 开源版v0.3.62起，支持远程配置脚本(会按照配置创建目录和脚本)

我看文档有说开源版本支持脚本远程下发，相关文档在哪里呀，我没有找到，谢谢！

### Expected behavior

企业版从v0.3.34, 开源版v0.3.62起，支持远程配置脚本(会按照配置创建目录和脚本)

我看文档有说开源版本支持脚本远程下发，相关文档在哪里呀，我没有找到，谢谢！

### Actual behavior

企业版从v0.3.34, 开源版v0.3.62起，支持远程配置脚本(会按照配置创建目录和脚本)

我看文档有说开源版本支持脚本远程下发，相关文档在哪里呀，我没有找到，谢谢！

### Additional info

企业版从v0.3.34, 开源版v0.3.62起，支持远程配置脚本(会按照配置创建目录和脚本)

我看文档有说开源版本支持脚本远程下发，相关文档在哪里呀，我没有找到，谢谢！

**Comment by UlricQin** [comment]
<img width="758" alt="image" src="https://github.com/user-attachments/assets/349dd9ea-2add-4050-8dc0-bd271e61fc07">
那就是
