### ISSUE TITLE
windows server 2008R2 不支持

### ISSUE THREAD

**Issue by showsmall** [flashcatcloud/categraf#1098]
### Relevant config.toml

```toml
C:\categraf-v0.3.82-windows-amd64>categraf.exe --win-service-install
fatal error: kernel32.dll not found
runtime: panic before malloc heap initialized

C:\categraf-v0.3.82-windows-amd64>
```

### Logs from categraf

```text
C:\categraf-v0.3.82-windows-amd64>categraf.exe --win-service-install
fatal error: kernel32.dll not found
runtime: panic before malloc heap initialized

C:\categraf-v0.3.82-windows-amd64>
```

### System info

v0.3.82

### Steps to reproduce

C:\categraf-v0.3.82-windows-amd64>categraf.exe --win-service-install
fatal error: kernel32.dll not found
runtime: panic before malloc heap initialized

C:\categraf-v0.3.82-windows-amd64>

### Expected behavior

C:\categraf-v0.3.82-windows-amd64>categraf.exe --win-service-install
fatal error: kernel32.dll not found
runtime: panic before malloc heap initialized

C:\categraf-v0.3.82-windows-amd64>

### Actual behavior

C:\categraf-v0.3.82-windows-amd64>categraf.exe --win-service-install
fatal error: kernel32.dll not found
runtime: panic before malloc heap initialized

C:\categraf-v0.3.82-windows-amd64>

**Comment by kongfei605** [comment]
对的，go 不支持2008了，编译出来的可执行文件也不支持了

**Comment by zzmark** [comment]
golang 1.21 废弃了 win2008，得降低至 1.20 编译。

0.3.48 改用了 golang 1.21。
要么降低至此前的版本，要么自行改下go.mod降低至1.20自行编译，可能会遇到一些依赖不支持的情况。

**Comment by kongfei605** [comment]
> golang 1.21 废弃了 win2008，得降低至 1.20 编译。
> 
> 0.3.48 改用了 golang 1.21。 要么降低至此前的版本，要么自行改下go.mod降低至1.20自行编译，可能会遇到一些依赖不支持的情况。

改go.mod方式行不通，新插件用了很多1.21的特性 ，比如chrony插件

**Comment by showsmall** [comment]
chrony插件 在go 1.20下面好像是正常的呢？ @kongfei605

**Comment by kongfei605** [comment]
> chrony插件 在go 1.20下面好像是正常的呢？ @kongfei605

哦？ 可以看看v0.3.48 的change log ，没记错的话应该是有两个插件的PR merge进来才升级的go版本

**Comment by kongfei605** [comment]
> chrony插件 在go 1.20下面好像是正常的呢？ @kongfei605

windows 没有chrony

**Comment by kongfei605** [comment]
> 我的方案：改代码，在go1.20编译，现在跑在测试环境下面看看稳定性，我目前只改了一个地方就可以顺利通过编译然后在windows server 2008R2服务器上面跑起来

欢迎共享下你的方案给其他需要的用户

**Comment by showsmall** [comment]
https://github.com/flashcatcloud/categraf/issues/1094 帮忙看看这个issuse呗 @kongfei605

**Comment by kongfei605** [comment]
> #1094 帮忙看看这个issuse呗 @kongfei605

看不出来 问题

**Comment by kongfei605** [comment]
明确不支持windows server2008. 各位有需要的请去掉依赖go.1.21的插件，自行编译
