### ISSUE TITLE
windows 10 环境下面agent报错

### ISSUE THREAD

**Issue by showsmall** [flashcatcloud/categraf#1099]
### Relevant config.toml

```toml
windows 10 环境下面agent报错

2024/11/28 15:54:42 metrics_agent.go:260: E! failed to load configuration of plugin: local.gnmi error: toml: incompatible types: TOML key "instances.max_msg_size" has type string; destination has type integer
```

### Logs from categraf

```text
2024/11/28 15:54:42 metrics_agent.go:260: E! failed to load configuration of plugin: local.gnmi error: toml: incompatible types: TOML key "instances.max_msg_size" has type string; destination has type integer
```

### System info

v0.3.82

### Steps to reproduce

2024/11/28 15:54:42 metrics_agent.go:260: E! failed to load configuration of plugin: local.gnmi error: toml: incompatible types: TOML key "instances.max_msg_size" has type string; destination has type integer

### Expected behavior

2024/11/28 15:54:42 metrics_agent.go:260: E! failed to load configuration of plugin: local.gnmi error: toml: incompatible types: TOML key "instances.max_msg_size" has type string; destination has type integer

### Actual behavior

2024/11/28 15:54:42 metrics_agent.go:260: E! failed to load configuration of plugin: local.gnmi error: toml: incompatible types: TOML key "instances.max_msg_size" has type string; destination has type integer

**Comment by kongfei605** [comment]
用不到gnmi插件的话 可以input.gnmi目录删除掉

**Comment by showsmall** [comment]
ok

**Comment by kongfei605** [comment]
这个默认配置，我们再修改下
