### ISSUE TITLE
希望添加etcd和minio的采集

### ISSUE THREAD

**Issue by qtblsk** [flashcatcloud/categraf#116]
希望添加etcd和minio的采集

**Comment by kongfei605** [comment]
可以用prometheus的方式抓取https://github.com/flashcatcloud/categraf/tree/main/prometheus 。etcd推荐用fd_sd_config 方式，配置完如果能整理一篇文章更好了，欢迎参与

**Comment by qtblsk** [comment]
vim prometheus.yml

  - job_name: "etcd"
    scheme: https
    scrape_interval: 15s
    metrics_path: /metrics
    tls_config:
     ca_file: /root/etcd/ca.pem
     cert_file: /root/etcd/etcd.pem
     key_file: /root/etcd/etcd-key.pem
     insecure_skip_verify: false
    static_configs:
      - targets: ["10.10.10.1:2379", "10.10.10.2:2379", "10.10.10.3:2379"]

验证：
# curl -Lk --cert ./etcd.pem --key ./etcd-key.pem  https://10.10.10.1:2379/metrics

这就是pull的模式了，在跨网环境还是统一用categraf来push更方便，希望尽快集成到categraf里面

**Comment by kongfei605** [comment]
没太明白，是因为权限限制 所以pull模式不行？  可以用categraf 跟dns 部署到一个网络环境，remote write到外部的prometheus

**Comment by qtblsk** [comment]
还是不太方便，希望categraf能内置etcd、minio、wireguard插件

**Comment by UlricQin** [comment]
etcd 直接暴露了 /metrics 接口，minio也直接暴露了/minio/v2/metrics/cluster接口，通过categraf的prometheus插件直接采集即可
