### ISSUE TITLE
categraf 支持windows自定义采集指标？exec 配置的时候没有找到文件 

### ISSUE THREAD

**Issue by shawnloong** [flashcatcloud/categraf#139]
报错信息
2022/08/03 14:36:06 exec.go:133: E! exec_command: D:\exec\exec_oracle.bat error: exec: "D:execexec_oracle.bat": file does not exist stderr:

interval = 15
[[instances]]
commands = [
     "D:\\exec\\*.bat"
]
 timeout = 5
 interval_times = 15
# # mesurement,labelkey1=labelval1,labelkey2=labelval2 field1=1.2,field2=2.3
 data_format = "influx"

d:\exec\exec_oracle.bat
echo 'filesize,directory="/home/gxslzy/" size=547754993374'

**Comment by kongfei605** [comment]
加上转义字符再试试 D:\\exec\\*.bat

**Comment by kongfei605** [comment]
这个issue先close了，有问题随时反馈
