### ISSUE TITLE
请问ipmi监控有排期吗

### ISSUE THREAD

**Issue by zhushiyang** [flashcatcloud/categraf#143]
请问，什么时候可以支持ipmi监控

**Comment by Huagee** [comment]
同问

**Comment by UlricQin** [comment]
目前尚未，可以先使用 Telegraf 的 ipmi 插件，或者 ipmi_exporter，看看哪个好用反馈一下，回头给集成到 categraf中

**Comment by wthahaha** [comment]
ipmi_exporter还好用

**Comment by kongfei605** [comment]
ipmi  已经上线了，https://flashcat.cloud/docs/content/flashcat-monitor/categraf/plugin/ipmi/
