### ISSUE TITLE
categraf 能不能支持设置header

### ISSUE THREAD

**Issue by TOT-JIN** [flashcatcloud/categraf#144]
grafana labs旗下的产品 都有个多租户的概念，是以http请求头 X-Scope-OrgID 来实现的。
categraf 能不能支持设置header，用于兼容grafana的多租户模式。
目前不支持的情况下，可以采用在 remote write api 前加一层nginx反向代理，然后根据不同的server_name来proxy_set_header不同的值。

**Comment by UlricQin** [comment]
你是说categraf通过remote write往后端存储写数据的时候？这个现在不支持，产品设计角度来看，可以支持，也比较简单，欢迎PR
