### ISSUE TITLE
linux oracle 报错(centos 6.5 x64)

### ISSUE THREAD

**Issue by shawnloong** [flashcatcloud/categraf#146]
### Relevant config.toml

```toml
[global]
print_configs = false
hostname = "192.168.1.2"
omit_hostname = false
precision = "ms"
interval = 15

[global.labels]
region = "testdb"
env = "prod"
project_name='kk'
project_bs='ss'

[writer_opt]
batch = 2000
chan_size = 10000

[[writers]]
url = "https://xxx.xxx.com:19000/prometheus/v1/write"
basic_auth_user = "xx"
basic_auth_pass = "xxxxxx"

timeout = 5000
dial_timeout = 2500
max_idle_conns_per_host = 100
```

### Logs from categraf

```text
2022/08/08 19:10:53 main.go:112: I! runner.fd_limits: (soft=1024, hard=4096)
2022/08/08 19:10:53 main.go:113: I! runner.vm_limits: (soft=unlimited, hard=unlimited)
2022/08/08 19:10:53 config.go:33: I! tracing disabled
2022/08/08 19:10:53 agent.go:63: I! agent starting
2022/08/08 19:10:53 metrics_agent.go:95: I! input: conntrack started
2022/08/08 19:10:53 metrics_agent.go:95: I! input: cpu started
2022/08/08 19:10:53 metrics_agent.go:95: I! input: disk started
2022/08/08 19:10:53 metrics_agent.go:95: I! input: diskio started
2022/08/08 19:10:53 metrics_agent.go:95: I! input: kernel started
2022/08/08 19:10:53 metrics_agent.go:95: I! input: kernel_vmstat started
2022/08/08 19:10:53 metrics_agent.go:95: I! input: linux_sysctl_fs started
2022/08/08 19:10:53 metrics_agent.go:95: I! input: mem started
2022/08/08 19:10:53 metrics_agent.go:95: I! input: net started
2022/08/08 19:10:53 metrics_agent.go:95: I! input: netstat started
2022/08/08 19:10:53 metrics_agent.go:40: E! input: oracle not supported
```

### System info

centos 6.5 x64

### Steps to reproduce

1. go build 
2. cp categraf /opt/categraf/
3.
...

### Expected behavior

无

### Actual behavior

无

**Comment by UlricQin** [comment]
```
cd categraf
make build-enterprise
```

then use categraf binary to gather oracle metrics

**Comment by shizhoulong356** [comment]
while running on centos6.5  build failed  


go build --tags "enterprise"
# github.com/godror/godror
cgo: gcc did not produce error at completed:1
on input:

#line 1 "cgo-builtin-prolog"
#include <stddef.h> /* for ptrdiff_t and size_t below */

/* Define intgo when compiling with GCC.  */
typedef ptrdiff_t intgo;

#define GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; intgo n; } _GoString_;
typedef struct { char *p; intgo n; intgo c; } _GoBytes_;
_GoString_ GoString(char *p);
_GoString_ GoStringN(char *p, int l);
_GoBytes_ GoBytes(void *p, int n);
char *CString(_GoString_);
void *CBytes(_GoBytes_);
void *_CMalloc(size_t);

__attribute__ ((unused))
static size_t _GoStringLen(_GoString_ s) { return (size_t)s.n; }

__attribute__ ((unused))
static const char *_GoStringPtr(_GoString_ s) { return s.p; }
#line 8 "/root/go/pkg/mod/github.com/godror/godror@v0.33.0/conn.go"

#include <stdlib.h>
#include "dpiImpl.h"

#line 1 "cgo-generated-wrapper"
#line 1 "not-declared"
void __cgo_f_1_1(void) { __typeof__(CString) *__cgo_undefined__1; }
#line 1 "not-type"
void __cgo_f_1_2(void) { CString *__cgo_undefined__2; }
#line 1 "not-int-const"
void __cgo_f_1_3(void) { enum { __cgo_undefined__3 = (CString)*1 }; }
#line 1 "not-num-const"
void __cgo_f_1_4(void) { static const double __cgo_undefined__4 = (CString); }
#line 1 "not-str-lit"
void __cgo_f_1_5(void) { static const char __cgo_undefined__5[] = (CString); }
#line 2 "not-declared"
void __cgo_f_2_1(void) { __typeof__(char) *__cgo_undefined__1; }
#line 2 "not-type"
void __cgo_f_2_2(void) { char *__cgo_undefined__2; }
#line 2 "not-int-const"
void __cgo_f_2_3(void) { enum { __cgo_undefined__3 = (char)*1 }; }
#line 2 "not-num-const"
void __cgo_f_2_4(void) { static const double __cgo_undefined__4 = (char); }
#line 2 "not-str-lit"
void __cgo_f_2_5(void) { static const char __cgo_undefined__5[] = (char); }
#line 3 "not-declared"
void __cgo_f_3_1(void) { __typeof__(dpiConn) *__cgo_undefined__1; }
#line 3 "not-type"
void __cgo_f_3_2(void) { dpiConn *__cgo_undefined__2; }
#line 3 "not-int-const"
void __cgo_f_3_3(void) { enum { __cgo_undefined__3 = (dpiConn)*1 }; }
#line 3 "not-num-const"
void __cgo_f_3_4(void) { static const double __cgo_undefined__4 = (dpiConn); }
#line 3 "not-str-lit"
void __cgo_f_3_5(void) { static const char __cgo_undefined__5[] = (dpiConn); }
#line 4 "not-declared"
void __cgo_f_4_1(void) { __typeof__(dpiConn_breakExecution) *__cgo_undefined__1; }
#line 4 "not-type"
void __cgo_f_4_2(void) { dpiConn_breakExecution *__cgo_undefined__2; }
#line 4 "not-int-const"
void __cgo_f_4_3(void) { enum { __cgo_undefined__3 = (dpiConn_breakExecution)*1 }; }
#line 4 "not-num-const"
void __cgo_f_4_4(void) { static const double __cgo_undefined__4 = (dpiConn_breakExecution); }
#line 4 "not-str-lit"
void __cgo_f_4_5(void) { static const char __cgo_undefined__5[] = (dpiConn_breakExecution); }
#line 5 "not-declared"
void __cgo_f_5_1(void) { __typeof__(dpiConn_commit) *__cgo_undefined__1; }
#line 5 "not-type"
void __cgo_f_5_2(void) { dpiConn_commit *__cgo_undefined__2; }
#line 5 "not-int-const"
void __cgo_f_5_3(void) { enum { __cgo_undefined__3 = (dpiConn_commit)*1 }; }
#line 5 "not-num-const"
void __cgo_f_5_4(void) { static const double __cgo_undefined__4 = (dpiConn_commit); }
#line 5 "not-str-lit"
void __cgo_f_5_5(void) { static const char __cgo_undefined__5[] = (dpiConn_commit); }
#line 6 "not-declared"
void __cgo_f_6_1(void) { __typeof__(dpiConn_getIsHealthy) *__cgo_undefined__1; }
#line 6 "not-type"
void __cgo_f_6_2(void) { dpiConn_getIsHealthy *__cgo_undefined__2; }
#line 6 "not-int-const"
void __cgo_f_6_3(void) { enum { __cgo_undefined__3 = (dpiConn_getIsHealthy)*1 }; }
#line 6 "not-num-const"
void __cgo_f_6_4(void) { static const double __cgo_undefined__4 = (dpiConn_getIsHealthy); }
#line 6 "not-str-lit"
void __cgo_f_6_5(void) { static const char __cgo_undefined__5[] = (dpiConn_getIsHealthy); }
#line 7 "not-declared"
void __cgo_f_7_1(void) { __typeof__(dpiConn_getServerVersion) *__cgo_undefined__1; }
#line 7 "not-type"
void __cgo_f_7_2(void) { dpiConn_getServerVersion *__cgo_undefined__2; }
#line 7 "not-int-const"
void __cgo_f_7_3(void) { enum { __cgo_undefined__3 = (dpiConn_getServerVersion)*1 }; }
#line 7 "not-num-const"
void __cgo_f_7_4(void) { static const double __cgo_undefined__4 = (dpiConn_getServerVersion); }
#line 7 "not-str-lit"
void __cgo_f_7_5(void) { static const char __cgo_undefined__5[] = (dpiConn_getServerVersion); }
#line 8 "not-declared"
void __cgo_f_8_1(void) { __typeof__(dpiConn_newVar) *__cgo_undefined__1; }
#line 8 "not-type"
void __cgo_f_8_2(void) { dpiConn_newVar *__cgo_undefined__2; }
#line 8 "not-int-const"
void __cgo_f_8_3(void) { enum { __cgo_undefined__3 = (dpiConn_newVar)*1 }; }
#line 8 "not-num-const"
void __cgo_f_8_4(void) { static const double __cgo_undefined__4 = (dpiConn_newVar); }
#line 8 "not-str-lit"
void __cgo_f_8_5(void) { static const char __cgo_undefined__5[] = (dpiConn_newVar); }
#line 9 "not-declared"
void __cgo_f_9_1(void) { __typeof__(dpiConn_ping) *__cgo_undefined__1; }
#line 9 "not-type"
void __cgo_f_9_2(void) { dpiConn_ping *__cgo_undefined__2; }
#line 9 "not-int-const"
void __cgo_f_9_3(void) { enum { __cgo_undefined__3 = (dpiConn_ping)*1 }; }
#line 9 "not-num-const"
void __cgo_f_9_4(void) { static const double __cgo_undefined__4 = (dpiConn_ping); }
#line 9 "not-str-lit"
void __cgo_f_9_5(void) { static const char __cgo_undefined__5[] = (dpiConn_ping); }
#line 10 "not-declared"
void __cgo_f_10_1(void) { __typeof__(dpiConn_prepareStmt) *__cgo_undefined__1; }
#line 10 "not-type"
void __cgo_f_10_2(void) { dpiConn_prepareStmt *__cgo_undefined__2; }
#line 10 "not-int-const"
void __cgo_f_10_3(void) { enum { __cgo_undefined__3 = (dpiConn_prepareStmt)*1 }; }
#line 10 "not-num-const"
void __cgo_f_10_4(void) { static const double __cgo_undefined__4 = (dpiConn_prepareStmt); }
#line 10 "not-str-lit"
void __cgo_f_10_5(void) { static const char __cgo_undefined__5[] = (dpiConn_prepareStmt); }
#line 11 "not-declared"
void __cgo_f_11_1(void) { __typeof__(dpiConn_release) *__cgo_undefined__1; }
#line 11 "not-type"
void __cgo_f_11_2(void) { dpiConn_release *__cgo_undefined__2; }
#line 11 "not-int-const"
void __cgo_f_11_3(void) { enum { __cgo_undefined__3 = (dpiConn_release)*1 }; }
#line 11 "not-num-const"
void __cgo_f_11_4(void) { static const double __cgo_undefined__4 = (dpiConn_release); }
#line 11 "not-str-lit"
void __cgo_f_11_5(void) { static const char __cgo_undefined__5[] = (dpiConn_release); }
#line 12 "not-declared"
void __cgo_f_12_1(void) { __typeof__(dpiConn_rollback) *__cgo_undefined__1; }
#line 12 "not-type"
void __cgo_f_12_2(void) { dpiConn_rollback *__cgo_undefined__2; }
#line 12 "not-int-const"
void __cgo_f_12_3(void) { enum { __cgo_undefined__3 = (dpiConn_rollback)*1 }; }
#line 12 "not-num-const"
void __cgo_f_12_4(void) { static const double __cgo_undefined__4 = (dpiConn_rollback); }
#line 12 "not-str-lit"
void __cgo_f_12_5(void) { static const char __cgo_undefined__5[] = (dpiConn_rollback); }
#line 13 "not-declared"
void __cgo_f_13_1(void) { __typeof__(dpiConn_setAction) *__cgo_undefined__1; }
#line 13 "not-type"
void __cgo_f_13_2(void) { dpiConn_setAction *__cgo_undefined__2; }
#line 13 "not-int-const"
void __cgo_f_13_3(void) { enum { __cgo_undefined__3 = (dpiConn_setAction)*1 }; }
#line 13 "not-num-const"
void __cgo_f_13_4(void) { static const double __cgo_undefined__4 = (dpiConn_setAction); }
#line 13 "not-str-lit"
void __cgo_f_13_5(void) { static const char __cgo_undefined__5[] = (dpiConn_setAction); }
#line 14 "not-declared"
void __cgo_f_14_1(void) { __typeof__(dpiConn_setCallTimeout) *__cgo_undefined__1; }
#line 14 "not-type"
void __cgo_f_14_2(void) { dpiConn_setCallTimeout *__cgo_undefined__2; }
#line 14 "not-int-const"
void __cgo_f_14_3(void) { enum { __cgo_undefined__3 = (dpiConn_setCallTimeout)*1 }; }
#line 14 "not-num-const"
void __cgo_f_14_4(void) { static const double __cgo_undefined__4 = (dpiConn_setCallTimeout); }
#line 14 "not-str-lit"
void __cgo_f_14_5(void) { static const char __cgo_undefined__5[] = (dpiConn_setCallTimeout); }
#line 15 "not-declared"
void __cgo_f_15_1(void) { __typeof__(dpiConn_setClientIdentifier) *__cgo_undefined__1; }
#line 15 "not-type"
void __cgo_f_15_2(void) { dpiConn_setClientIdentifier *__cgo_undefined__2; }
#line 15 "not-int-const"
void __cgo_f_15_3(void) { enum { __cgo_undefined__3 = (dpiConn_setClientIdentifier)*1 }; }
#line 15 "not-num-const"
void __cgo_f_15_4(void) { static const double __cgo_undefined__4 = (dpiConn_setClientIdentifier); }
#line 15 "not-str-lit"
void __cgo_f_15_5(void) { static const char __cgo_undefined__5[] = (dpiConn_setClientIdentifier); }
#line 16 "not-declared"
void __cgo_f_16_1(void) { __typeof__(dpiConn_setClientInfo) *__cgo_undefined__1; }
#line 16 "not-type"
void __cgo_f_16_2(void) { dpiConn_setClientInfo *__cgo_undefined__2; }
#line 16 "not-int-const"
void __cgo_f_16_3(void) { enum { __cgo_undefined__3 = (dpiConn_setClientInfo)*1 }; }
#line 16 "not-num-const"
void __cgo_f_16_4(void) { static const double __cgo_undefined__4 = (dpiConn_setClientInfo); }
#line 16 "not-str-lit"
void __cgo_f_16_5(void) { static const char __cgo_undefined__5[] = (dpiConn_setClientInfo); }
#line 17 "not-declared"
void __cgo_f_17_1(void) { __typeof__(dpiConn_setDbOp) *__cgo_undefined__1; }
#line 17 "not-type"
void __cgo_f_17_2(void) { dpiConn_setDbOp *__cgo_undefined__2; }
#line 17 "not-int-const"
void __cgo_f_17_3(void) { enum { __cgo_undefined__3 = (dpiConn_setDbOp)*1 }; }
#line 17 "not-num-const"
void __cgo_f_17_4(void) { static const double __cgo_undefined__4 = (dpiConn_setDbOp); }
#line 17 "not-str-lit"
void __cgo_f_17_5(void) { static const char __cgo_undefined__5[] = (dpiConn_setDbOp); }
#line 18 "not-declared"
void __cgo_f_18_1(void) { __typeof__(dpiConn_setModule) *__cgo_undefined__1; }
#line 18 "not-type"
void __cgo_f_18_2(void) { dpiConn_setModule *__cgo_undefined__2; }
#line 18 "not-int-const"
void __cgo_f_18_3(void) { enum { __cgo_undefined__3 = (dpiConn_setModule)*1 }; }
#line 18 "not-num-const"
void __cgo_f_18_4(void) { static const double __cgo_undefined__4 = (dpiConn_setModule); }
#line 18 "not-str-lit"
void __cgo_f_18_5(void) { static const char __cgo_undefined__5[] = (dpiConn_setModule); }
#line 19 "not-declared"
void __cgo_f_19_1(void) { __typeof__(dpiConn_shutdownDatabase) *__cgo_undefined__1; }
#line 19 "not-type"
void __cgo_f_19_2(void) { dpiConn_shutdownDatabase *__cgo_undefined__2; }
#line 19 "not-int-const"
void __cgo_f_19_3(void) { enum { __cgo_undefined__3 = (dpiConn_shutdownDatabase)*1 }; }
#line 19 "not-num-const"
void __cgo_f_19_4(void) { static const double __cgo_undefined__4 = (dpiConn_shutdownDatabase); }
#line 19 "not-str-lit"
void __cgo_f_19_5(void) { static const char __cgo_undefined__5[] = (dpiConn_shutdownDatabase); }
#line 20 "not-declared"
void __cgo_f_20_1(void) { __typeof__(dpiConn_startupDatabase) *__cgo_undefined__1; }
#line 20 "not-type"
void __cgo_f_20_2(void) { dpiConn_startupDatabase *__cgo_undefined__2; }
#line 20 "not-int-const"
void __cgo_f_20_3(void) { enum { __cgo_undefined__3 = (dpiConn_startupDatabase)*1 }; }
#line 20 "not-num-const"
void __cgo_f_20_4(void) { static const double __cgo_undefined__4 = (dpiConn_startupDatabase); }
#line 20 "not-str-lit"
void __cgo_f_20_5(void) { static const char __cgo_undefined__5[] = (dpiConn_startupDatabase); }
#line 21 "not-declared"
void __cgo_f_21_1(void) { __typeof__(dpiData) *__cgo_undefined__1; }
#line 21 "not-type"
void __cgo_f_21_2(void) { dpiData *__cgo_undefined__2; }
#line 21 "not-int-const"
void __cgo_f_21_3(void) { enum { __cgo_undefined__3 = (dpiData)*1 }; }
#line 21 "not-num-const"
void __cgo_f_21_4(void) { static const double __cgo_undefined__4 = (dpiData); }
#line 21 "not-str-lit"
void __cgo_f_21_5(void) { static const char __cgo_undefined__5[] = (dpiData); }
#line 22 "not-declared"
void __cgo_f_22_1(void) { __typeof__(dpiNativeTypeNum) *__cgo_undefined__1; }
#line 22 "not-type"
void __cgo_f_22_2(void) { dpiNativeTypeNum *__cgo_undefined__2; }
#line 22 "not-int-const"
void __cgo_f_22_3(void) { enum { __cgo_undefined__3 = (dpiNativeTypeNum)*1 }; }
#line 22 "not-num-const"
void __cgo_f_22_4(void) { static const double __cgo_undefined__4 = (dpiNativeTypeNum); }
#line 22 "not-str-lit"
void __cgo_f_22_5(void) { static const char __cgo_undefined__5[] = (dpiNativeTypeNum); }
#line 23 "not-declared"
void __cgo_f_23_1(void) { __typeof__(dpiObjectType) *__cgo_undefined__1; }
#line 23 "not-type"
void __cgo_f_23_2(void) { dpiObjectType *__cgo_undefined__2; }
#line 23 "not-int-const"
void __cgo_f_23_3(void) { enum { __cgo_undefined__3 = (dpiObjectType)*1 }; }
#line 23 "not-num-const"
void __cgo_f_23_4(void) { static const double __cgo_undefined__4 = (dpiObjectType); }
#line 23 "not-str-lit"
void __cgo_f_23_5(void) { static const char __cgo_undefined__5[] = (dpiObjectType); }
#line 24 "not-declared"
void __cgo_f_24_1(void) { __typeof__(dpiOracleTypeNum) *__cgo_undefined__1; }
#line 24 "not-type"
void __cgo_f_24_2(void) { dpiOracleTypeNum *__cgo_undefined__2; }
#line 24 "not-int-const"
void __cgo_f_24_3(void) { enum { __cgo_undefined__3 = (dpiOracleTypeNum)*1 }; }
#line 24 "not-num-const"
void __cgo_f_24_4(void) { static const double __cgo_undefined__4 = (dpiOracleTypeNum); }
#line 24 "not-str-lit"
void __cgo_f_24_5(void) { static const char __cgo_undefined__5[] = (dpiOracleTypeNum); }
#line 25 "not-declared"
void __cgo_f_25_1(void) { __typeof__(dpiShutdownMode) *__cgo_undefined__1; }
#line 25 "not-type"
void __cgo_f_25_2(void) { dpiShutdownMode *__cgo_undefined__2; }
#line 25 "not-int-const"
void __cgo_f_25_3(void) { enum { __cgo_undefined__3 = (dpiShutdownMode)*1 }; }
#line 25 "not-num-const"
void __cgo_f_25_4(void) { static const double __cgo_undefined__4 = (dpiShutdownMode); }
#line 25 "not-str-lit"
void __cgo_f_25_5(void) { static const char __cgo_undefined__5[] = (dpiShutdownMode); }
#line 26 "not-declared"
void __cgo_f_26_1(void) { __typeof__(dpiStartupMode) *__cgo_undefined__1; }
#line 26 "not-type"
void __cgo_f_26_2(void) { dpiStartupMode *__cgo_undefined__2; }
#line 26 "not-int-const"
void __cgo_f_26_3(void) { enum { __cgo_undefined__3 = (dpiStartupMode)*1 }; }
#line 26 "not-num-const"
void __cgo_f_26_4(void) { static const double __cgo_undefined__4 = (dpiStartupMode); }
#line 26 "not-str-lit"
void __cgo_f_26_5(void) { static const char __cgo_undefined__5[] = (dpiStartupMode); }
#line 27 "not-declared"
void __cgo_f_27_1(void) { __typeof__(dpiStmt) *__cgo_undefined__1; }
#line 27 "not-type"
void __cgo_f_27_2(void) { dpiStmt *__cgo_undefined__2; }
#line 27 "not-int-const"
void __cgo_f_27_3(void) { enum { __cgo_undefined__3 = (dpiStmt)*1 }; }
#line 27 "not-num-const"
void __cgo_f_27_4(void) { static const double __cgo_undefined__4 = (dpiStmt); }
#line 27 "not-str-lit"
void __cgo_f_27_5(void) { static const char __cgo_undefined__5[] = (dpiStmt); }
#line 28 "not-declared"
void __cgo_f_28_1(void) { __typeof__(dpiStmt_getInfo) *__cgo_undefined__1; }
#line 28 "not-type"
void __cgo_f_28_2(void) { dpiStmt_getInfo *__cgo_undefined__2; }
#line 28 "not-int-const"
void __cgo_f_28_3(void) { enum { __cgo_undefined__3 = (dpiStmt_getInfo)*1 }; }
#line 28 "not-num-const"
void __cgo_f_28_4(void) { static const double __cgo_undefined__4 = (dpiStmt_getInfo); }
#line 28 "not-str-lit"
void __cgo_f_28_5(void) { static const char __cgo_undefined__5[] = (dpiStmt_getInfo); }
#line 29 "not-declared"
void __cgo_f_29_1(void) { __typeof__(dpiVar) *__cgo_undefined__1; }
#line 29 "not-type"
void __cgo_f_29_2(void) { dpiVar *__cgo_undefined__2; }
#line 29 "not-int-const"
void __cgo_f_29_3(void) { enum { __cgo_undefined__3 = (dpiVar)*1 }; }
#line 29 "not-num-const"
void __cgo_f_29_4(void) { static const double __cgo_undefined__4 = (dpiVar); }
#line 29 "not-str-lit"
void __cgo_f_29_5(void) { static const char __cgo_undefined__5[] = (dpiVar); }
#line 30 "not-declared"
void __cgo_f_30_1(void) { __typeof__(dpiVersionInfo) *__cgo_undefined__1; }
#line 30 "not-type"
void __cgo_f_30_2(void) { dpiVersionInfo *__cgo_undefined__2; }
#line 30 "not-int-const"
void __cgo_f_30_3(void) { enum { __cgo_undefined__3 = (dpiVersionInfo)*1 }; }
#line 30 "not-num-const"
void __cgo_f_30_4(void) { static const double __cgo_undefined__4 = (dpiVersionInfo); }
#line 30 "not-str-lit"
void __cgo_f_30_5(void) { static const char __cgo_undefined__5[] = (dpiVersionInfo); }
#line 31 "not-declared"
void __cgo_f_31_1(void) { __typeof__(free) *__cgo_undefined__1; }
#line 31 "not-type"
void __cgo_f_31_2(void) { free *__cgo_undefined__2; }
#line 31 "not-int-const"
void __cgo_f_31_3(void) { enum { __cgo_undefined__3 = (free)*1 }; }
#line 31 "not-num-const"
void __cgo_f_31_4(void) { static const double __cgo_undefined__4 = (free); }
#line 31 "not-str-lit"
void __cgo_f_31_5(void) { static const char __cgo_undefined__5[] = (free); }
#line 32 "not-declared"
void __cgo_f_32_1(void) { __typeof__(int) *__cgo_undefined__1; }
#line 32 "not-type"
void __cgo_f_32_2(void) { int *__cgo_undefined__2; }
#line 32 "not-int-const"
void __cgo_f_32_3(void) { enum { __cgo_undefined__3 = (int)*1 }; }
#line 32 "not-num-const"
void __cgo_f_32_4(void) { static const double __cgo_undefined__4 = (int); }
#line 32 "not-str-lit"
void __cgo_f_32_5(void) { static const char __cgo_undefined__5[] = (int); }
#line 33 "not-declared"
void __cgo_f_33_1(void) { __typeof__(sizeof(dpiSubscrMessageTable)) *__cgo_undefined__1; }
#line 33 "not-type"
void __cgo_f_33_2(void) { sizeof(dpiSubscrMessageTable) *__cgo_undefined__2; }
#line 33 "not-int-const"
void __cgo_f_33_3(void) { enum { __cgo_undefined__3 = (sizeof(dpiSubscrMessageTable))*1 }; }
#line 33 "not-num-const"
void __cgo_f_33_4(void) { static const double __cgo_undefined__4 = (sizeof(dpiSubscrMessageTable)); }
#line 33 "not-str-lit"
void __cgo_f_33_5(void) { static const char __cgo_undefined__5[] = (sizeof(dpiSubscrMessageTable)); }
#line 34 "not-declared"
void __cgo_f_34_1(void) { __typeof__(unsigned int) *__cgo_undefined__1; }
#line 34 "not-type"
void __cgo_f_34_2(void) { unsigned int *__cgo_undefined__2; }
#line 34 "not-int-const"
void __cgo_f_34_3(void) { enum { __cgo_undefined__3 = (unsigned int)*1 }; }
#line 34 "not-num-const"
void __cgo_f_34_4(void) { static const double __cgo_undefined__4 = (unsigned int); }
#line 34 "not-str-lit"
void __cgo_f_34_5(void) { static const char __cgo_undefined__5[] = (unsigned int); }
#line 35 "not-declared"
void __cgo_f_35_1(void) { __typeof__(uint32_t) *__cgo_undefined__1; }
#line 35 "not-type"
void __cgo_f_35_2(void) { uint32_t *__cgo_undefined__2; }
#line 35 "not-int-const"
void __cgo_f_35_3(void) { enum { __cgo_undefined__3 = (uint32_t)*1 }; }
#line 35 "not-num-const"
void __cgo_f_35_4(void) { static const double __cgo_undefined__4 = (uint32_t); }
#line 35 "not-str-lit"
void __cgo_f_35_5(void) { static const char __cgo_undefined__5[] = (uint32_t); }
#line 1 "completed"
int __cgo__1 = __cgo__2;

full error output:
cc1: error: unrecognized command line option "-fno-lto"

**Comment by shizhoulong356** [comment]
it seems not compitionable  with the centos6  ,but centos7 is ok ?
