### ISSUE TITLE
categraf是否能支持olap数据库clickhouse的性能指标采集？

### ISSUE THREAD

**Issue by lishijiang** [flashcatcloud/categraf#15]
**What would you like to be added**:

**Why is this needed**:

**Describe the solution you'd like**

**Additional context**

**Comment by lishijiang** [comment]
新的版本的支持prometheus接口拉取指标

**Comment by UlricQin** [comment]
prom 生态是真牛逼，clickhouse、rabbitmq、zookeeper、nginx_vts  等，相当于都内置支持了 prometheus 来暴露监控数据
