### ISSUE TITLE
k8s部署客户端触发空指针。

### ISSUE THREAD

**Issue by DuanxianshengGO** [flashcatcloud/categraf#151]
[root@m1 kubelet.service.d]# kubectl  logs -f -n n9e nightingale-categraf-7sz2d 
/entrypoint.sh: 5: setcap: not found
Failed to set additional capabilities on /usr/bin/categraf
2022/08/12 01:51:16 main.go:113: I! runner.binarydir: /usr/bin
2022/08/12 01:51:16 main.go:114: I! runner.hostname: m3
2022/08/12 01:51:16 main.go:115: I! runner.fd_limits: (soft=1048576, hard=1048576)
2022/08/12 01:51:16 main.go:116: I! runner.vm_limits: (soft=unlimited, hard=unlimited)
2022/08/12 01:51:16 config.go:33: I! tracing disabled
2022/08/12 01:51:16 agent.go:65: I! agent starting
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2e587f4]

goroutine 80 [running]:
flashcat.cloud/categraf/api.Start()
	/home/runner/work/categraf/categraf/api/server.go:17 +0x34
created by main.main
	/home/runner/work/categraf/categraf/main.go:70 +0x171

**Comment by kongfei605** [comment]
这个是因为v0.2.9的版本引入新功能，挂载的配置中没有。
方案一：修改image:  `flashcatcloud/categraf:latest` 为 `image: flashcatcloud/categraf:v0.2.8` 
或者 
方案二：`imagePullPolicy: IfNotPresent` 修改为 `imagePullPolicy: Always` 再重新部署下

**Comment by DuanxianshengGO** [comment]
问题已解决，thanks
