### ISSUE TITLE
Categraf 能以daemonset的形式部署在k8s中采集集群节点的监控指标吗

### ISSUE THREAD

**Issue by hctech** [flashcatcloud/categraf#16]

**Comment by UlricQin** [comment]
可以daemonset方式部署，目前可以采集机器的相关监控数据和docker容器的监控数据，下周继续完善

**Comment by hctech** [comment]
除了将 `/proc` 和 `/sys` 目录挂载至容器内，还需要注意什么

**Comment by UlricQin** [comment]
@kongfei605 请孔老师帮忙解答一下？或者咱们直接提供镜像和daemonset的yaml

**Comment by kongfei605** [comment]
可以的。yaml文件在https://github.com/flashcatcloud/categraf/blob/main/k8s/categraf.yaml  。记得替换其中的``` NSERVER_SERVICE_WITH_PORT``` 为集群的nserver ip:port
