### ISSUE TITLE
有支持sqlserver的计划吗？

### ISSUE THREAD

**Issue by shawnloong** [flashcatcloud/categraf#169]
**What would you like to be added**:

**Why is this needed**:

**Describe the solution you'd like**

**Additional context**

**Comment by kongfei605** [comment]
有。 后续pg/sqlserver/mariadb/sqlite等等， 都会支持。优先级排在mtail、snmp插件之后

**Comment by lsy1990** [comment]
为啥会支持sqlite，那都是嵌入式的啊：）

**Comment by kongfei605** [comment]
> 为啥会支持sqlite，那都是嵌入式的啊：）

顺带支持上

**Comment by kongfei605** [comment]
https://github.com/flashcatcloud/categraf/pull/207/files ，sqlserver已经merge到main分支了 @shawnloong ，着急用可以先自己build一个版本哈

**Comment by kongfei605** [comment]
v0.2.15已经支持了sqlserver，欢迎试用
