### ISSUE TITLE
logs.toml 配置中的[[logs.Processing_rules]]有使用范例吗？

### ISSUE THREAD

**Issue by qiqiaobin** [flashcatcloud/categraf#186]
想使用categraf自带的日志监控功能，看了datadog的日志解析规则，自己尝试配置，但是test的时候报错了，failed to init config: failed to load configs of dir: conf err:toml: line 99 (last key "logs.Processing_rules"): expected '.' or '=', but got '%' instead

**Comment by qiqiaobin** [comment]
已经解决这个问题，撸了datadog的文档，看了categraf的源码，知晓了如何配置日志解析规则。

**Comment by UlricQin** [comment]
好奇具体是咋搞的？我一直没有用过日志这块采集逻辑
