### ISSUE TITLE
build fail  fatal error: pcap.h: No such file or directory

### ISSUE THREAD

**Issue by mamh2021** [flashcatcloud/categraf#196]
### Relevant config.toml

```toml
# github.com/google/gopacket/pcap
../../../.go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap_unix.go:34:10: fatal error: pcap.h: No such file or directory
 #include <pcap.h>
          ^~~~~~~~
compilation terminated.
```

### Logs from categraf

```text
fatal error: pcap.h: No such file or directory
```

### System info

 fatal error: pcap.h: No such file or directory

### Steps to reproduce

1. fatal error: pcap.h: No such file or directory
2.
3.
...

### Expected behavior

 fatal error: pcap.h: No such file or directory

### Actual behavior

 fatal error: pcap.h: No such file or directory

**Comment by UlricQin** [comment]
你在什么平台编译的

**Comment by mamh2021** [comment]
Description:    Ubuntu 18.04.6 LTS

**Comment by UlricQin** [comment]
`sudo apt-get install libpcap-dev`

**Comment by UlricQin** [comment]
或者拉最新的代码，我给 arp_packet 加了一个特殊的编译 tag，默认不会编译进去了
