### ISSUE TITLE
上报的指标有没有可能兼容 node exporter

### ISSUE THREAD

**Issue by oiooj** [flashcatcloud/categraf#20]
目前很多公司在使用原生的 node exporter 来监控公司的业务服务器，指标的名称、类型、标签可能和目前的 categraf 都是不兼容的，很难平滑的迁移到 categraf 上，可能无法复用之前的 rules 和一些配置（dashboard）。

有没有什么比较好的方式让这批用户比较简单的迁移到 categraf 上？

**Comment by UlricQin** [comment]
对于机器层面的监控，categraf 提供了[监控大盘](https://github.com/flashcatcloud/categraf/blob/main/inputs/system/dashboard.json)和[告警规则](https://github.com/flashcatcloud/categraf/blob/main/inputs/system/alerts-linux.json)，导入即可使用。

**Comment by oiooj** [comment]
> 对于机器层面的监控，categraf 提供了[监控大盘](https://github.com/flashcatcloud/categraf/blob/main/inputs/system/dashboard.json)和[告警规则](https://github.com/flashcatcloud/categraf/blob/main/inputs/system/alerts-linux.json)，导入即可使用。现在 categraf 的指标名称更多的是和 telegraf 保持一致，node exporter 的机器指标，很多是需要在服务端二次计算的，对于新手不太友好

监控大盘和告警规则文件是什么标准？Grafana 或者 原生的 rule 可以支持吗，还是说服务端必须使用 n9e 的服务？

**Comment by UlricQin** [comment]
> > 对于机器层面的监控，categraf 提供了[监控大盘](https://github.com/flashcatcloud/categraf/blob/main/inputs/system/dashboard.json)和[告警规则](https://github.com/flashcatcloud/categraf/blob/main/inputs/system/alerts-linux.json)，导入即可使用。现在 categraf 的指标名称更多的是和 telegraf 保持一致，node exporter 的机器指标，很多是需要在服务端二次计算的，对于新手不太友好
> 
> 
> 
> 监控大盘和告警规则文件是什么标准？Grafana 或者 原生的 rule 可以导入吗，还是说服务端必须使用 n9e 的服务？

夜莺前端v5.5.0以上可以支持grafana大盘导入，不过因为夜莺和grafana大盘不是100%一样的，所以无法完全兼容，只能搞定常用的图表类型，告警规则未来会支持导入prometheus的规则，现在还不支持，现在阶段要做迁移的话，需要手工拷贝原来alerting rule中的promql创建夜莺里的告警规则，后面会着手支持。

至于夜莺的大盘和告警规则的格式，可以在夜莺里创建几条，选中导出，就可以看到json的格式了
