### ISSUE TITLE
客户端无法联网报错

### ISSUE THREAD

**Issue by shawnloong** [flashcatcloud/categraf#203]
failed to init config: failed to get outbound ip: dial udp 8.8.8.8:80，是否可以去掉公网检测
// Get preferred outbound ip of this machine
func GetOutboundIP() (net.IP, error) {
	conn, err := net.Dial("udp", "8.8.8.8:80")
	if err != nil {
		return nil, fmt.Errorf("failed to get outbound ip: %v", err)
	}
	defer conn.Close()

	localAddr := conn.LocalAddr().(*net.UDPAddr)

	return localAddr.IP, nil
}

**Comment by UlricQin** [comment]
之所以会自动探测本机IP，是因为 hostname 字段配置了 `"$ip"` 。最简单的解法：不要使用自动探测IP功能，即 hostname 字段中不要配置 `$ip`，如果想上报本机IP，就写死本机IP。当然，这样每个机器分别手写本机IP不方便，建议使用批量执行工具，做sed替换，通过脚本获取本机IP，然后sed替换配置文件，把ip填充上

**Comment by shawnloong** [comment]
批量安装目前是这样做的，不过hostname没有替换，直接用变量
