### ISSUE TITLE
prometheus插件 是否可以增加一个类似target_up的metric?

### ISSUE THREAD

**Issue by wy281704862** [flashcatcloud/categraf#204]
目前使用prometheus插件进行抓取数据的时候，服务异常，插件抓取/metrics接口获取数据的时候，不能获取到数据。希望增加一个metric，用来标记接口调用失败或目标服务异常。

**Comment by 710leo** [comment]
你这个需求可以通过 [http_response](https://github.com/flashcatcloud/categraf/tree/main/inputs/http_response) 插件来满足

**Comment by UlricQin** [comment]
现在就有，用的指标名字叫 up

**Comment by wy281704862** [comment]
感谢，已经使用up指标来判断
