### ISSUE TITLE
请问categraf支持centos 6吗

### ISSUE THREAD

**Issue by czxin788** [flashcatcloud/categraf#205]
centos 7上可以正常运行categraf，但是centos 6上无法运行，请问categraf支持centos 6吗。
在centos 6运行时报如下错误：
 ./categraf --help
./categraf: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./categraf)

categraf版本是：categraf-v0.2.13

我们有好多个centos 6的机器，需要用夜莺监控centos 6操作系统，可以实现吗。

**Comment by shawnloong** [comment]
升级 一下glibc

**Comment by UlricQin** [comment]
或者自己在centos6下编译一个就行

**Comment by czxin788** [comment]
谢谢，可以了。

1、安装go环境
wget https://dl.google.com/go/go1.19.2.linux-amd64.tar.gz
tar -xvf go1.19.2.linux-amd64.tar.gz
mv go /usr/loca/
cat /etc/profile
export GOROOT=/usr/local/go
export PATH=$GOROOT/bin/:/usr/local/mysql/bin/:"$PATH:$MYSQL_HOME/bin"
:wq
source /etc/profile

2、在centos 6上编译categraf
wget https://github.com/flashcatcloud/categraf/archive/refs/tags/v0.2.14.zip
cd categraf-0.2.14
export GO111MODULE=on
export GOPROXY=https://goproxy.cn
go build
mkdir /opt/categraf
cp -a  categraf  /opt/categraf
cp -a conf /opt/categraf

3、在centos 6上启动categraf
/opt/categraf/categraf
