### ISSUE TITLE
建议告警恢复的通知加个告警恢复时长

### ISSUE THREAD

**Issue by czxin788** [flashcatcloud/categraf#208]
**What would you like to be added**:
我想在告警恢复的通知中加个告警时长。

**Why is this needed**:
因为这样很方便让运维人员知晓这个故障用了多长时间恢复的。

**Describe the solution you'd like**
夜莺的告警恢复通知是这样的：
![image](https://user-images.githubusercontent.com/13861904/194809537-3c5f5dc2-6096-47a5-bf6e-77cfa4d60fda.png)

我们zabbix的告警恢复通知是这样的，有告警时长，很容易看出这个故障持续了大概5分钟：
![image](https://user-images.githubusercontent.com/13861904/194809652-8c3ff2ef-37dc-447d-a044-0383c0e6f7f8.png)

**Additional context**
无

**Comment by UlricQin** [comment]
可以自行修改模板文件达成此目的。etc/template下面，恢复时间减去告警时间(TriggerTime)就行，熟悉一下Go template语法，很容易实现

**Comment by UlricQin** [comment]
可以自行修改模板文件达成此目的。etc/template下面，恢复时间减去告警时间(TriggerTime)就行，熟悉一下Go template语法，很容易实现。另外，这类问题后面提交到 [论坛](https://github.com/ccfos/nightingale/discussions) 去吧，不要提到categraf的repo里

**Comment by czxin788** [comment]
收到，谢谢
