### ISSUE TITLE
监控k8s

### ISSUE THREAD

**Issue by wangxiajian** [flashcatcloud/categraf#209]
您好，我在使用kubectl apply -n monitoring -f k8s/deployment.yaml 发生pod内有报错

![image](https://user-images.githubusercontent.com/67364083/195026149-bd015e20-50f4-4699-9108-a07887d3a992.png)
 deployment.yaml 配置
![image](https://user-images.githubusercontent.com/67364083/195026466-2534e96c-8e4b-4771-94f8-c4e47bda25b6.png)

**Comment by kongfei605** [comment]
这里要填etcd内容，不是路径

**Comment by wangxiajian** [comment]
好的，知道了，十分感谢
