### ISSUE TITLE
categraf 推送标签ident作为标识中有特殊符号使用，导致状态为dowb

### ISSUE THREAD

**Issue by stiei13wangluo** [flashcatcloud/categraf#211]
主要是想使用url地址为标识
暂时发现url中有?特殊符号作为ident为出现该问题
通过即时查询，发现数据正常

<img width="1494" alt="image" src="https://user-images.githubusercontent.com/10474594/195664066-2d5ea4e6-1699-409d-b439-6c389db5a23a.png">

<img width="1693" alt="image" src="https://user-images.githubusercontent.com/10474594/195665502-86ecee56-8f4e-43ce-948c-1640494ce35e.png">

**Comment by UlricQin** [comment]
不建议把url作为ident。这个产品层面不会针对特殊字符做特殊处理。监控对象列表，建议只注册机器，顶多再加上网络设备ip
