### ISSUE TITLE
下载新版本无法启动

### ISSUE THREAD

**Issue by Chuck-ng** [flashcatcloud/categraf#222]
你好
在windows环境下，刚下载了最新的0.2.16版本并覆盖在原来categraf文件夹里（之前是0.2.14），然后运行出现了以下错误
PS C:\Program Files\categraf> .\categraf.exe
2022/10/26 17:15:11 main.go:118: I! runner.binarydir: C:\Program Files\categraf
2022/10/26 17:15:11 main.go:119: I! runner.hostname: A
2022/10/26 17:15:11 main.go:120: I! runner.fd_limits: N/A
2022/10/26 17:15:11 main.go:121: I! runner.vm_limits: N/A
2022/10/26 17:15:11 main.go:65: F! failed to init config: failed to load configs of dir: conf err:toml: line 108: Key 'global' has already been defined.
请问这个怎么解决？
万分感谢！

**Comment by UlricQin** [comment]
你的配置文件配置的不对。可以去conf目录下执行下面的命令，看看哪里配置了global：
```shell
cd conf
grep global -r .
```

**Comment by Chuck-ng** [comment]
你好，
我比较过，除了config.toml下的global其他的都被注释掉了，然后2.14和2.16的config.toml我也比较过是一样。因为是直接下载2.16然后只是改了config.toml的接收目标端口。现在真不知道哪里出了问题了......
望能解惑。
非常感谢

________________________________

**Comment by UlricQin** [comment]
我发了命令了，你得截图给我看啊。我本地测试没问题，大概率是你的配置问题：

```
[work@tt-fc-dev01.nj categraf]$ git status
位于分支 main
您的分支与上游分支 'origin/main' 一致。

无文件要提交，干净的工作区
[work@tt-fc-dev01.nj categraf]$ make
Building version v0.2.16-8d71470800a38472897bcfcbaa333b37e0916010
[work@tt-fc-dev01.nj categraf]$ ./categraf --test
2022/10/27 14:54:20 main.go:110: I! runner.binarydir: /home/work/go/src/categraf
2022/10/27 14:54:20 main.go:111: I! runner.hostname: tt-fc-dev01.nj
2022/10/27 14:54:20 main.go:112: I! runner.fd_limits: (soft=655360, hard=655360)
2022/10/27 14:54:20 main.go:113: I! runner.vm_limits: (soft=unlimited, hard=unlimited)
2022/10/27 14:54:20 config.go:33: I! tracing disabled
2022/10/27 14:54:20 provider.go:63: I! use input provider: [local]
2022/10/27 14:54:20 agent.go:85: I! agent starting
2022/10/27 14:54:20 metrics_agent.go:37: E! input: local.arp_packet not supported
2022/10/27 14:54:20 metrics_agent.go:93: I! input: local.conntrack started
2022/10/27 14:54:20 metrics_agent.go:93: I! input: local.cpu started
2022/10/27 14:54:20 metrics_agent.go:93: I! input: local.disk started
```

**Comment by Chuck-ng** [comment]
主要我在windows下没装git，只能用fc来比较几个主要的配置文件，然后执行文件都是直接下载来用的，没试过编译源代码来使用，可能是中间有些文件在windows下有些问题？我在github上比较了2.14和2.16实在太多增减了，我没法确定原因

________________________________

**Comment by kongfei605** [comment]
检查下是否有隐藏文件，看报错是global重复定义。另外，git只是用来管理代码版本的 ，启动有一个config.toml 就可以了，需要哪个插件再去找对应插件的配置。

**Comment by Chuck-ng** [comment]
今天重新下载过压缩文件，没有手改配置文件，直接把配置文件直接覆盖又没问题了，有可能是之前配置文件的问题。十分谢谢

________________________________
