### ISSUE TITLE
categraf.log能否手动关闭

### ISSUE THREAD

**Issue by liufangpeng** [flashcatcloud/categraf#226]
categraf-windows版本，运行之后会输出categraf.log运行日志会一直打印，有什么方法可以关闭吗，担心长时间打印会占用磁盘过高

**Comment by kongfei605** [comment]
windows也支持重定向 。
类似 xxx  2>NUL 1>NUL

**Comment by liufangpeng** [comment]
![图片](https://user-images.githubusercontent.com/73222197/198554223-bd6938c6-5c8a-4b81-9eec-12725bb3a86d.png)
重定向了但是内容并没有更改

**Comment by liufangpeng** [comment]
![图片](https://user-images.githubusercontent.com/73222197/198555095-ba5ea506-e639-4f09-839a-9b1cb79a680c.png)
使用这种甚至 echo off 都会提示进程正在使用，想实现自动清理

**Comment by kongfei605** [comment]
> ![图片](https://user-images.githubusercontent.com/73222197/198554223-bd6938c6-5c8a-4b81-9eec-12725bb3a86d.png) 重定向了但是内容并没有更改

这个不是没有内容输出标准输出么？ 这个就是符合预期的。你的启动脚本内容呢？

**Comment by kongfei605** [comment]
这样吧，你贴你的启动脚本内容

**Comment by liufangpeng** [comment]
我用的categraf.exe --win-service-install这个命令启动的，意思就是categraf.exe --win-service-install 2>NUL 1>NUL这个意思吗

**Comment by kongfei605** [comment]
> 



> 我用的categraf.exe --win-service-install这个命令启动的，意思就是categraf.exe --win-service-install 2>NUL 1>NUL这个意思吗

你编辑一下这个服务（控制面板-》 管理员工具-》 服务-》 categraf），应该有个logging选项。

可以参考以下链接。
https://confluence.atlassian.com/jirakb/how-to-disable-jira-stdout-and-jira-stderr-logging-on-windows-1071822733.html

**Comment by kongfei605** [comment]
如果没有其他问题，这个issue先关闭了。
