### ISSUE TITLE
categraf采集指标

### ISSUE THREAD

**Issue by liufangpeng** [flashcatcloud/categraf#228]
怎么样去收集windows的GPU指标呢

**Comment by UlricQin** [comment]
试试 nvidia_smi 插件

**Comment by liufangpeng** [comment]
这个方法好像行不通

**Comment by liufangpeng** [comment]
只是需要安装nvidia_smi插件就可以了吗还需要配置什么吗
![图片](https://user-images.githubusercontent.com/73222197/199134418-84ace344-a45e-4755-9680-d25651625426.png)

**Comment by UlricQin** [comment]
nvidia_smi_command 这个参数配置为你机器上的 nvidia_smi 的路径

**Comment by liufangpeng** [comment]
绝对路径吗，或者说我在cmd输入nvidia-smi命令能看到返回结果，nvidia_smi_command = “nvidia-smi”这样配置可以吗

**Comment by UlricQin** [comment]
> 绝对路径吗，或者说我在cmd输入nvidia-smi命令能看到返回结果，nvidia_smi_command = “nvidia-smi”这样配置可以吗

既然提了两种猜测，为啥不去测试一下呢，电脑又不会爆炸

**Comment by kongfei605** [comment]
issue先关闭了，有重复问题可以随时打开
