### ISSUE TITLE
未来有没有支持多种output的规划

### ISSUE THREAD

**Issue by Ohimma** [flashcatcloud/categraf#240]
目前只支持output到n9e server。
未来会不会支持output成prometheus_client数据或者output到influxdb的方式

**Comment by UlricQin** [comment]
并非只支持发给 n9e-server，而是通过remote write协议发往所有支持remote write协议的后端，prometheus、influxdb、thanos、m3、VictoriaMetrics等，都支持remote write 接口

**Comment by Ohimma** [comment]
哦哦，那会不会支持 类似exporter客户端的方式，让prometheus过来拉数据

**Comment by UlricQin** [comment]
不支持
