### ISSUE TITLE
把ibex-agent集成进来

### ISSUE THREAD

**Issue by UlricQin** [flashcatcloud/categraf#242]
让用户少部署一个 agent，如果能够顺带解决 ibex-agent 无法在 windows下运行的问题就更好了

**Comment by luoxjie** [comment]
期待大佬能早日实现，现在新增服务器初始化时，还得多部署多1个agent

**Comment by hagic-hhj** [comment]
目前已经集成了，同时支持windows系统bat脚本

**Comment by UlricQin** [comment]
👍🏻
