### ISSUE TITLE
snmp监控指标能批量监控吗

### ISSUE THREAD

**Issue by liufangpeng** [flashcatcloud/categraf#244]
目前snmp里面是单点收集有什么办法能够批量收集吗

**Comment by kongfei605** [comment]
instances 和agents都是数组 ，你说的单点收集是什么意思？

**Comment by liufangpeng** [comment]
我的意思是能范围性收集吗 例如网段

**Comment by kongfei605** [comment]
这个不支持统配符/网段，要明确指定采集的ip:port

**Comment by UlricQin** [comment]
可以写个cron，解析网段内的ip列表，自动生成categraf的配置，如果发现IP列表变了就 kill -HUP `pidof categraf` 重新加载一下categraf的配置，如果发现IP列表没变，就不用重新加载了
