### ISSUE TITLE
磁盘故障的探测

### ISSUE THREAD

**Issue by loveyang2012** [flashcatcloud/categraf#248]
主机磁盘硬件故障能否探测到？如图
在主机上执行 dmesg 可以看到硬件异常
![image](https://user-images.githubusercontent.com/24237714/201589793-a676ab78-e02e-471f-93f0-4b2e3ea92be4.png)

**Comment by kongfei605** [comment]
图看不到。所有通过日志采集的，都可以通过mtail插件来实现

**Comment by UlricQin** [comment]
我再补充两个招：
1、通过exec自定义插件脚本，比如执行 `dmesg|grep -i "i/o error"`
2、还是通过exec自定义插件脚本，往各个分区里写一个临时文件，然后再删掉，以此探测是否可以读写

**Comment by lsy1990** [comment]
我觉得@kongfei605 的方法，更容易标准化，我在按这个思路，再整理配置文件

**Comment by xiehaitang** [comment]
node_exporter是可以探测到的，可以参考一下node_exporter做法

**Comment by kongfei605** [comment]
categraf v0.2.36增加了一个disk_device_error指标 ，可以下载了
