### ISSUE TITLE
非k8s服务器使用 categraf 链接k8s部署的n9e时报错

### ISSUE THREAD

**Issue by lyitt1987** [flashcatcloud/categraf#250]
categraf 报错如下
 post to http://172.16.26.57:31900/prometheus/v1/write got error: Post "http://172.16.26.57:31900/prometheus/v1/write": dial tcp 172.16.26.57:31900: i/o timeout

nserver的svc文件内容如下
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: nightingale
    meta.helm.sh/release-namespace: n9e
  labels:
    app: n9e
    app.kubernetes.io/managed-by: Helm
    chart: nightingale
    heritage: Helm
    release: nightingale
  name: n9e-nserver-svc
  namespace: n9e
spec:
  ports:
  - name: nserver-port
    port: 80
    protocol: TCP
    targetPort: 19000
    nodePort: 31900
  selector:
    app: n9e
    component: nserver
    release: nightingale
  type: NodePort

非k8s服务器telnet nserver端口是通的
![image](https://user-images.githubusercontent.com/35764082/201870431-e5fb328c-13c3-46df-8294-1eedb1556d81.png)

**Comment by UlricQin** [comment]
偶尔报错没事，可能是网络抖动

**Comment by lyitt1987** [comment]
好的，谢谢，我再观察观察

**Comment by kongfei605** [comment]
issue先关闭了，如果再有重复问题可以随时打开
