### ISSUE TITLE
sqlserver缺少数据库状态指标(up or down)

### ISSUE THREAD

**Issue by shawnloong** [flashcatcloud/categraf#252]
**What would you like to be added**:

**Why is this needed**:

**Describe the solution you'd like**

**Additional context**

**Comment by UlricQin** [comment]
@lsy1990 阳哥~要不要来个PR :) sqlserver_up 来标识是否能连上，sql_scrape_use_seconds 来标识抓取花费了多少时间？

**Comment by lsy1990** [comment]
好，我来搞下

**Comment by lsy1990** [comment]
@UlricQin 我来搞下

**Comment by kongfei605** [comment]
v0.2.22 已经发布，带上了@lsy新增的up/down指标
  @shawnloong 可以使用v0.2.22版本了

**Comment by shawnloong** [comment]
@kongfei605 感谢
