### ISSUE TITLE
HELP: 配置了mongodb监控, 很多metrics获取不到

### ISSUE THREAD

**Issue by lunuan** [flashcatcloud/categraf#255]
帮忙看下是哪里配置的不对呢

![image](https://user-images.githubusercontent.com/44047817/202434433-ac2f4ccc-0174-417d-b7e4-9b267de4543f.png)

配置文件
```
[[instances]]
mongodb_uri = "mongodb://monitor:xxxxxxx@172.20.81.27:27017"
collect_all = true
labels = { instance="172.20.81.27:27017", cluster="feat"}
```

日志一直在报这个
```
time="2022-11-17T19:34:42+08:00" level=error msg="cannot auto discover databases and collections"

time="2022-11-17T19:34:42+08:00" level=error msg="cannot auto discover databases and collections: cannot list the collections for \"feat\": cannot get the list of collections for discovery: (Unauthorized) not authorized on feat to execute command { listCollections: 1, filter: {}, nameOnly: true, cursor: {}, lsid: { id: UUID(\"0bbc9880-92ad-4eeb-9b9a-5479c71100df\") }, $clusterTime: { clusterTime: Timestamp(1668684880, 2), signature: { hash: BinData(0, B07B02E75AFF8F914102B0C1A37883E6EA7EFD96), keyId: 7151285779526844417 } }, $db: \"feat\", $readPreference: { mode: \"primary\" } }"

time="2022-11-17T19:35:44+08:00" level=warning msg="cannot create metrics for oplog: (IllegalOperation) Can't use 'local' database through mongos"
```

mongo权限如下
![image](https://user-images.githubusercontent.com/44047817/202435714-f4ab6a32-d502-4353-bdb8-430fe6ecdd17.png)

**Comment by lunuan** [comment]
mongo是分片集群,   mongos、shard、mongocfg 都配置到了 [[instances]] 中

**Comment by ysyneu** [comment]
@lunuan 
1. 为什么没有指标？
> 目前给出的大盘对分片集群适配不够，仅在副本集集群下验证过，MongoDB不同集群模式下产生指标可能不同 

2. 如何修复该问题？
> 进入图片编辑页面，比如uptime：现在的PromQL是 mongodb_instance_uptime_seconds{instance='$instance'}， 可以尝试增加集群模式对应的指标（一般为mongodb_ss_xxx），比如更改成mongodb_instance_uptime_seconds{instance='$instance'} or mongodb_ss_uptime{instance='$instance'}，两个指标同时运行
<img width="1885" alt="image" src="https://user-images.githubusercontent.com/9045284/203033123-3c6edca3-ef4a-4c68-bdf7-61966fcfbecd.png">

3. 如何提交pr？
> 欢迎修复后提交pr，导出大盘JSON文件，提交给 https://github.com/flashcatcloud/categraf/blob/main/inputs/mongodb/dashboard.json 和 https://github.com/ccfos/nightingale/blob/main/etc/dashboards/mongo_by_exporter.json

**Comment by kongfei605** [comment]
这个issue后续解决了么？ @lunuan
