### ISSUE TITLE
categraf  mtail 不显示新增标签

### ISSUE THREAD

**Issue by luoxjie** [flashcatcloud/categraf#260]
categraf（V0.2.20） mtail，是否需要在哪里配置  or bug
问题描述：
使用categraf mtail插件监控Nginx日志，自行添加了一些标签，发现web端即时查询出来的结果：
http_requests_url_total{busigroup="xxxx", ident="xxxx"}    4
刚开始以为是自己编写mtail配置有错，找了许久没发现问题，直接下载了mtail 3.0.0程序，使用同样的配置启动，curl获取到的metrics
http_requests_url_total{prog="nginx.mtail",request_uri="xxxxxx",status="200",vhost="xxxxx.com"}   4
问题：
请问大佬，是需要哪里配置还是bug？

**Comment by kongfei605** [comment]
有配置吗？

**Comment by luoxjie** [comment]
> 有配置吗？
你说的是mtail配置吗？
counter http_requests_counter
counter http_requests_total by vhost,request_method,status
counter http_requests_url_total by vhost,request_uri,status
counter http_response_milliseconds_sum by vhost,request_uri,upstream_addr,upstream_status
counter http_request_duration_milliseconds_sum by vhost,request_method,status
counter http_response_size_bytes_sum by vhost,request_method,status

# log_format  main  '$remote_addr [$time_local] 
#                   $host "$request" $status $body_bytes_sent $request_time "$http_referer" 
#                   "$http_user_agent" $upstream_response_time $upstream_addr $upstream_status'

/^/ +
/(?P<remote_addr>[0-9A-Za-z\.\-:]+) / +
/(?P<time_local>\[\d{2}\/\w{3}\/\d{4}:\d{2}:\d{2}:\d{2} \+\d{4}\]) / +
/(?P<vhost>[0-9A-Za-z\.\-:]+) / +
/"(?P<request_method>[A-Z]+) (?P<request_uri>\S+) (?P<http_version>HTTP\/[0-9\.]+)" / +
/(?P<status>\d{3}) / +
/(?P<bytes_sent>\d+) / +
/(?P<request_seconds>\d+)\.(?P<request_milliseconds>\d+) / +
/"(?P<http_referer>\S+)" / +
/"(?P<http_user_agent>\S+)" / +
/(?P<upstream_repsponse_seconds>\d+)\.(?P<upstream_response_milliseconds>\d+) / +
/(?P<upstream_addr>\S+) / +
/(?P<upstream_status>\d{3})/ +
/$/ {
  http_requests_counter++
  http_requests_total[$vhost][$request_method][$status]++
  http_requests_url_total[$vhost][$request_uri][$status]++
  http_response_milliseconds_sum[$vhost][$request_uri][$upstream_addr][$upstream_status] += $upstream_repsponse_seconds * 1000 + $upstream_response_milliseconds
  http_request_duration_milliseconds_sum[$vhost][$request_method][$status] += $request_seconds * 1000 + $request_milliseconds
  http_response_size_bytes_sum[$vhost][$request_method][$status] += $bytes_sent
}

**Comment by luoxjie** [comment]
> 有配置吗？

counter http_requests_counter
counter http_requests_total by vhost,request_method,status
counter http_requests_url_total by vhost,request_uri,status
counter http_response_milliseconds_sum by vhost,request_uri,upstream_addr,upstream_status
counter http_request_duration_milliseconds_sum by vhost,request_method,status
counter http_response_size_bytes_sum by vhost,request_method,status

/^/ +
/(?P<remote_addr>[0-9A-Za-z\.\-:]+) / +
/(?P<time_local>\[\d{2}\/\w{3}\/\d{4}:\d{2}:\d{2}:\d{2} \+\d{4}\]) / +
/(?P<vhost>[0-9A-Za-z\.\-:]+) / +
/"(?P<request_method>[A-Z]+) (?P<request_uri>\S+) (?P<http_version>HTTP\/[0-9\.]+)" / +
/(?P<status>\d{3}) / +
/(?P<bytes_sent>\d+) / +
/(?P<request_seconds>\d+)\.(?P<request_milliseconds>\d+) / +
/"(?P<http_referer>\S+)" / +
/"(?P<http_user_agent>\S+)" / +
/(?P<upstream_repsponse_seconds>\d+)\.(?P<upstream_response_milliseconds>\d+) / +
/(?P<upstream_addr>\S+) / +
/(?P<upstream_status>\d{3})/ +
/$/ {
  http_requests_counter++
  http_requests_total[$vhost][$request_method][$status]++
  http_requests_url_total[$vhost][$request_uri][$status]++
  http_response_milliseconds_sum[$vhost][$request_uri][$upstream_addr][$upstream_status] += $upstream_repsponse_seconds * 1000 + $upstream_response_milliseconds
  http_request_duration_milliseconds_sum[$vhost][$request_method][$status] += $request_seconds * 1000 + $request_milliseconds
  http_response_size_bytes_sum[$vhost][$request_method][$status] += $bytes_sent
}

**Comment by kongfei605** [comment]
config.toml 和 mtail.toml 的呢？提issue按照模板提

**Comment by luoxjie** [comment]
> config.toml 和 mtail.toml 的呢？提issue按照模板提

config.toml 都是默认配置参数
[[instances]]
 progs = "/data/nightingale/categraf/conf/input.mtail/prog2" # prog dir2
 logs = ["/data/logs/nginx/access.log"]
# override_timezone = "Asia/Shanghai"
# emit_metric_timestamp = "true" # string type

用Google的mtail启动上述mtail配置，categraf 的prometheus插件获取metrics，可以正确获得自定义标签了

**Comment by luoxjie** [comment]
> config.toml 和 mtail.toml 的呢？提issue按照模板提

config.toml 都是默认配置参数
[[instances]]
progs = "/data/nightingale/categraf/conf/input.mtail/prog2" # prog dir2
logs = ["/data/logs/nginx/access.log"]

\#override_timezone = "Asia/Shanghai"
\#emit_metric_timestamp = "true" # string type
用Google的mtail启动上述mtail配置，categraf 的prometheus插件获取metrics，可以正确获得自定义标签了

**Comment by jones-0701** [comment]
同问，遇到了相同的问题，categraf（V0.2.18），楼主解决了吗？

**Comment by luoxjie** [comment]
> 同问，遇到了相同的问题，categraf（V0.2.18），楼主解决了吗？

曲线救国，下载mtail，暴露metrics，用categraf的input.prometheus接入

**Comment by kongfei605** [comment]
> > config.toml 和 mtail.toml 的呢？提issue按照模板提
> 
> config.toml 都是默认配置参数 [[instances]] progs = "/data/nightingale/categraf/conf/input.mtail/prog2" # prog dir2 logs = ["/data/logs/nginx/access.log"]
> 
> #override_timezone = "Asia/Shanghai" #emit_metric_timestamp = "true" # string type 用Google的mtail启动上述mtail配置，categraf 的prometheus插件获取metrics，可以正确获得自定义标签了

配置没问题。设置emit_prog_label="false"（字符串） 试试
这个开关标志位默认应该设置的

**Comment by kongfei605** [comment]
v0.2.22版本发布了，emit_prog_label="true"

**Comment by luoxjie** [comment]
> v0.2.22版本发布了，emit_prog_label="true"

大佬，还是一样耶，第一条结果是categraf的mtail，第二条是mtail程序输出到categraf的prometheus的结果
![image](https://user-images.githubusercontent.com/54051831/203702181-d51c17de-b7f1-4e88-b3ce-b2044b2030f2.png)

**Comment by luoxjie** [comment]
> > > config.toml 和 mtail.toml 的呢？提issue按照模板提
> > 
> > 
> > config.toml 都是默认配置参数 [[instances]] progs = "/data/nightingale/categraf/conf/input.mtail/prog2" # prog dir2 logs = ["/data/logs/nginx/access.log"]
> > #override_timezone = "Asia/Shanghai" #emit_metric_timestamp = "true" # string type 用Google的mtail启动上述mtail配置，categraf 的prometheus插件获取metrics，可以正确获得自定义标签了
> 
> 配置没问题。0.2.22以下版本设置emit_prog_label="false"（字符串） 试试 稍等，我发个新版本0.2.22，修改下这个开关标志位默认设置
使用categraf  --test输出也确实没有自定义标签
![image](https://user-images.githubusercontent.com/54051831/203714998-ba149cfe-a64d-4063-86f8-d244301eab9f.png)

**Comment by kongfei605** [comment]
有点奇怪，反馈收到，我再看下

**Comment by kongfei605** [comment]
问题已修复，代码合并到main分支了，可以先用main分支验证了。 明天梳理下近期的功能点，再看看发布个新版本

**Comment by kongfei605** [comment]
v0.2.27版本已经发布

**Comment by luoxjie** [comment]
> 问题已修复，代码合并到main分支了，可以先用main分支验证了。 明天梳理下近期的功能点，再看看发布个新版本

感谢！终于可以干掉mtail了，下午升级看看
