### ISSUE TITLE
请问k8s 里面的container是否running没有采集吗总数？

### ISSUE THREAD

**Issue by lyitt1987** [flashcatcloud/categraf#271]
我就只看到running的总数，得不到每个container是否running的状态
我想通过是否running来告警，以便知道某个container是否重启
![image](https://user-images.githubusercontent.com/35764082/203751362-d34d1996-7d91-400c-bd18-658f6e1d2ff8.png)

谢谢解答

**Comment by kongfei605** [comment]
kube-state-metrics有这个指标，可以搜一下之前整理的kube-state-metrics指标文章

**Comment by lyitt1987** [comment]
我看了下，没有找到kube-state-metric
然后我用container启动时间来判断
比如，启动时间小于60秒：time()-container_start_time_seconds{} < 60
