### ISSUE TITLE
Categraf 机器标签可以采用外网IP吗？

### ISSUE THREAD

**Issue by jones-0701** [flashcatcloud/categraf#281]
![image](https://user-images.githubusercontent.com/97278188/205263047-b638fa21-3f28-4857-8de5-ca6c5f9de726.png)
你好，麻烦请教一下：这里获取的Ip为内网IP，可以自动获取外网ip吗？ 还是必须要手动定义呀

**Comment by UlricQin** [comment]
需要手工自行指定
