### ISSUE TITLE
Categraf 是如何通过 Promethues agent 模式自动发现 k8s 集群内的exporter 节点呢

### ISSUE THREAD

**Issue by XiaoMuYi** [flashcatcloud/categraf#282]
**What would you like to be added**:
更加详细的文档说明(由于我自身的知识不足以及对Categraf了解太少)

**Why is this needed**:
早期 k8s 监控都是基于 prometheus-operator 实现，服务监控也是通过在 Service 添加 `prometheus.io/scrape` 和 `prometheus.io/port` 注释来实现部分微服务的监控指标采集。

**Describe the solution you'd like**
无

**Additional context**
我想知道 Categraf 采集器能否实现类似的功能或者说 Categraf 是如何通过 prometheus agent 模式自动发现这些服务，我想不在大的变动下兼容原采集，该如何实现呢

**Comment by kongfei605** [comment]
config.toml中enable=true 即可开启
scrape_config_file 指定prometheus的配置文件，把你之前的scrape文件拷贝过来就可以。

一个例子
```
enable = true
scrape_config_file="/opt/categraf/scrape/in_cluster_scrape.yaml"
## log level, debug warn info error
log_level="error"
```

**Comment by XiaoMuYi** [comment]
@kongfei605 大佬，我在请教一个问题，我如果已经通过 daemonset 部署了 Categraf 节点.是不是就不能复用基于 DaemoSet 的部署方式使用 Prometheus agent 模式，这样就会重复采集 prometheus agent exporter 的数据吧.
我应该单独创建一个单副本的Deployment 资源专门用于 promehtues agent 模式？

**Comment by kongfei605** [comment]
> @kongfei605 大佬，我这里有个点没有明白。prometheus agent 已经配置将数据远程写入到 nsserver 端。然后又在 Categraf 端指定 scrape_config_file 指定prometheus的配置文件，这个作用是什么呢？

你使用prometheus agent模式采集的时候 是不是也要指定一个配置文件？这个scrape_config_file  指定的文件就是你原来使用的配置，拿过来用就可以了。

**Comment by kongfei605** [comment]
```
[prometheus] 
 enable=true  这一行是开启prometheus agent mod 
  scrape_config_file="/path/to/in_cluster_scrape.yaml" 这一行指定你原来prometheus使用的采集配置
```

**Comment by kongfei605** [comment]
搞定了没？ @XiaoMuYi 可以看看https://flashcat.cloud/blog/kubernetes-monitoring-06-apiserver/

**Comment by realzhuangxinyu** [comment]
@kongfei605 您好，我也遇到了通过k8s注解暴露metrics后采集的需求。我看你发的链接中，实现方式是使用Prometheus 作为采集器，直接remote write到夜莺数据库。中间不经过categraf吧？那么请问您发的修改prometheus.toml是指修改谁的这个文件？

**Comment by kongfei605** [comment]
这里的prometheus-agent 是集成到categraf中了，可以参考这个文档https://flashcat.cloud/docs/content/flashcat-monitor/categraf/5-prometheus/

**Comment by realzhuangxinyu** [comment]
@kongfei605 好的，谢谢。请问不需要scrape自动发现，但是需要一些relable_configs，也是如你说的开启方式，现在的prometheus input是不支持的？

**Comment by realzhuangxinyu** [comment]
@kongfei605 了解了，谢谢
