### ISSUE TITLE
n9e dashboard监控看图中，即时查询和快捷视图不一致

### ISSUE THREAD

**Issue by wangteng0906** [flashcatcloud/categraf#287]
1.即时查询到的监控指标有断点，快捷视图查询到的监控指标没有断点。从而导致配置的告警在断点处恢复告警，在实线处触发告警。
![image](https://user-images.githubusercontent.com/72957138/205878493-4f915d3c-9eb3-4a4e-aa7f-e37aa62f67fc.png)
![image](https://user-images.githubusercontent.com/72957138/205878801-19f531e9-871b-43db-ad2f-68b02c6635c8.png)
2.版本
n9e版本：
前端版本：5.13.0
后端版本：v5.13.0-445d03e0969fa519aa5ceb0ecc2b46e6231db05f
categraf版本：v0.2.14-a63d5052056603e9c6b5ca2738758e0e42470e20
3.模块使用模块exec模块

**Comment by UlricQin** [comment]
快捷视图里，可能还选中了其他的ident，以致于在根据ident聚合的时候，线连在一起了。可以看看chrome开发者工具，看看发的http request 和 http response

**Comment by kongfei605** [comment]
这个还有后续吗？ @wangteng0906

**Comment by wangteng0906** [comment]
> 这个还有后续吗？ @wangteng090
猜想是由于大量标签涌入n9e server,导致server压力大处理不过来，发往tsdb有断点。
搭建另一机房（没有导入大量标签）验证了猜想，tsdb出图正常，建议优化server处理标签逻辑

**Comment by wangteng0906** [comment]
@kongfei605

**Comment by wangteng0906** [comment]
猜想是由于大量标签涌入n9e server,导致server压力大处理不过来，发往tsdb有断点。
搭建另一机房（没有导入大量标签）验证了猜想，tsdb出图正常，建议优化server处理标签逻辑 @kongfei605

**Comment by kongfei605** [comment]
> 猜想是由于大量标签涌入n9e server,导致server压力大处理不过来，发往tsdb有断点。 搭建另一机房（没有导入大量标签）验证了猜想，tsdb出图正常，建议优化server处理标签逻辑 @kongfei605

日志中有没有报错信息？
