### ISSUE TITLE
categraf数据写到pushgateway

### ISSUE THREAD

**Issue by tangr** [flashcatcloud/categraf#292]
**What would you like to be added**:

categraf 写数据到 pushgateway里

**Why is this needed**:
加层pushgateway，使得categraf可以支持pull模型

**Describe the solution you'd like**

writers里的写到prometheus里的url，能不能支持写到pushgateway的接口

[[writers]]
#url = "http://127.0.0.1:19000/prometheus/v1/write"
url = "http://127.0.0.1:9099/metrics/job/categraf"

**Additional context**

https://github.com/ccfos/nightingale/issues/1011
这里说的categraf支持了pushgateway接口，是指哪部分，http还是writers呢

**Comment by UlricQin** [comment]
是指提供 http 接口，接收数据，categraf 本身不支持 `/metrics` 接口暴露数据，个人觉得用 remote write 挺好的，目前没有计划支持被动暴露指标的方式
