### ISSUE TITLE
disk_used_percent 磁盘使用率监控指标：一会告警一会恢复，实际应一直告警才对！

### ISSUE THREAD

**Issue by jones-0701** [flashcatcloud/categraf#294]
![23a563d41a4a208ab0df85ec9e9df18](https://user-images.githubusercontent.com/97278188/207030620-553438e7-a411-4f96-b740-1f4af9914046.jpg)
![4b0c8d1dfffee94aea8fa6e8217b517](https://user-images.githubusercontent.com/97278188/207030628-045bb333-b579-488a-999f-f0936ef5989e.jpg)
![a203896bfc230ab0739e9db9bdd7a2d](https://user-images.githubusercontent.com/97278188/207030643-56e547ff-4a9e-4fd1-b20a-7ea22be690b9.jpg)
有大佬解释一下这个磁盘告警，为什么一会恢复一会告警，实际应该要一直告警才对，pql：disk_used_percent > 60      

![84a26a0db583b7325a44d182ef1f8b7](https://user-images.githubusercontent.com/97278188/207030693-375c9bd0-2997-4281-adac-248ee7828467.png)
![5e19d86f104004443377519ab03820b](https://user-images.githubusercontent.com/97278188/207030701-73dd0c23-3d13-4541-801e-6625bbf8e06f.png)
18:52:45 直接跳到了18:54:45， 发送恢复通知时间： 2022-12-12 18:53:29
不是默认15秒采集一次吗？

**Comment by UlricQin** [comment]
https://www.gitlink.org.cn/ccfos/nightingale/wiki/faq 看一下007号FAQ。系统查不到数据就会认为恢复了。你这个数据看起来没有按照15秒的频率在上报，需要排查categraf的配置和日志

**Comment by jones-0701** [comment]
后端数据库用的mysql， 不是MariaDB， 这个会有影响吗？

**Comment by UlricQin** [comment]
使用最新版本的夜莺5.14.4，升级的时候尤其要注意5.14.2版本引入的配置：https://github.com/ccfos/nightingale/releases/tag/v5.14.2

**Comment by jones-0701** [comment]
升级完后一直报错：WARNING writer/writer.go:78 post to http://127.0.0.1:9060/api/v1/write got error: push data with remote write request got status code: 400, response body: out of bounds

**Comment by UlricQin** [comment]
out of bounds 是时序库返回的，上报的时候过于超前或滞后就会报这个错。你可以把prometheus的data目录直接删除重来，就不会有这个问题了

**Comment by jones-0701** [comment]
感谢大佬，已解决！
