### ISSUE TITLE
inputs.exec 自定以标签content=OK: ALL 35 processlist up.;CORE NULL;MSG queue length OK    像这种的要怎么把这一长字符当成整个呢？

### ISSUE THREAD

**Issue by jones-0701** [flashcatcloud/categraf#298]
![ae6b52c76ff155cd87560794f5a0690](https://user-images.githubusercontent.com/97278188/208073925-2d02e538-0b68-487c-9b08-58a48aa41cef.jpg)

**Comment by UlricQin** [comment]
做不到
