### ISSUE TITLE
target_up有两条记录?

### ISSUE THREAD

**Issue by pangpeng** [flashcatcloud/categraf#307]
采集客户端:categraf
服务端:n9e
Prometheus查询出两条target_up
一个ident为IP
一个ident为Hostname
它俩都指向一台机器(主机名:office-cloud-ops-monitor-1,IP:192.168.100.37)
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/8667405/209647759-5cfc2415-6008-490e-9ee5-b01e3751aea4.png">
夜莺后台查看也是2条
![image](https://user-images.githubusercontent.com/8667405/209647886-c701386c-d6f0-4436-81b1-7031ce9d77a2.png)
不应该只有一条ident为hostname的指标项吗

**Comment by xiaoziv** [comment]
自己修改过hostname吧
n9e会记录所有上报的host，不需要的话，在页面上删掉对象就好了

**Comment by pangpeng** [comment]
> 

没有修改过hostname,我清理数据后还是2条
 1401  2022-12-27 17:37:05 cd /opt/n9e-prometheus/
 1403  2022-12-27 17:37:12 ps aux |grep prome
 1404  2022-12-27 17:37:17 kill -15 22539
 1405  2022-12-27 17:37:22 rm -rf data/*
 1406  2022-12-27 17:37:29 nohup ./prometheus --web.listen-address=:9091 --enable-feature=remote-write-receiver &>log &
你的意思是n9e的服务端记录过ip那条数据,就是我清理了Prometheus数据还是会有?

**Comment by xiaoziv** [comment]
对象列表页面选中对象删除即可，不是清除prometheus的数据

**Comment by pangpeng** [comment]
> 

删除了,感谢
