### ISSUE TITLE
UDP监控疑问

### ISSUE THREAD

**Issue by liufangpeng** [flashcatcloud/categraf#309]
咨询一下UDP监控到了端口通过net_response_result_code这个指标返回值为3代表的什么意义呢

**Comment by xiaoziv** [comment]
https://github.com/flashcatcloud/categraf/blob/main/inputs/net_response/net_response.go#L25

**Comment by liufangpeng** [comment]
3=读取失败 这个会是因为什么情况呢

**Comment by kongfei605** [comment]
这个就是字面意思，从（TCP/UDP）连接中读取数据出错了=》读取失败。
