### ISSUE TITLE
http监控疑问

### ISSUE THREAD

**Issue by liufangpeng** [flashcatcloud/categraf#310]
http监控https的时候会验证证书吗，我一共监控了6个地址，其中2个是证书安全，其中4个是证书不安全，不安全的URL确实可以打开，有没有配置能够不进行验证证书呢

**Comment by kongfei605** [comment]
http插件配置包含了tls配置 ，所有toml的标签都可以放到配置中，你提到的 跳过证书验证， 用insecure_skip_verify = true 就好了
https://github.com/flashcatcloud/categraf/blob/main/pkg/tls/config.go#L14

**Comment by lyitt1987** [comment]
添加了insecure_skip_verify = true ，还是报 x509: certificate is valid for

**Comment by lyitt1987** [comment]
添加了insecure_skip_verify = true ，还是报 x509: certificate is valid for

**Comment by lyitt1987** [comment]
添加insecure_skip_verify = true后 还是报 tls: server selected unsupported protocol version 301
或
x509: certificate has expired or is not yet valid
因为证书是自定义的，请问如何实现 curl -I -k https://xxxx.xxx.com，如图，就算证书过期了，也能获取到200
![image](https://user-images.githubusercontent.com/35764082/224621358-b0f3afdf-41bb-4baa-8fde-66312438212a.png)

**Comment by UlricQin** [comment]
use_tls 设置为 true

**Comment by lyitt1987** [comment]
x509: certificate has expired or is not yet valid 这个错误提示通过配置use_tls = true解决了
tls: server selected unsupported protocol version 301 这个错误提示，添加了use_tls = true和insecure_skip_verify = true也不能解决，应该是执行获取返回码的时候，不支持tls1.0，不知是否可以让镜像所使用的操作系统支持tls1.0

谢谢

**Comment by kongfei605** [comment]
```
tls_min_version
tls_max_version
```
这两个选项可以配置TLS的版本。

可选项为
```
1.0
1.1
1.2
1.3
```
分别对应tls1.0 到tls1.3

**Comment by lyitt1987** [comment]
好的，谢谢！
