### ISSUE TITLE
请问 postgresql 的 大盘怎么使用？

### ISSUE THREAD

**Issue by flyingfz** [flashcatcloud/categraf#312]
在若干机器上部署了 categraf 采集器， 大部分指标是系统相关，
把  https://github.com/flashcatcloud/categraf/blob/main/inputs/system/dashboard.json 导入夜莺后， LinuxHost 大盘很顺利的就能查看。

今天在其中几个机器上启用了 input.postgresql  , 但在 夜莺里 导入 https://github.com/flashcatcloud/categraf/blob/main/inputs/postgresql/dashboard.json ， 打开大盘的页面之后提示  No such cluster: qd-dev-cluster , 尝试修改 json 内容里的 qd-dev-cluster 为 default , 也还是提示 No such cluster: default

**Comment by flyingfz** [comment]
请问我下一步该如何修改，让这个大盘可以正常显示？ 
或者能不能把这个 dashboard.json 的规则文档发一下？

**Comment by kongfei605** [comment]
datasourcename 这个应该不影响，看看你的instance和db有值吗？

**Comment by kongfei605** [comment]
json中的qd-dev-cluster 那行都去掉呢 @flyingfz 
@lsy1990 也帮忙看看，这个大盘固定了datasourcename

**Comment by flyingfz** [comment]
去掉 json 里所有   `"datasourceName": "qd-dev-cluster",` ， 提示 `bad_data: 1:10: parse error: expected type range vector in call to function "increase", got instant vector`

**Comment by kongfei605** [comment]
这个报错是大盘里面的promql写得有问题 ， 等修复后再使用大盘吧

**Comment by flyingfz** [comment]
好的。 感谢回复

**Comment by kongfei605** [comment]
https://github.com/flashcatcloud/categraf/tree/main/inputs/postgresql 已经修复了，补充了配置的注释和大盘截图 可以重新导入大盘了，没问题的话，记得来close下issue

**Comment by flyingfz** [comment]
把 dashboard.json 倒数第3行的`"datasourceValue": "qd-dev-cluster"`删除之后再导入，可以正常使用了。

**Comment by kongfei605** [comment]
> 把 dashboard.json 倒数第3行的`"datasourceValue": "qd-dev-cluster"`删除之后再导入，可以正常使用了。

带datasourceValue/datasourceName的都可以删除掉 。main分支也重新删除了这行
