### ISSUE TITLE
建议增加磁盘故障监控

### ISSUE THREAD

**Issue by xiehaitang** [flashcatcloud/categraf#315]
建议增加磁盘监控，在使用node_exporter是有磁盘故障监控的，可以参考下面链接
https://github.com/prometheus/node_exporter/blob/master/collector/filesystem_bsd.go
告警规则就是node_filesystem_readonly{fstype=~"(ext.|xfs)"} == 1

**Comment by sweetweapen** [comment]
之前老版本的n9e collector 里面有个指标disk.rw.error，感觉可以加回到categraf

**Comment by kongfei605** [comment]
后续都安排上

**Comment by kongfei605** [comment]
磁盘故障通过disk_device_error != 0 来判断, categraf版本v0.2.36 新增指标；
磁盘只读通过disk_xxx 中的label mode!="rw" 来判断，这个label一直有。

**Comment by laster-bin** [comment]
这个方式监控不准确，有时候文件系统只读了，这个值采集的/proc/1/mountinfo没有变成ro，所以不可靠
