### ISSUE TITLE
建议支持日志滚动和自动清理功能

### ISSUE THREAD

**Issue by wpliang** [flashcatcloud/categraf#322]
**What would you like to be added**:
增加日志滚动和自动清理功能

**Why is this needed**:
在生产环境避免日志无限增大，占用过多磁盘

**Describe the solution you'd `like*`
使用lumberjack进行日志分割滚动和自动清理，代码改动量小
1. config.toml里增加日志参数配置
`[log]
#日志文件名称
file_name = "log/categraf.log"
#日志文件大小，单位MB
max_size = 100
#日志文件保留时间，单位天
max_age = 3
#过期日志保留个数
max_backups = 1`
2. config.go里增加响应类
`type Log struct {
	FileName   string `toml:"file_name"`
	MaxSize    int    `toml:"max_size"`
	MaxAge     int    `toml:"max_age"`
	MaxBackups int    `toml:"max_backups"`
}
type ConfigType struct {
...
	Logs       Logs           `toml:"logs"`
...
}
`
3. 在main_posix.go里增加日志配置
`func doOSsvc() {
	log.SetOutput(&lumberjack.Logger{
		Filename:   config.Config.Log.FileName,   // 文件名称
		MaxSize:    config.Config.Log.MaxSize,    // 文件大小，单位MB
		MaxAge:     config.Config.Log.MaxAge,     // 文件有效期，单位天
		MaxBackups: config.Config.Log.MaxBackups, // 最大过期日志保留数
		LocalTime:  true,
	})
}`
4. main.go里调整下初始化配置的位置，放到doOSsvc前面
`	// init configs
	if err := config.InitConfig(*configDir, *debugMode, *testMode, *interval, *inputFilters); err != nil {
		log.Fatalln("F! failed to init config:", err)
	}

	doOSsvc()
	printEnv()`

**Additional context**

**Comment by kongfei605** [comment]
直接提个PR吧

**Comment by wpliang** [comment]
好的，晚点提交下

**Comment by kongfei605** [comment]
目前再v0.2.29版本中已经包含了，issue先close了
