### ISSUE TITLE
workfolw  release.yaml

### ISSUE THREAD

**Issue by jjeejj** [flashcatcloud/categraf#326]
这个 github action 里面的 login docker 的 step 是不是无用 可以去掉？, 这里没有docker 相关的操作

<img width="515" alt="image" src="https://user-images.githubusercontent.com/15176971/212711243-f6a333c3-478c-4235-8986-c8dbc6935d52.png">

**Comment by kongfei605** [comment]
编译后推镜像时再失败会浪费很多时间，fail-fast原则。
