### ISSUE TITLE
静态编译版本

### ISSUE THREAD

**Issue by LynkLin** [flashcatcloud/categraf#327]
**What would you like to be added**:
是否可以单独发布使用静态编译的版本
**Why is this needed**:
gcc版本太低的linux系统（如suse）无法运行
**Describe the solution you'd like**

**Additional context**

**Comment by kongfei605** [comment]
暂时会先做其他更重要的特性。目前2.14以下的现在用不了 ，低版本的系统，可以clone 代码，make build 。

**Comment by kongfei605** [comment]
v0.3.47版本开始orale现在已经不需要依赖gcc了。 只有arp插件依赖cgo。
