### ISSUE TITLE
Categraf windows疑惑

### ISSUE THREAD

**Issue by liufangpeng** [flashcatcloud/categraf#330]
windows运行日志一直在刷
rocketmq.go:51 E! fail to get topic please check config
rocketmq.go:275 E! unable to decode topic name list unexpected end of JSON input
这个是在哪个配置文件里可以关闭的呢，我在input.rocketmq_offset并没有发现配置这个的地方

**Comment by UlricQin** [comment]
没用 rocketmq 监控插件吧，直接删除 conf/input.rocketmq_offset 目录即可
