### ISSUE TITLE
mtail的README有误

### ISSUE THREAD

**Issue by wpliang** [flashcatcloud/categraf#335]
**What would you like to be added**:

`## 启动
编辑mtail.toml文件, 注意每个instance 需要指定不同的progs参数（不同的progs文件或者目录）`

这里可以指定相同的progs吧，比如一台机器上安装了三个应用，progs指定一个错误日志规则，三个应用就可以复用这个progs文件，logs指定不通的日志文件，再把[instances.labels]打开来表示不同的应用，如下
`[[instances]]
progs = "conf/progs/error_log"
logs = ["log/a.log"]
override_timezone = "Asia/Shanghai"
emit_metric_timestamp = "true" #string type
[instances.labels]
app = "a"`
![image](https://user-images.githubusercontent.com/18420903/216968588-e342a65b-86e9-46f0-814f-94f7b85846db.png)

**Why is this needed**:

**Describe the solution you'd like**

**Additional context**

**Comment by kongfei605** [comment]
直接提个PR吧

**Comment by kongfei605** [comment]
已更正，见https://github.com/flashcatcloud/categraf/pull/337， 感谢反馈 @wpliang

**Comment by wpliang** [comment]
> 已更正，见[https://github.com/flashcatcloud/categraf/pull/337，](https://github.com/flashcatcloud/categraf/pull/337%EF%BC%8C) 感谢反馈 @wpliang

效率啊，👍
