### ISSUE TITLE
插件配置的文件是否可以热加载

### ISSUE THREAD

**Issue by pangpeng** [flashcatcloud/categraf#339]
场景:
一台监控主机监控多个mysql实例,
目前通过定时python脚本请求DB管理系统生成input.mysql/mysql.toml配置文件
其中Instances条目会动态增减,如果不systemctl restart categraf程序,程序仍在采集减掉的实例数据

**Comment by kongfei605** [comment]
kill -HUP ${PID}

**Comment by pangpeng** [comment]
> kill -HUP ${PID}

谢谢 这种方式验证可用。

是否支持在每个input插件轮训周期从新读取下插件配置文件

**Comment by kongfei605** [comment]
> > kill -HUP ${PID}
> 
> 谢谢 这种方式验证可用。
> 
> 是否支持在每个input插件轮训周期从新读取下插件配置文件

本地配置不支持。
你的场景下可以service文件中加上一行
```
ExecReload=/bin/kill -s HUP $MAINPID
```
每次修改插件配置后执行， `systemctl reload categraf` 就以了

**Comment by pangpeng** [comment]
> 



> > > kill -HUP ${PID}
> > 
> > 
> > 谢谢 这种方式验证可用。
> > 是否支持在每个input插件轮训周期从新读取下插件配置文件
> 
> 本地配置不支持。 你的场景下可以service文件中加上一行
> 
> ```
> ExecReload=/bin/kill -s HUP $MAINPID
> ```
> 
> 每次修改插件配置后执行， `systemctl reload categraf` 就以了
