### ISSUE TITLE
arp_packet插件报local.arp_packet not supported错误

### ISSUE THREAD

**Issue by nondevops** [flashcatcloud/categraf#364]
### Relevant config.toml

```toml
[root@aliyun input.arp_packet]# cat arp_packet.toml
# # collect interval
interval = 15

[[instances]]
eth_device="eth0"
```

### Logs from categraf

```text
[root@aliyun categraf]# ./categraf --test --inputs arp_packet --debug
2023/02/21 20:11:46 main.go:104: I! runner.binarydir: /opt/gocode/src/categraf
2023/02/21 20:11:46 main.go:105: I! runner.hostname: aliyun.tjf.n9e.001
2023/02/21 20:11:46 main.go:106: I! runner.fd_limits: (soft=65535, hard=65535)
2023/02/21 20:11:46 main.go:107: I! runner.vm_limits: (soft=unlimited, hard=unlimited)
2023/02/21 20:11:46 config.go:36: I! tracing disabled
2023/02/21 20:11:46 provider.go:69: I! use input provider: [local]
2023/02/21 20:11:46 traces_agent.go:19: I! traces agent disabled!
2023/02/21 20:11:46 prometheus_agent.go:19: I! prometheus scraping disabled!
2023/02/21 20:11:46 ibex_agent.go:19: I! ibex agent disabled!
2023/02/21 20:11:46 agent.go:39: I! agent starting
2023/02/21 20:11:46 metrics_agent.go:150: E! input: local.arp_packet not supported
2023/02/21 20:11:46 agent.go:47: I! [*agent.MetricsAgent] started
2023/02/21 20:11:46 agent.go:50: I! agent started
```

### System info

CentOS Linux release 7.8.2003 (Core)

### Steps to reproduce

1.修改配置
2.重启categraf服务
3.--test探测是否能获取数据
4.发现有一个错误

### Expected behavior

2023/02/21 20:11:46 metrics_agent.go:150: E! input: local.arp_packet not supported
不清楚这个错误是系统不支持导致的还是配置语法有问题导致的。

### Actual behavior

2023/02/21 20:11:46 metrics_agent.go:150: E! input: local.arp_packet not supported
不清楚这个错误是系统不支持导致的还是配置语法有问题导致的。

### Additional info

![image](https://user-images.githubusercontent.com/12181410/220341451-5e8bb963-691c-4f45-bcaf-afbdd2ad3730.png)

**Comment by kongfei605** [comment]
这个是编译的版本没有带arp_packet 插件，下个版本我再加一下。

如果自己编译的话，需要需要安装lib-pcap，编译时要带上tags：` go build --tags "arppacket" `

**Comment by kongfei605** [comment]
v0.2.30已经发布了，categraf-v0.2.30-linux-amd64-with-oracle-plugin.tar.gz 支持arp和oracle这类依赖cgo的插件。
