### ISSUE TITLE
windows获取swap

### ISSUE THREAD

**Issue by fzzpeng** [flashcatcloud/categraf#381]
windows 不支持获取swap吗

**Comment by kongfei605** [comment]
是指windows virtual memory 吗？ 如果是virtual memory不支持。 
https://www.windowscentral.com/how-change-virtual-memory-size-windows-10看这里介绍，virtual memory 就是在某个分区上单独创建一个特殊文件用户内存页换出。 欢迎讨论~

**Comment by kongfei605** [comment]
这个issue是否已经解决？
