### ISSUE TITLE
【插件新增建议】新增clickhouse监控

### ISSUE THREAD

**Issue by nondevops** [flashcatcloud/categraf#383]
【插件新增建议】新增clickhouse监控

# 诉求背景
1、clickhouse作为大数据、日志存储最为关键的组件，需要纳入监控一体化建设体系中。
2、目前现存的插件库对大数据组件的支撑较少。

# 实现难度
telegraf已实现clickhouse监控，对于熟悉go语言及插件库和监控运转逻辑的同学应该很快就能实现。（主要是我不会go，尴尬中）

**Comment by kongfei605** [comment]
看到了 https://github.com/influxdata/telegraf/tree/master/plugins/inputs/clickhouse ，安排

**Comment by kongfei605** [comment]
社区有热心的小伙伴提PR了，categraf v0.3.3及以上版本可用
