### ISSUE TITLE
【插件新增建议】新增consul监控

### ISSUE THREAD

**Issue by nondevops** [flashcatcloud/categraf#384]
【插件新增建议】新增consul监控

# 诉求背景
1、consul作为配置注册及服务发现常用软件，多用于高可用及K8S系列场景。

# 实现难度
telegraf已实现consul监控（https://github.com/influxdata/telegraf/tree/master/plugins/inputs/consul），在开发过程中可参考。

**Comment by kongfei605** [comment]
v0.3.13版本categraf已经添加consul插件
