### ISSUE TITLE
【插件新增建议】新增openldap监控

### ISSUE THREAD

**Issue by nondevops** [flashcatcloud/categraf#385]
【插件新增建议】新增openldap监控

# 诉求背景
1、openldap作为统一身份认证的必要条件，监控组织变化及服务主从状态。

# 实现难度
telegraf已实现openldap监控（https://github.com/influxdata/telegraf/tree/master/plugins/inputs/openldap），在开发过程中可参考。

**Comment by kongfei605** [comment]
https://github.com/flashcatcloud/categraf/pull/772 已添加， v0.3.48 版本已支持
