### ISSUE TITLE
latest 镜像 nil 异常

### ISSUE THREAD

**Issue by Mystery00** [flashcatcloud/categraf#407]
https://github.com/flashcatcloud/categraf/blob/e59d509fb25b74721f9f643360099712378a012d/heartbeat/heartbeat.go#L37

如果此处 conf = nil？

**Comment by Mystery00** [comment]
https://github.com/flashcatcloud/categraf/blob/e59d509fb25b74721f9f643360099712378a012d/heartbeat/heartbeat.go#L22-L37

kongfei 在 2023/03/13 13:56 修复了 conf.Enable 判断中的nil，但是用户从旧版本升级到当前版本的时候，配置文件中不会有 heartbeat 相关的配置，此时就会

`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x36e490b]

goroutine 99 [running]:
flashcat.cloud/categraf/heartbeat.Work()
        /home/runner/work/categraf/categraf/heartbeat/heartbeat.go:37 +0xcb
created by main.main
        /home/runner/work/categraf/categraf/main.go:85 +0x185`

**Comment by Mystery00** [comment]
修复代码 https://github.com/flashcatcloud/categraf/pull/408

**Comment by kongfei605** [comment]
清理镜像，重新pull
