### ISSUE TITLE
k8s集群采集不到二进制安装的组件数据

### ISSUE THREAD

**Issue by maco6096** [flashcatcloud/categraf#424]
### Relevant config.toml

```toml
kind: ConfigMap
metadata:
  name: categraf-config-deployment
  namespace: kube-monitor
apiVersion: v1
data:
  config.toml: |
    [global]
    # whether print configs
    print_configs = true

    # add label(agent_hostname) to series
    # "" -> auto detect hostname
    # "xx" -> use specified string xx
    # "$hostname" -> auto detect hostname
    # "$ip" -> auto detect ip
    # "$hostname-$ip" -> auto detect hostname and ip to replace the vars
    hostname = "$HOSTNAME"

    # will not add label(agent_hostname) if true
    omit_hostname = false

    # s | ms
    precision = "ms"

    # global collect interval
    interval = 15

    [global.labels]
    # region = "shanghai"
    env = "k8s"

    [writer_opt]
    # default: 2000
    batch = 2000
    # channel(as queue) size
    chan_size = 10000

    [[writers]]
    url = "http://ip:19000/prometheus/v1/write"

    # Basic auth username
    basic_auth_user = ""

    # Basic auth password
    basic_auth_pass = ""

    # timeout settings, unit: ms
    timeout = 5000
    dial_timeout = 2500
    max_idle_conns_per_host = 100
  prometheus.toml: |
    [prometheus]
    enable = true
    scrape_config_file="/opt/categraf/scrape/in_cluster_scrape.yaml"
    ## log level, debug warn info error
    log_level="info"
    ## wal reserve time duration, default value is 2 hour
    # wal_min_duration=2
    ## wal storage path, default value is ./data-agent
    wal_storage_path="/opt/categraf/prometheus-wal"
```

### Logs from categraf

```text
2023/03/24 11:26:28 main.go:128: I! runner.binarydir: /usr/bin
2023/03/24 11:26:28 main.go:129: I! runner.hostname: nightingale-categraf-9d996985d-gbg86
2023/03/24 11:26:28 main.go:130: I! runner.fd_limits: (soft=1048576, hard=1048576)
2023/03/24 11:26:28 main.go:131: I! runner.vm_limits: (soft=unlimited, hard=unlimited)
2023/03/24 11:26:28 agent.go:39: I! agent starting
2023/03/24 11:26:28 provider.go:69: I! use input provider: []
2023/03/24 11:26:28 traces_agent.go:19: I! traces agent disabled!
2023/03/24 11:26:28 ibex_agent.go:19: I! ibex agent disabled!
2023/03/24 11:26:28 metrics_agent.go:117: I! no inputs
2023/03/24 11:26:28 agent.go:47: I! [*agent.MetricsAgent] started
2023/03/24 11:26:28 prometheus_agent.go:27: I! prometheus scraping started!
2023/03/24 11:26:28 agent.go:47: I! [*agent.PrometheusAgent] started
2023/03/24 11:26:28 agent.go:50: I! agent started
ts=2023-03-24T03:26:28.938Z caller=web.go:553 level=info component=web msg="Start listening for connections" address=127.0.0.1:0
ts=2023-03-24T03:26:28.943Z caller=prometheus.go:803 level=info msg="Starting WAL storage ..."
ts=2023-03-24T03:26:28.947Z caller=tls_config.go:195 level=info component=web msg="TLS is disabled." http2=false
ts=2023-03-24T03:26:28.958Z caller=db.go:332 level=info msg="replaying WAL, this may take a while" dir=/opt/categraf/prometheus-wal/wal
ts=2023-03-24T03:26:28.959Z caller=db.go:383 level=info msg="WAL segment loaded" segment=0 maxSegment=0
ts=2023-03-24T03:26:28.960Z caller=prometheus.go:824 level=info fs_type=XFS_SUPER_MAGIC
ts=2023-03-24T03:26:28.960Z caller=prometheus.go:827 level=info msg="Agent WAL storage started"
ts=2023-03-24T03:26:28.960Z caller=prometheus.go:828 level=debug msg="Agent WAL storage options" WALSegmentSize=0B WALCompression=false StripeSize=0 TruncateFrequency=0s MinWALTime=0s MaxWALTime=0s
ts=2023-03-24T03:26:28.960Z caller=prometheus.go:258 level=info msg="Loading configuration file" filename=/opt/categraf/scrape/in_cluster_scrape.yaml
ts=2023-03-24T03:26:28.990Z caller=dedupe.go:112 component=remote level=info remote_name=5bf4c4 url=http://10.1.82.77:19000/prometheus/v1/write msg="Starting WAL watcher" queue=5bf4c4
ts=2023-03-24T03:26:28.990Z caller=dedupe.go:112 component=remote level=info remote_name=5bf4c4 url=http://10.1.82.77:19000/prometheus/v1/write msg="Starting scraped metadata watcher"
ts=2023-03-24T03:26:28.991Z caller=dedupe.go:112 component=remote level=info remote_name=5bf4c4 url=http://10.1.82.77:19000/prometheus/v1/write msg="Replaying WAL" queue=5bf4c4
ts=2023-03-24T03:26:28.991Z caller=dedupe.go:112 component=remote level=debug remote_name=5bf4c4 url=http://10.1.82.77:19000/prometheus/v1/write msg="Tailing WAL" lastCheckpoint= checkpointIndex=0 currentSegment=0 lastSegment=0
ts=2023-03-24T03:26:28.991Z caller=dedupe.go:112 component=remote level=debug remote_name=5bf4c4 url=http://10.1.82.77:19000/prometheus/v1/write msg="Processing segment" currentSegment=0
ts=2023-03-24T03:26:29.022Z caller=manager.go:289 level=debug component="discovery manager scrape" msg="Starting provider" provider=file/0 subs=map[apiserver:{}]
ts=2023-03-24T03:26:29.023Z caller=manager.go:289 level=debug component="discovery manager scrape" msg="Starting provider" provider=file/1 subs=map[controller-manager:{}]
ts=2023-03-24T03:26:29.023Z caller=manager.go:289 level=debug component="discovery manager scrape" msg="Starting provider" provider=file/2 subs=map[scheduler:{}]
ts=2023-03-24T03:26:29.023Z caller=manager.go:289 level=debug component="discovery manager scrape" msg="Starting provider" provider=file/3 subs=map[etcd:{}]
ts=2023-03-24T03:26:29.023Z caller=prometheus.go:285 level=info msg="Completed loading of configuration file" filename=/opt/categraf/scrape/in_cluster_scrape.yaml totalDuration=62.997732ms remote_storage=3.22791ms web_handler=1.585µs scrape=32.028524ms scrape_sd=640.212µs notify=3.437µs notify_sd=8.296µs
ts=2023-03-24T03:26:29.023Z caller=prometheus.go:788 level=info msg="Server is ready to receive web requests."
```

### System info

categraf-0.2.31

### Steps to reproduce

1.二进制安装k8s组件，coreDNS是通过kubeAdm安装
2.部署categraf/k8s/deployment.yaml
3.
...

### Expected behavior

夜莺查询到所有数据

### Actual behavior

只采集到了coreDNS的

### Additional info

kind: ConfigMap
metadata:
  name: scrape-config
  namespace: kube-monitor
apiVersion: v1
data:
  in_cluster_scrape.yaml: |
    global:
      scrape_interval: 15s
      #external_labels:
      #  cluster: test
      #  replica: 0
    scrape_configs:
      - job_name: "apiserver"
        metrics_path: "/metrics"
        file_sd_configs:
          - files: ["/home/work/prometheus/file_sd_config/*.json"]
        scheme: https
        tls_config:
          insecure_skip_verify: true
        authorization:
          credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - source_labels:
              [
                __meta_kubernetes_namespace,
                __meta_kubernetes_service_name,
                __meta_kubernetes_endpoint_port_name,
              ]
            action: keep
            regex: default;kubernetes;https

      - job_name: "controller-manager"
        metrics_path: "/metrics"
        file_sd_configs:
          - files: ["/home/work/prometheus/file_sd_config/*.json"]
        scheme: https
        tls_config:
          insecure_skip_verify: true
        authorization:
          credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - source_labels:
              [
                __meta_kubernetes_namespace,
                __meta_kubernetes_service_name,
                __meta_kubernetes_endpoint_port_name,
              ]
            action: keep
            regex: kube-system;kube-controller-manager;https

      - job_name: "scheduler"
        metrics_path: "/metrics"
        file_sd_configs:
          - files: ["/home/work/prometheus/file_sd_config/*.json"]
        scheme: https
        tls_config:
          insecure_skip_verify: true
        authorization:
          credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - source_labels:
              [
                __meta_kubernetes_namespace,
                __meta_kubernetes_service_name,
                __meta_kubernetes_endpoint_port_name,
              ]
            action: keep
            regex: kube-system;kube-scheduler;https

      - job_name: "etcd"
        metrics_path: "/metrics"
        file_sd_configs:
          - files: ["/home/work/prometheus/file_sd_config/*.json"]
        scheme: https
        tls_config:
          ca_file: /opt/categraf/pki/etcd/ca.crt
          cert_file: /opt/categraf/pki/etcd/client.crt
          key_file: /opt/categraf/pki/etcd/client.key
          insecure_skip_verify: true
        relabel_configs:
          - source_labels:
              [
                __meta_kubernetes_namespace,
                __meta_kubernetes_service_name,
                __meta_kubernetes_endpoint_port_name,
              ]
            action: keep
            regex: kube-system;etcd;https

      - job_name: "coredns"
        metrics_path: "/metrics"
        kubernetes_sd_configs:
          - role: endpoints
        scheme: http
        relabel_configs:
          - source_labels:
              [
              __meta_kubernetes_namespace,
              __meta_kubernetes_service_name,
              __meta_kubernetes_endpoint_port_name,
              ]
            action: keep
            regex: kube-system;kube-dns;metrics

    remote_write:
      - url: 'http://ip:19000/prometheus/v1/write'
---

**Comment by kongfei605** [comment]
之前你用prometheus怎么采集的？ 直接把配置拿过来 放到scrape-config中

**Comment by maco6096** [comment]
没有直接用prometheus采集过
scrape-config现在改成就静态采集一个apiserver，也采集不到，但是改成kube-sd-config方式采集coredns就可以，感觉静态的就没有自动抓取，debug日志一直都没有进一步的输出。

in_cluster_scrape.yaml: |
    global:
      scrape_interval: 15s
      #external_labels:
      #  cluster: test
      #  replica: 0
    scrape_configs:
      - job_name: "apiserver"
        metrics_path: "/metrics"
        static_configs:
          - targets: ["10.1.80.15:6443"]
        #file_sd_configs:
        #  - files: ["/home/work/prometheus/file_sd_config/apiserver.json"]
        scheme: https
        tls_config:
          insecure_skip_verify: true
        authorization:
          credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - source_labels:
              [
                __meta_kubernetes_namespace,
                __meta_kubernetes_service_name,
                __meta_kubernetes_endpoint_port_name,
              ]
            action: keep
            regex: default;kubernetes;https

    remote_write:
      - url: 'http://10.1.88.79:19000/prometheus/v1/write'

**Comment by kongfei605** [comment]
你这个配置格式我也没办法帮你检查，多检查下配置吧

**Comment by kongfei605** [comment]
黄埔营一期有专门讲 如何采集二进制部署的组件数据。可以了解下。
