### ISSUE TITLE
图表没有数据

### ISSUE THREAD

**Issue by anxiaokei** [flashcatcloud/categraf#43]
您好，我按照相关的配置，但图表却没有相关数据：
![image](https://user-images.githubusercontent.com/107683514/174282806-376c715d-de7a-4bfd-b1b2-9eb7ba8efa6c.png)
./categraf --test --inputs mysql：
![image](https://user-images.githubusercontent.com/107683514/174283092-876e2b02-1ac4-4797-9b60-2cfd06678444.png)
![image](https://user-images.githubusercontent.com/107683514/174283165-bfc17257-a6c0-43d4-8449-0656e680e06e.png)
![image](https://user-images.githubusercontent.com/107683514/174283336-1ce16f9a-0d1b-4765-acbf-70c1469a5486.png)

**Comment by UlricQin** [comment]
mysql.toml中需要为mysql实例配上一个instance的标签
