### ISSUE TITLE
怎样增加新的input

### ISSUE THREAD

**Issue by cleverchou** [flashcatcloud/categraf#430]
按Readme，在Input文件下拷贝tpl文件重新命名为test，test这个插件并没有并执行，是否有新增Input的详细步骤?

**Comment by kongfei605** [comment]
readme的链接是哪个？插件只能是从已有的插件中新增配置 启动对应的插件。并不能通过配置增加不存在的插件。

**Comment by cleverchou** [comment]
readme的链接：https://github.com/flashcatcloud/categraf/tree/main/inputs/readme.md

**Comment by UlricQin** [comment]
这个没有文档，可以参考tomcat的插件和mem插件，代码很少，如果想自己写插件需要能读懂这俩插件的代码，看懂这俩插件的代码基本就知道怎么搞了。其他一些朋友贡献插件也都是这么入门的

**Comment by UlricQin** [comment]
哦对了，这个也可以看看 https://mp.weixin.qq.com/s/eeoRTeQrQwZ6iRvIqVozSA

**Comment by kongfei605** [comment]
如果是实现新插件，按照秦老师给的视频链接来就好了。 先关闭这个issue了，有问题可以随时打开。
