### ISSUE TITLE
如何只编译想要的插件？

### ISSUE THREAD

**Issue by SpaHuang** [flashcatcloud/categraf#444]
大神们，全量插件编译后的执行文件有100多M，放在嵌入工上不合适，而且很多插件在嵌入式设备上用不到，如何只编译自己想要地插件？

**Comment by UlricQin** [comment]
make build-pure 可以减少一些插件，但是无法指定哪些编译哪些不编译

**Comment by ChetWang** [comment]
一个agent，压缩后还有上百MB，也是没谁了。。。

**Comment by UlricQin** [comment]
```
ulric@bogon categraf % du -sh categraf
126M	categraf
ulric@bogon categraf % make build-pure
Building version v0.2.39-7c8e01af226182d080c3c857af3d24166541490a
ulric@bogon categraf % du -sh categraf
 55M	categraf
```

**Comment by kongfei605** [comment]
> 一个agent，压缩后还有上百MB，也是没谁了。。。

纯好奇，上百兆是咋压缩的？release页面压缩包三十几M。

**Comment by ChetWang** [comment]
> > 一个agent，压缩后还有上百MB，也是没谁了。。。
> 
> 纯好奇，上百兆是咋压缩的？release页面压缩包三十几M。

说错了，解压后是上百MB，建议用upx加壳压缩下

**Comment by kongfei605** [comment]
> > > 一个agent，压缩后还有上百MB，也是没谁了。。。
> > 
> > 
> > 纯好奇，上百兆是咋压缩的？release页面压缩包三十几M。
> 
> 说错了，解压后是上百MB，建议用upx加壳压缩下

后续可以拆分metrics 、log、trace 和全版本， 需要用哪个就下载哪个
