### ISSUE TITLE
input.prometheus插件采集nginx_vts指标中特殊字符会影响夜莺预置筛选功能

### ISSUE THREAD

**Issue by nibo-dev** [flashcatcloud/categraf#445]
### Relevant config.toml

```toml
[[instances]]
urls = [
     "http://172.24.86.99:1184/status",
     "http://172.24.86.99:9913/metrics",
     "http://172.24.86.98:1184/status",
     "http://172.24.86.98:9913/metrics"
]
url_label_key = "pro_collector"
url_label_value = "ngx_test"
```

### Logs from categraf

```text
无报错日志
```

### System info

categrafv0.2.28

### Steps to reproduce

![image](https://user-images.githubusercontent.com/64080566/230551623-2e413dca-af5e-4e62-8026-226d7c228f5a.png)
![image](https://user-images.githubusercontent.com/64080566/230552111-7a20925e-b69b-45d8-b949-605711db8dc3.png)

### Expected behavior

在使用v5.15版本时发现由于特殊符号\*导致预置筛选功能无法使用.

### Actual behavior

经过排查发现是由于使用input.prometheus插件采集nginx_vts的metrics的host导致该问题，我关闭nginx_vts的指标采集，手动清理掉特殊字符后，解决该问题，我不确定是由于我的配置导致还是categraf指标识别导致。

**Comment by kongfei605** [comment]
vts 本身就带了这个指标 ，可以
`curl http://172.24.86.98:9913/metrics'看看返回

**Comment by nibo-dev** [comment]
> vts 本身就带了这个指标 ，可以 `curl [http://172.24.86.98:9913/metrics'看看返回](http://172.24.86.98:9913/metrics'%E7%9C%8B%E7%9C%8B%E8%BF%94%E5%9B%9E)
![image](https://user-images.githubusercontent.com/64080566/230558878-722f8ef2-909e-4fb1-97fa-447a0a5f5860.png)

您好，我的意思是vts自带的特殊符号指标会影响到夜莺v5.15的对象列表中的未分组对象和全部对象查询,我理解为在使用对象列表是调用nwebapi中的语句，但是改语句不识别特殊字符，所以导致对象列表不可用。
![image](https://user-images.githubusercontent.com/64080566/230559734-80abcce4-ea31-4bb3-bc5d-6760cec20300.png)

我理解vts的特殊字符不应该影响夜莺ident的使用，因为我在n9e_v5.target的表中看到了vts的特殊字符在ident字段。
![image](https://user-images.githubusercontent.com/64080566/230560134-30285287-9296-4e3d-9023-97928a83af79.png)

我不确定我这样解释这个问题是否正确。

**Comment by kongfei605** [comment]
建议先升级到v6 ，v6中已经可以处理这个问题哈。
