### ISSUE TITLE
V6版本为什么监控项target_up拿不到值

### ISSUE THREAD

**Issue by liufangpeng** [flashcatcloud/categraf#485]
![image](https://user-images.githubusercontent.com/73222197/234246511-5012da2e-3292-467a-b5f5-44c72fd11439.png)

![image](https://user-images.githubusercontent.com/73222197/234436608-2db75435-48d2-47fc-9006-46df81a643fc.png)

**Comment by kongfei605** [comment]
采集器是哪个？版本呢？请按照模板提供信息。

**Comment by kongfei605** [comment]
https://flashcat.cloud/blog/nightingale-v6-host-nodata/
