### ISSUE TITLE
windows-categraf，采集每台机子的IP如何更改为采集序列号

### ISSUE THREAD

**Issue by liufangpeng** [flashcatcloud/categraf#499]
由于IP有时候会变更，导致监控的机器信息也会down掉，拉起新的，所以想将采集每台主机的IP更改为采集序列号，序列号采集命令为powershell 的 (Get-WmiObject win32_bios).SerialNumber

**Comment by kongfei605** [comment]
hostname也会变吗？
可以在config.toml中hostname配置一个固定字符串，或者用$hostname（如果hostname不变）

**Comment by wudihechao** [comment]
确实有需求，因为ip重新分配很常见，而主机名也不算靠谱，例如有时物理机会回收用于其他系统，此时主机名会重新命名，就会变为新对象。
还有一个类似需求：目前没有采集bios序列号，没法实现物理机 与 远程管理卡、磁盘等通过snmp协议采集到的对象关联在一起。

**Comment by wudihechao** [comment]
> hostname也会变吗？ 可以在config.toml中hostname配置一个固定字符串，或者用$hostname（如果hostname不变）

确实有需求，因为ip重新分配很常见，而主机名也不算靠谱，例如有时物理机会回收用于其他系统，此时主机名会重新命名，就会变为新对象。
还有一个类似需求：目前没有采集bios序列号，没法实现物理机 与 远程管理卡、磁盘等通过snmp协议采集到的对象关联在一起。
