### ISSUE TITLE
请问一下是否移除了win大盘

### ISSUE THREAD

**Issue by shuncon** [flashcatcloud/categraf#515]
请问一下是否移除了win大盘，我并没找到相关大盘json，而且内置的仪表盘是Windows - exporter

而我采集器是categraf，是不通用的

**Comment by shuncon** [comment]
![image](https://github.com/flashcatcloud/categraf/assets/25509201/b361df53-bfb4-47c7-863e-80f0e9800347)

**Comment by kongfei605** [comment]
大盘有社区贡献的，也有内部开发的，有些大盘可能是没有的。后续大盘都会集中到n9e的integrations目录中。

**Comment by shuncon** [comment]
> 大盘有社区贡献的，也有内部开发的，有些大盘可能是没有的。后续大盘都会集中到n9e的integrations目录中。

能发一下地址嘛 emm

**Comment by kongfei605** [comment]
> > 大盘有社区贡献的，也有内部开发的，有些大盘可能是没有的。后续大盘都会集中到n9e的integrations目录中。
> 
> 能发一下地址嘛 emm

夜莺的仓库里有个目录叫integrations

**Comment by UlricQin** [comment]
可以复用linux的大盘，除了个别指标没有，其他指标基本类似

**Comment by shuncon** [comment]
好的 我试试
