### ISSUE TITLE
使用0.2.10版本采集windows报错

### ISSUE THREAD

**Issue by Asina-opt** [flashcatcloud/categraf#516]
报错内容：
E! failed to get disk usage: The volume does not contain a recognized file system.Please make sure that all required file system drivers are loaded and that the volume is not corrupted.

windows的磁盘信息：
![1685352879745](https://github.com/flashcatcloud/categraf/assets/118288956/6ddbf1c7-8f1e-4d1e-b6b0-14a1bc92c76a)

请问怎么解决？

**Comment by kongfei605** [comment]
./categraf --version

**Comment by Asina-opt** [comment]
![image](https://github.com/flashcatcloud/categraf/assets/118288956/4896f224-4868-4228-aa7b-1727b9098d73)
![image](https://github.com/flashcatcloud/categraf/assets/118288956/9d715c9c-4f77-4e8b-b714-5b4fc9199001)
![image](https://github.com/flashcatcloud/categraf/assets/118288956/28a63b12-80d7-4967-9c9a-a6f78528712a)
![image](https://github.com/flashcatcloud/categraf/assets/118288956/266b12bc-3cfd-4dcf-ab8a-f6686d13110a)

**Comment by kongfei605** [comment]
看修改的配置都不会引起这个报错哈。 下载最新版本的categraf v0.2.35 试试。磁盘采集是调用的第三方库，中间有过升级。

**Comment by Asina-opt** [comment]
升级了版本没用，采集的windows虚拟机没啥问题，物理机就报上面那个错了

**Comment by kongfei605** [comment]
虚机是什么文件系统？物理机是什么文件系统

**Comment by Asina-opt** [comment]
是我们的物理机文件系统有问题么？
![image](https://github.com/flashcatcloud/categraf/assets/118288956/46a78193-c5f9-49c9-9627-e91368bd6145)

**Comment by Asina-opt** [comment]
采集磁盘信息需要windows有驱动吗？

**Comment by Asina-opt** [comment]
怎么关闭对磁盘的采集呢？

**Comment by kongfei605** [comment]
> 怎么关闭对磁盘的采集呢？

关闭某个插件，只需要删除conf/input.xxx 目录就好
