### ISSUE TITLE
categraf-v0.3.0采集出现错误

### ISSUE THREAD

**Issue by liufangpeng** [flashcatcloud/categraf#519]
监控的所有机器nvidia的监控项能监控到算力利用率，但是显存利用率、显存total全体机器都查不到数据
已下为categraf debug模式报错
![image](https://github.com/flashcatcloud/categraf/assets/73222197/84dbb34e-f013-4bad-a3b0-f38ac592da58)

**Comment by kongfei605** [comment]
有返回为NA的值 ，这个是符合预期的。 nvidia-smi --format=csv  看看输出（根据你的配置 选择是否添加 --query-gpu 参数）

**Comment by liufangpeng** [comment]
今天查看所有监控项都恢复了，没有人做任何变更在昨天18:30左右所有同时恢复。
![image](https://github.com/flashcatcloud/categraf/assets/73222197/f8fd658b-3344-4291-933b-4ca910a876f6)

执行nvidia-smi --format=csv之后提示命令不对
![image](https://github.com/flashcatcloud/categraf/assets/73222197/5d5de25e-1270-4e0c-a5c9-bd79694b3242)

**Comment by kongfei605** [comment]
为什么恢复 你要自己排查下了，是不是再18：30 ,nvidia-smi 有输出了。

**Comment by liufangpeng** [comment]
如果在那个时间恢复的话不会这么巧所有机器都会同时有输出吧，显卡没有统一管控

**Comment by kongfei605** [comment]
> 显卡没有统一管控

之前空跑，然后批量计算任务？ categraf的插件就是调用了nvidia-smi命令，然后从命令提取 数值 ，上报成指标。没有符合条件的数值，categraf也很无奈呀，要是debug模式显示的数值都正常，但是上报有问题，那可以怀疑categraf了。

**Comment by liufangpeng** [comment]
但是nvidia-smi命令在事故期间一直也都是有输出的，数值也都有，就是一直上报不上去没有向时序数据库输送数据

**Comment by kongfei605** [comment]
看第一张截图，都是NA ，转换不了 ，所以不上报。如果有能转换得了的，--debug 会把指标和值都输出。目前你给的信息支持不了你的结论，这个agent是开源的，每次release都有changelog，实在不放心，你可以再对比下。

**Comment by liufangpeng** [comment]
那现在总结下来，判断是nvidia-smi命令出了问题导致那段时间agent拿不到GPU的一些值？

**Comment by kongfei605** [comment]
对，看你截图. 
```
--debug 会吧采集到的指标打印出来，并上报给server
--test 模式，会把采集的指标打印出来，不上报
```
后续遇到类似问题，可以多找几台机器验证，然后按照模板提交issue，开启即时查询的自动补全，输入nvdia 截图
