### ISSUE TITLE
能否增加监控docker退出容器的指标

### ISSUE THREAD

**Issue by Somalia0932** [flashcatcloud/categraf#522]
**What would you like to be added**: 增加监控docker退出容器的指标 Exited (143) 3 weeks ago

**Why is this needed**:   纯docker环境，监控容器的运行状态，便于制作大屏 及告警。

**Describe the solution you'd like**

**Additional context**

**Comment by kongfei605** [comment]
docker run --restart =always ,好奇问下，一台机器上有多少容器？

**Comment by Somalia0932** [comment]
> docker run --restart =always ,好奇问下，一台机器上有多少容器？

restart当然是做啦，有些情形就会导致起不来 或者被关闭了，导致状态Exited ，一台机器几十个容器吧。

**Comment by kongfei605** [comment]
categraf支持cadvisor，可以每个物理机上装个cadvisor，也能发现类似的问题 。短期内可能也不会做特别针对容器这类问题的支持，exit 、oom类似的更适合做成event 上报。

**Comment by kongfei605** [comment]
容器退出、oom之类的会做成event，可以关注一下catpaw。这个issue先close了
