### ISSUE TITLE
catagraf Startup error out of order labels

### ISSUE THREAD

**Issue by hzhuchao** [flashcatcloud/categraf#524]
catagraf Startup error:
config.toml is default config
just change
[[writers]]
url = "http://<thanos-receive>/api/v1/receive"

catagraf  startup log:
writer.go:66: W! post to http://<thanos-receive>/api/v1/receive got error: push data with remote write request got status code: 409, response body: store locally for endpoint thanos-receive-0.thanos-receive:10901: add 114 series: out of order labels

How to repair it?

**Comment by kongfei605** [comment]
409 是 (Conflict) indicates that the request could not be processed because of conflict。 看看你server端是按照哪个key做冲突判断的，然后找找冲突的原因

**Comment by hzhuchao** [comment]
server 接收端用的thanos receive，默认配置，我看catagraf文档中心提到支持对接thanos，不清楚哪个key有冲突

**Comment by noovertime7** [comment]
我也使用categraf推送到thanos 发生了一样的报错，这应该是bug

**Comment by noovertime7** [comment]
@hzhuchao 请问下问题解决了吗
