### ISSUE TITLE
mongodb采集不支持tls连接

### ISSUE THREAD

**Issue by mingyou** [flashcatcloud/categraf#542]
mongodb配置了tls连接需要证书, categraf 如何配置证书?报错:
Type: Unknown, Last error: connection() error occurred during connection handshake: x509: certificate signed by unknown authority

**Comment by kongfei605** [comment]
mongodb_uri 配置 中加一个query `tlsinsecure=true`   。
```
mongodb_uri=https://baidu.com =>  mongodb_uri=https://baidu.com?tlsinsecure=true 
```

**Comment by mingyou** [comment]
> mongodb_uri 配置 中加一个query `tlsinsecure=true` 。
> 
> ```
> mongodb_uri=https://baidu.com =>  mongodb_uri=https://baidu.com?tlsinsecure=true 
> ```
可以, 感谢老表, 666

**Comment by mingyou** [comment]
使用上面配置解决
