### ISSUE TITLE
僵尸进程采集新增采集僵尸进程名

### ISSUE THREAD

**Issue by nondevops** [flashcatcloud/categraf#545]
**What would you like to be added**:
僵尸进程采集新增采集僵尸进程名

**Why is this needed**:
当前只能看到有多少个僵死进程，不知道这些僵尸进程是哪些，有些进程是瞬间的，想知道具体信息。

**Describe the solution you'd like**

**Additional context**

**Comment by UlricQin** [comment]
这种需求不适合用指标采集了，适合 event 采集器，可以使用 [catpaw](https://mp.weixin.qq.com/s/Y-KipuKZxVn8o-NR6-ZBZg) 的 sfilter 插件

**Comment by kongfei605** [comment]
能被短时间回收的僵尸进程 不会产生影响，要关注的是持续不能被回收的僵尸进程。
