### ISSUE TITLE
为什么注释掉Prometheus Stop方法

### ISSUE THREAD

**Issue by yangliyl** [flashcatcloud/categraf#548]
https://github.com/flashcatcloud/categraf/blob/a1fb8f44012566d04d0beaffa5a4c91751cddb76/prometheus/prometheus.go#L894C1-L898C2

**Comment by kongfei605** [comment]
stop 两处场景中会用到。 
1. reload，先stop再start。 但是prometheus-agent 走得单独的逻辑，不需要main agent里的stop和start了，所以stop这里什么都不做。
2. 真的stop prometheus-agent 。这里也是单独逻辑，prometheus会自己接受并处理信号，所以也不需要stop做什么。

这里应该是一个空方法 ，不应该注释。

**Comment by yangliyl** [comment]
那我把这里的注视打开，我调main agent的Reload方法，是不是也能正确执行prometheus的reload

**Comment by yangliyl** [comment]
因为我自己想调用main agent的Reload来实现所有配置重新加载，但是我发现这里被注释掉了，prometheus并没有stop然后再start，而是直接又掉start方法，这样的话会pannic
panic: duplicate metrics collector registration attempted
我没有通过给进程发送信号的方式，我是想直接调用Reload方法实现加载

**Comment by kongfei605** [comment]
> 那我把这里的注视打开，我调main agent的Reload方法，是不是也能正确执行prometheus的reload

那要把用到stop这个chan的地方都改一下

**Comment by kongfei605** [comment]
> 因为我自己想调用main agent的Reload来实现所有配置重新加载，但是我发现这里被注释掉了，prometheus并没有stop然后再start，而是直接又掉start方法，这样的话会pannic panic: duplicate metrics collector registration attempted 我没有通过给进程发送信号的方式，我是想直接调用Reload方法实现加载

你改了prometheus.yaml ，prometheus-agent 会自动reload

**Comment by yangliyl** [comment]
我看了下prometheus这一块的信号处理有点复杂，我搞不定。最简单的办法，应该就是走直接给进程发送信号，但是我有一个疑问，main的信号处理也是调用的agent的Reload方法，那会不会有可能也会panic，当我发送信号后，prometheus的信号还没有处理结束的情况下，agent的reload已经直接完毕了，那也会在prometheus重复start。

**Comment by yangliyl** [comment]
我认为最好的解决办法是统一实现Start和Stop方法来实现启动和停止，那样不管是走信号还是走Reload方法，那都是没有问题的，而且很统一很一致

**Comment by kongfei605** [comment]
> 我看了下prometheus这一块的信号处理有点复杂，我搞不定。最简单的办法，应该就是走直接给进程发送信号，但是我有一个疑问，main的信号处理也是调用的agent的Reload方法，那会不会有可能也会panic，当我发送信号后，prometheus的信号还没有处理结束的情况下，agent的reload已经直接完毕了，那也会在prometheus重复start。

不会，信号是到整个进程的。每个处理信号的goroutine，都会收到。 可以再深入了解下。

**Comment by kongfei605** [comment]
> 我认为最好的解决办法是统一实现Start和Stop方法来实现启动和停止，那样不管是走信号还是走Reload方法，那都是没有问题的，而且很统一很一致
，后面prometheus agent可能会去掉

**Comment by yangliyl** [comment]
> > 我看了下prometheus这一块的信号处理有点复杂，我搞不定。最简单的办法，应该就是走直接给进程发送信号，但是我有一个疑问，main的信号处理也是调用的agent的Reload方法，那会不会有可能也会panic，当我发送信号后，prometheus的信号还没有处理结束的情况下，agent的reload已经直接完毕了，那也会在prometheus重复start。
> 
> 不会，信号是到整个进程的。每个处理信号的goroutine，都会收到。 可以再深入了解下。

我知道信号会到达每个处理信号的gouroutine，我可能没有描述清楚我的问题。

main agent 和 prometheus都会接受到reload的信号。他们分别执行各自的逻辑，main agent 会执行所有实现了start 和 stop 方法的。

prometheus 自己已经走了自己处理信号的reload的逻辑了，main agent还会执行一遍prometheus实现的start 和stop方法，正因为stop方法是一个空方法，相当于没有停止，仅仅执行了start方法，相当于又启动了一遍prometheus，造成panic我上面提到的。

我不知道我这些描述的问题，对prometheus和main agent reload功能逻辑的理解是否是正确的

**Comment by kongfei605** [comment]
逻辑理解不正确，不会panic。不放心的话，你可以按照你理解的逻辑测试下。

**Comment by yangliyl** [comment]
> 逻辑理解不正确，不会panic。不放心的话，你可以按照你理解的逻辑测试下。

好的，感谢
