### ISSUE TITLE
categraf 数据停止不上报时，web页面上查询的时间点一直在更新，怎么停止更新呢？

### ISSUE THREAD

**Issue by jones-0701** [flashcatcloud/categraf#550]
![image](https://github.com/flashcatcloud/categraf/assets/97278188/a4dc4b0c-8613-48da-a53c-b16a38664319)
例如，数据停止上报的时间戳为：1687771740，但是后面时间却一直在更新：1687771927.595；有办法数据不上报后，时间停止更新吗？

**Comment by kongfei605** [comment]
categraf停了还在上报？第一次听到这个反馈， 复现步骤是如何的呢？

**Comment by jones-0701** [comment]
> categraf 停在上报了吗？第一次听到这个反馈，复步骤是怎么样的呢？

categraf 进程还在，数据停止上报是指：没有相同mestic 标签数据进行上报了，但是这个时间点一直在更新；
场景：使用mtail插件第一次匹配到数据规则后，进行上报n9e，后续匹配不到后，n9e 标签对应的val值没有变化，但是数据时间点一直在更新......
还是说我理解不到位，虽然没有匹配数据到但是之前数据节点一直在更新呢

**Comment by kongfei605** [comment]
mtail插件可以理解为指标是counter类型，不上报了，也会一直保持这个值。 你要想发现值的变化可以用rate change之类的函数来查询

**Comment by jones-0701** [comment]
> 

明白，是可以用rate change函数来判断值的变化，但是会有一个问题，第一次上报时：rate change函数都是默认没变化的，所以第一次上报一直不会触发告警，这种情况要怎么搞呢？

**Comment by kongfei605** [comment]
从无到有判断，用present 
 ```present_over_time(xxx[2m]) or changes(xxx[2m])``` 就可以搞定了

**Comment by jones-0701** [comment]
> 从无到有判断，用present `present_over_time(xxx[2m]) or changes(xxx[2m])` 就可以搞定了

谢谢啦，我去试一下嘞
