### ISSUE TITLE
在权限不足的情况下，采集pod指标？

### ISSUE THREAD

**Issue by loveyang2012** [flashcatcloud/categraf#557]
背景：在是否某paas平台时，只有部分权限，有一个kubectl控制台，但是只能查看指定的namespace下的资源。

在这种情况下怎么采集pod的指标呢，需求是采集每个pod所使用的的磁盘，内存，cpu等基础指标

**Comment by UlricQin** [comment]
感觉可以咨询一下这个所谓的 PaaS 平台的提供商~~~

**Comment by loveyang2012** [comment]
有个想法，针对paas平台的租户，不关心k8s各组件的指标，只关心每个pod所使用的的资源，比如 kubectl top 看到的。
有没有一种方式，在这个能执行kubectl top的节点上 安装一个采集器，只采集 每个pod 占用的cpu 和 内存呢？

**Comment by loveyang2012** [comment]
> 感觉可以咨询一下这个所谓的 PaaS 平台的提供商~~~

有个想法，针对paas平台的租户，不关心k8s各组件的指标，只关心每个pod所使用的的资源，比如 kubectl top 看到的。
有没有一种方式，在这个能执行kubectl top的节点上 安装一个采集器，只采集 每个pod 占用的cpu 和 内存呢？

**Comment by kongfei605** [comment]
如果可以操作node，可以安装cadvisor，或者能跟kubelete的cadvisor接口交互也可以（高版本需要权限)
