### ISSUE TITLE
怎么实现nginx的日志内容的可视化呢，比如ip地区热点图？

### ISSUE THREAD

**Issue by mm8m6m7m** [flashcatcloud/categraf#568]
怎么实现nginx的日志内容的可视化呢，比如ip地区热点图？

**Comment by kongfei605** [comment]
categraf只能采集日志，比如采集到kafka，然后找能可视化的服务吧。 商业版flashcat是有这个功能的，当然也可以看看其他项目。

**Comment by mm8m6m7m** [comment]
不是可以画图吗 不能直接从es抽取吗？选择字段实现？

**Comment by kongfei605** [comment]
> 不是可以画图吗 不能直接从es抽取吗？选择字段实现？

categraf只是一个采集器，没有画图功能。
