### ISSUE TITLE
k8s以Deployment的方式部署categraf，命令测试插件时提示Failed to init config

### ISSUE THREAD

**Issue by yangxueren** [flashcatcloud/categraf#581]
### Relevant config.toml

```toml
[global]
    # whether print configs
    print_configs = true

    # add label(agent_hostname) to series
    # "" -> auto detect hostname
    # "xx" -> use specified string xx
    # "$hostname" -> auto detect hostname
    # "$ip" -> auto detect ip
    # "$hostname-$ip" -> auto detect hostname and ip to replace the vars
    # hostname = "$HOSTNAME"
    hostname = "$hostname-$ip"

    # will not add label(agent_hostname) if true
    omit_hostname = true

    # s | ms
    precision = "ms"

    # global collect interval
    interval = 15

    # [global.labels]
    # region = "shanghai"
    # env = "localhost"

    [writer_opt]
    # default: 2000
    batch = 2000
    # channel(as queue) size
    chan_size = 10000

    [[writers]]
    url = "http://nightingale-center.n9e/prometheus/v1/write"

    # Basic auth username
    basic_auth_user = ""

    # Basic auth password
    basic_auth_pass = ""

    # timeout settings, unit: ms
    timeout = 5000
    dial_timeout = 2500
    max_idle_conns_per_host = 100
```

### Logs from categraf

```text
2023/07/29 11:21:56 I! tracing disabled
{
    "ConfigDir": "/opt/categraf/conf",
    "DebugMode": true,
    "TestMode": false,
    "InputFilters": "",
    "Global": {
        "PrintConfigs": true,
        "Hostname": "$hostname-$ip",
        "IP": "172.16.0.103",
        "OmitHostname": true,
        "Labels": null,
        "Precision": "ms",
        "Interval": 15000000000,
        "Providers": null
    },
    "WriterOpt": {
        "Batch": 2000,
        "ChanSize": 10000
    },
    "Writers": [
        {
            "Url": "http://nightingale-center.n9e/prometheus/v1/write",
            "BasicAuthUser": "",
            "BasicAuthPass": "",
            "Headers": null,
            "Timeout": 5000,
            "DialTimeout": 2500,
            "MaxIdleConnsPerHost": 100
        }
    ],
    "Logs": {
        "api_key": "ef4ahfbwzwwtlwfpbertgq1i6mq0ab1q",
        "enable": false,
        "send_to": "127.0.0.1:17878",
        "send_type": "http",
        "use_compression": false,
        "compression_level": 0,
        "send_with_tls": false,
        "batch_wait": 5,
        "run_path": "/opt/categraf/run",
        "open_files_limit": 100,
        "scan_period": 10,
        "frame_size": 10,
        "collect_container_all": true,
        "container_include": null,
        "container_exclude": null,
        "processing_rules": [
            {
                "type": "",
                "name": "",
                "replace_placeholder": "",
                "pattern": "",
                "Regex": null,
                "Placeholder": null
            }
        ],
        "items": [
            {
                "Type": "file",
                "Port": 0,
                "idle_timeout": "",
                "Path": "/opt/tomcat/logs/*.txt",
                "topic": "",
                "encoding": "",
                "exclude_paths": null,
                "start_position": "",
                "include_units": null,
                "exclude_units": null,
                "container_mode": false,
                "Image": "",
                "Label": "",
                "Name": "",
                "Identifier": "",
                "channel_path": "",
                "Query": "",
                "Service": "my_service",
                "Source": "tomcat",
                "SourceCategory": "",
                "Tags": null,
                "log_processing_rules": null,
                "auto_multi_line_detection": false,
                "auto_multi_line_sample_size": 0,
                "auto_multi_line_match_threshold": 0
            }
        ],
        "topic": "",
        "brokers": null,
        "kubernetes_http_kubelet_port": 0,
        "kubernetes_https_kubelet_port": 0,
        "kubelet_auth_token_path": "",
        "kubelet_client_ca": ""
    },
    "Traces": null,
    "HTTP": null,
    "Prometheus": {
        "Enable": true,
        "LogLevel": "info",
        "ScrapeConfigFile": "/opt/categraf/scrape/in_cluster_scrape.yaml",
        "WebAddress": "",
        "StoragePath": "/opt/categraf/prometheus-wal",
        "MinBlockDuration": ""
    },
    "Ibex": null,
    "Heartbeat": null,
    "Log": {
        "FileName": "",
        "MaxSize": 0,
        "MaxAge": 0,
        "MaxBackups": 0,
        "LocalTime": false,
        "Compress": false
    },
    "HTTPProviderConfig": null
}
2023/07/29 11:21:56 main.go:128: I! runner.binarydir: /usr/bin
2023/07/29 11:21:56 main.go:129: I! runner.hostname: nightingale-categraf-6b966484c9-c4mh6
2023/07/29 11:21:56 main.go:130: I! runner.fd_limits: (soft=1048576, hard=1048576)
2023/07/29 11:21:56 main.go:131: I! runner.vm_limits: (soft=unlimited, hard=unlimited)
2023/07/29 11:21:56 provider_manager.go:61: I! use input provider: []
2023/07/29 11:21:56 traces_agent.go:19: I! traces agent disabled!
2023/07/29 11:21:56 ibex_agent.go:19: I! ibex agent disabled!
ts=2023-07-29T03:21:56.999Z caller=web.go:553 level=info component=web msg="Start listening for connections" address=127.0.0.1:0
ts=2023-07-29T03:21:56.999Z caller=prometheus.go:804 level=info msg="Starting WAL storage ..."
2023/07/29 11:21:56 agent.go:39: I! agent starting
2023/07/29 11:21:56 metrics_agent.go:275: I! input: local.http_response started
2023/07/29 11:21:56 agent.go:47: I! [*agent.MetricsAgent] started
2023/07/29 11:21:56 prometheus_agent.go:27: I! prometheus scraping started!
2023/07/29 11:21:56 agent.go:47: I! [*agent.PrometheusAgent] started
2023/07/29 11:21:56 agent.go:50: I! agent started
2023/07/29 11:21:56 metrics_reader.go:54: D! local.http_response : before gather once
2023/07/29 11:21:56 http_response.go:163: D! http_response... target: https://www.bing.com
ts=2023-07-29T03:21:57.001Z caller=tls_config.go:195 level=info component=web msg="TLS is disabled." http2=false
2023/07/29 11:21:57 http_response.go:163: D! http_response... target: https://www.baidu.com
ts=2023-07-29T03:21:57.003Z caller=db.go:332 level=info msg="replaying WAL, this may take a while" dir=/opt/categraf/prometheus-wal/wal
ts=2023-07-29T03:21:57.003Z caller=db.go:383 level=info msg="WAL segment loaded" segment=0 maxSegment=0
ts=2023-07-29T03:21:57.003Z caller=prometheus.go:825 level=info fs_type=EXT4_SUPER_MAGIC
ts=2023-07-29T03:21:57.003Z caller=prometheus.go:828 level=info msg="Agent WAL storage started"
ts=2023-07-29T03:21:57.003Z caller=prometheus.go:829 level=debug msg="Agent WAL storage options" WALSegmentSize=0B WALCompression=false StripeSize=0 TruncateFrequency=0s MinWALTime=0s MaxWALTime=0s
ts=2023-07-29T03:21:57.003Z caller=prometheus.go:258 level=info msg="Loading configuration file" filename=/opt/categraf/scrape/in_cluster_scrape.yaml
ts=2023-07-29T03:21:57.005Z caller=dedupe.go:112 component=remote level=info remote_name=68ab73 url=http://nightingale-center.n9e/prometheus/v1/write msg="Starting WAL watcher" queue=68ab73
ts=2023-07-29T03:21:57.005Z caller=dedupe.go:112 component=remote level=info remote_name=68ab73 url=http://nightingale-center.n9e/prometheus/v1/write msg="Starting scraped metadata watcher"
ts=2023-07-29T03:21:57.005Z caller=dedupe.go:112 component=remote level=info remote_name=68ab73 url=http://nightingale-center.n9e/prometheus/v1/write msg="Replaying WAL" queue=68ab73
ts=2023-07-29T03:21:57.005Z caller=dedupe.go:112 component=remote level=debug remote_name=68ab73 url=http://nightingale-center.n9e/prometheus/v1/write msg="Tailing WAL" lastCheckpoint= checkpointIndex=0 currentSegment=0 lastSegment=0
ts=2023-07-29T03:21:57.005Z caller=dedupe.go:112 component=remote level=debug remote_name=68ab73 url=http://nightingale-center.n9e/prometheus/v1/write msg="Processing segment" currentSegment=0
ts=2023-07-29T03:21:57.005Z caller=kubernetes.go:326 level=info component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
ts=2023-07-29T03:21:57.006Z caller=manager.go:289 level=debug component="discovery manager scrape" msg="Starting provider" provider=kubernetes/0 subs="map[apiserver:{} controller-manager:{} coredns:{} etcd:{} scheduler:{}]"
ts=2023-07-29T03:21:57.007Z caller=prometheus.go:285 level=info msg="Completed loading of configuration file" filename=/opt/categraf/scrape/in_cluster_scrape.yaml totalDuration=3.716272ms remote_storage=805.894µs web_handler=337ns scrape=349.816µs scrape_sd=1.628606ms notify=4.124µs notify_sd=4.037µs
ts=2023-07-29T03:21:57.007Z caller=prometheus.go:789 level=info msg="Server is ready to receive web requests."
11:21:57 http_response_response_time cert_name=baidu.com method=GET target=https://www.baidu.com 0.053850439
11:21:57 http_response_result_code cert_name=baidu.com method=GET target=https://www.baidu.com 0
11:21:57 http_response_cert_expire_timestamp cert_name=baidu.com method=GET target=https://www.baidu.com 1722909065
11:21:57 http_response_response_code cert_name=baidu.com method=GET target=https://www.baidu.com 200
11:21:57 http_response_response_code cert_name=www.bing.com method=GET target=https://www.bing.com 302
11:21:57 http_response_response_time cert_name=www.bing.com method=GET target=https://www.bing.com 0.390569243
11:21:57 http_response_result_code cert_name=www.bing.com method=GET target=https://www.bing.com 0
11:21:57 http_response_cert_expire_timestamp cert_name=www.bing.com method=GET target=https://www.bing.com 1692157665
2023/07/29 11:21:57 metrics_reader.go:60: D! local.http_response : after gather once, duration: 390.936367ms
ts=2023-07-29T03:22:02.007Z caller=manager.go:212 level=error component="scrape manager" msg="error creating new scrape pool" err="error creating HTTP client: unable to use specified CA cert /opt/categraf/pki/etcd/ca.crt" scrape_pool=etcd
ts=2023-07-29T03:22:07.007Z caller=manager.go:212 level=error component="scrape manager" msg="error creating new scrape pool" err="error creating HTTP client: unable to use specified CA cert /opt/categraf/pki/etcd/ca.crt" scrape_pool=etcd
```

### System info

categraf-v0.3.19

### Steps to reproduce

1. 按照github仓库里提供的yaml文件部署并启动categraf，可以看到容器能正常启动成功
2. 在容器内使用/usr/bin/categraf --test 进行自检测

### Expected behavior

使用自检测或插件检测的命令能否正常打印出categraf采集并返回的数据

### Actual behavior

提示 F! failed to init config: configuration file(conf/config.toml) not found

**Comment by kongfei605** [comment]
ps aux |grep categraf，复制完整的命令，再 加上 --test

**Comment by yangxueren** [comment]
按照建议直接执行/usr/bin/categraf --configs /opt/categraf/conf --test --inputs http_response，返回的内容如下，仍然没有展示该插件所采集的metric
2023/08/04 08:39:03 I! tracing disabled
{
    "ConfigDir": "/opt/categraf/conf",
    "DebugMode": false,
    "TestMode": true,
    "InputFilters": "local.http_response",
    "Global": {
        "PrintConfigs": true,
        "Hostname": "$HOSTNAME",
        "IP": "172.16.0.40",
        "OmitHostname": false,
        "Labels": null,
        "Precision": "ms",
        "Interval": 15000000000,
        "Providers": null
    },
    "WriterOpt": {
        "Batch": 2000,
        "ChanSize": 10000
    },
    "Writers": [
        {
            "Url": "http://nightingale-center.n9e/prometheus/v1/write",
            "BasicAuthUser": "",
            "BasicAuthPass": "",
            "Headers": null,
            "Timeout": 5000,
            "DialTimeout": 2500,
            "MaxIdleConnsPerHost": 100
        }
    ],
    "Logs": {
        "api_key": "ef4ahfbwzwwtlwfpbertgq1i6mq0ab1q",
        "enable": false,
        "send_to": "127.0.0.1:17878",
        "send_type": "http",
        "use_compression": false,
        "compression_level": 0,
        "send_with_tls": false,
        "batch_wait": 5,
        "run_path": "/opt/categraf/run",
        "open_files_limit": 100,
        "scan_period": 10,
        "frame_size": 10,
        "collect_container_all": true,
        "container_include": null,
        "container_exclude": null,
        "processing_rules": [
            {
                "type": "",
                "name": "",
                "replace_placeholder": "",
                "pattern": "",
                "Regex": null,
                "Placeholder": null
            }
        ],
        "items": [
            {
                "Type": "file",
                "Port": 0,
                "idle_timeout": "",
                "Path": "/opt/tomcat/logs/*.txt",
                "topic": "",
                "encoding": "",
                "exclude_paths": null,
                "start_position": "",
                "include_units": null,
                "exclude_units": null,
                "container_mode": false,
                "Image": "",
                "Label": "",
                "Name": "",
                "Identifier": "",
                "channel_path": "",
                "Query": "",
                "Service": "my_service",
                "Source": "tomcat",
                "SourceCategory": "",
                "Tags": null,
                "log_processing_rules": null,
                "auto_multi_line_detection": false,
                "auto_multi_line_sample_size": 0,
                "auto_multi_line_match_threshold": 0
            }
        ],
        "topic": "",
        "brokers": null,
        "kubernetes_http_kubelet_port": 0,
        "kubernetes_https_kubelet_port": 0,
        "kubelet_auth_token_path": "",
        "kubelet_client_ca": ""
    },
    "Traces": null,
    "HTTP": null,
    "Prometheus": {
        "Enable": true,
        "LogLevel": "info",
        "ScrapeConfigFile": "/opt/categraf/scrape/in_cluster_scrape.yaml",
        "WebAddress": "",
        "StoragePath": "/opt/categraf/prometheus-wal",
        "MinBlockDuration": ""
    },
    "Ibex": null,
    "Heartbeat": null,
    "Log": {
        "FileName": "",
        "MaxSize": 0,
        "MaxAge": 0,
        "MaxBackups": 0,
        "LocalTime": false,
        "Compress": false
    },
    "HTTPProviderConfig": null
}
2023/08/04 08:39:03 main.go:128: I! runner.binarydir: /usr/bin
2023/08/04 08:39:03 main.go:129: I! runner.hostname: nightingale-categraf-66f56d7f57-qhq97
2023/08/04 08:39:03 main.go:130: I! runner.fd_limits: (soft=1048576, hard=1048576)
2023/08/04 08:39:03 main.go:131: I! runner.vm_limits: (soft=unlimited, hard=unlimited)
2023/08/04 08:39:03 provider_manager.go:61: I! use input provider: []
2023/08/04 08:39:03 traces_agent.go:19: I! traces agent disabled!
2023/08/04 08:39:03 ibex_agent.go:19: I! ibex agent disabled!
2023/08/04 08:39:03 agent.go:39: I! agent starting
2023/08/04 08:39:03 agent.go:47: I! [*agent.MetricsAgent] started
2023/08/04 08:39:03 prometheus_agent.go:27: I! prometheus scraping started!
2023/08/04 08:39:03 agent.go:47: I! [*agent.PrometheusAgent] started
2023/08/04 08:39:03 agent.go:50: I! agent started
ts=2023-08-04T00:39:03.557Z caller=web.go:553 level=info component=web msg="Start listening for connections" address=127.0.0.1:0
ts=2023-08-04T00:39:03.557Z caller=prometheus.go:804 level=info msg="Starting WAL storage ..."
ts=2023-08-04T00:39:03.557Z caller=dir_locker.go:77 level=warn msg="A lockfile from a previous execution already existed. It was replaced" file=/opt/categraf/prometheus-wal/lock
ts=2023-08-04T00:39:03.557Z caller=prometheus.go:687 level=info msg="Stopping scrape discovery manager..."
ts=2023-08-04T00:39:03.557Z caller=prometheus.go:701 level=info msg="Stopping notify discovery manager..."
ts=2023-08-04T00:39:03.557Z caller=prometheus.go:723 level=info msg="Stopping scrape manager..."
ts=2023-08-04T00:39:03.557Z caller=prometheus.go:697 level=info msg="Notify discovery manager stopped"
ts=2023-08-04T00:39:03.558Z caller=tls_config.go:195 level=info component=web msg="TLS is disabled." http2=false
ts=2023-08-04T00:39:03.558Z caller=prometheus.go:683 level=info msg="Scrape discovery manager stopped"
ts=2023-08-04T00:39:03.558Z caller=notifier.go:608 level=info component=notifier msg="Stopping notification manager..."
ts=2023-08-04T00:39:03.558Z caller=prometheus.go:879 level=info msg="Notifier manager stopped"
ts=2023-08-04T00:39:03.558Z caller=prometheus.go:717 level=info msg="Scrape manager stopped"
ts=2023-08-04T00:39:03.558Z caller=prometheus.go:889 level=error err="opening storage failed lock DB directory: resource temporarily unavailable"

**Comment by kongfei605** [comment]
deployment 是用的prometheus agent。 想要用http_response插件，你要自己配置（configmap+挂载）。可以 先了解下deployment里做了什么。
