### ISSUE TITLE
categrafv0.3.19版本不能连外网就不能启动了？

### ISSUE THREAD

**Issue by yyqs2008** [flashcatcloud/categraf#583]
categrafv0.3.19版本不能连外网就不能启动了？

categraf: 2023/07/31 18:10:11 F! failed to init config: failed to get outbound ip: dial udp 223.5.5.5:80: connect: network is unreachable

v0.3.18还是正常的。有挺多场景被监控服务器不能上外网的，能否调整下呢

**Comment by kongfei605** [comment]
确定v0.3.18版本可以吗？ 可以把v0.3.18 版本，放到同一台机器上启动看看。

**Comment by yyqs2008** [comment]
确定v0.3.18版本可以
如图：
![QQ截图20230801084425](https://github.com/flashcatcloud/categraf/assets/1332668/6f296997-193e-4c1a-89f6-a12b46c1cca8)

**Comment by kongfei605** [comment]
升级到v0.3.20版本，这个问题已经修复了

**Comment by allenz92** [comment]
> 升级到v0.3.20版本，这个问题已经修复了 修复见#585

升级到v0.3.20有问题，ip地址变成127.0.0.1了
![升级前后对比](https://github.com/allenz92/img/blob/master/sn1.png?raw=true)

**Comment by UlricQin** [comment]
看来忘记剔除回环网卡了

**Comment by allenz92** [comment]
> 看来忘记剔除回环网卡了

调试了一下，不是通过getLocalIP获取到回环地址了。writers里配置成localhost可以复现，我做测试的时候跟n9e服务端在一台机器上。

**Comment by kongfei605** [comment]
是这样的逻辑，按照原来探测外网逻辑获取失败后，会通过连n9e的地址获取，如果获取失败了，会通过本地网卡（剔除回环，启找up状态的）获取其中一个IP

**Comment by kongfei605** [comment]
看来后面要加个逻辑，如果通过localhost连n9e  ，直接进入第三步，找启动的网卡获取一个IP地址

**Comment by UlricQin** [comment]
> 看来后面要加个逻辑，如果通过localhost连n9e ，直接进入第三步，找启动的网卡获取一个IP地址

可以考虑搞成：如果第二步获取的是127.0.0.1或者::1，就继续走第三步

**Comment by kongfei605** [comment]
这个问题v0.3.20已经修改成这个逻辑了，第二步，通过连n9e获取IP，如果是127或者localhost，会直接进入第三步。这个issue先关了。
