### ISSUE TITLE
reload error

### ISSUE THREAD

**Issue by tanxiao1990** [flashcatcloud/categraf#60]
重载的时候，偶尔会出现中断，进程直接退出

2022/06/28 20:44:42 agent.go:69: I! agent stopping
panic: send on closed channel

goroutine 1 [running]:
flashcat.cloud/categraf/agent.(*Agent).Stop(0xc000143df0?)
        /home/runner/work/categraf/categraf/agent/agent.go:73 +0xdf
flashcat.cloud/categraf/agent.(*Agent).Reload(0xc000143e70?)
        /home/runner/work/categraf/categraf/agent/agent.go:84 +0x53
main.handleSignal(0xc0002d7020?)
        /home/runner/work/categraf/categraf/main.go:94 +0x206
main.runAgent(0x0?)
        /home/runner/work/categraf/categraf/main_posix.go:12 +0x28
main.main()
        /home/runner/work/categraf/categraf/main.go:69 +0x17d

**Comment by kongfei605** [comment]
复现步骤就是不停的reload ？ 可以按照bug report模板提供一些更详细的信息

**Comment by kongfei605** [comment]
https://github.com/flashcatcloud/categraf/pull/477
https://github.com/flashcatcloud/categraf/pull/478
