### ISSUE TITLE
阿里云插件采集报错

### ISSUE THREAD

**Issue by fedocx** [flashcatcloud/categraf#600]
### Relevant config.toml

```toml
# # collect interval
# interval = 60
[[instances]]
# # endpoint region 参考 https://help.aliyun.com/document_detail/28616.html#section-72p-xhs-6qt
# region="cn-beijing"
region="cn-hangzhou"
# endpoint="metrics.cn-hangzhou.aliyuncs.com"
endpoint="metrics-vpc.cn-hangzhou.aliyuncs.com"
access_key_id="your-access-key-id"

access_key_secret="your-access-key-secret"

interval_times=4
delay="10m"
period="60s"
# # namespace 参考 https://help.aliyun.com/document_detail/163515.htm?spm=a2c4g.11186623.0.0.44d65c58mhgNw3
namespaces=["acs_ecs_dashboard"]
#[[instances.metric_filters]]
## # metric name 参考 https://help.aliyun.com/document_detail/163515.htm?spm=a2c4g.11186623.0.0.401d15c73Z0dZh
## # 参考页面中的Metric Id 填入下面的metricName ,页面中包含中文的Metric Name对应接口中的Description
## metric_names=["cpu_cores","vm.TcpCount"]
#metric_names=["cpu_cores","cpu_total","vm.TcpCount"]
#namespace=""
#ratelimit=25
#catch_ttl="1h"
#timeout="5s"
```

### Logs from categraf

```text
Aug 15 10:20:44 vpc-rancher-01 categraf[15363]: Message: code: 503, The request has failed due to a temporary failure of the server. request id: 
Aug 15 10:20:44 vpc-rancher-01 categraf[15363]: Data: {"Code":"ServiceUnavailable","HostId":"metrics-vpc.cn-hangzhou.aliyuncs.com","Message":"The request has failed due to a temporary failure of the server.","Recommend":"https://api.aliyun.com/troubleshoot?q=ServiceUnavailable\u0026product=Cms","RequestId":"","statusCode":503}
Aug 15 10:20:44 vpc-rancher-01 categraf[15363]: 2023/08/15 10:20:44 cloud.go:315: E! get metrics error, SDKError:
Aug 15 10:20:44 vpc-rancher-01 categraf[15363]: StatusCode: 503
Aug 15 10:20:44 vpc-rancher-01 categraf[15363]: Code: ServiceUnavailable
```

### System info

categraf-v0.3.22,CentOS Linux release 7.9.2009

### Steps to reproduce

1. 修改配置文件，重启
2.
3.
...

### Expected behavior

正常

### Actual behavior

正常

**Comment by Yuaninga** [comment]
我也是正常启动了，按照文档配置，但是数据采集后是：

<img width="1517" alt="image" src="https://github.com/flashcatcloud/categraf/assets/64267484/471cffa7-d68e-41ba-8bea-ae2ce4cf808b">

**Comment by Yuaninga** [comment]
配置和部署和文档一样 ，https://flashcat.cloud/docs/content/flashcat-monitor/categraf/plugin/aliyun/

`interval = 60
[[instances]]
region="cn-hangzhou"
endpoint="metrics.cn-hangzhou.aliyuncs.com"
access_key_id="xxx"
access_key_secret="xxx"
delay="5m"  
period="60s"
namespaces=["acs_vpc_eip", "acs_ecs_dashboard"]
ratelimit=25
batch_size=500  
timeout="5s" 
[[instances.metric_filters]]
namespaces=""
metric_names=["cpu_cores","vm.TcpCount", "cpu_idle"]
`

**Comment by kongfei605** [comment]
> ### Relevant config.toml
> ```toml
> # # collect interval
> # interval = 60
> [[instances]]
> # # endpoint region 参考 https://help.aliyun.com/document_detail/28616.html#section-72p-xhs-6qt
> # region="cn-beijing"
> region="cn-hangzhou"
> # endpoint="metrics.cn-hangzhou.aliyuncs.com"
> endpoint="metrics-vpc.cn-hangzhou.aliyuncs.com"
> access_key_id="your-access-key-id"
> 
> access_key_secret="your-access-key-secret"
> 
> interval_times=4
> delay="10m"
> period="60s"
> # # namespace 参考 https://help.aliyun.com/document_detail/163515.htm?spm=a2c4g.11186623.0.0.44d65c58mhgNw3
> namespaces=["acs_ecs_dashboard"]
> #[[instances.metric_filters]]
> ## # metric name 参考 https://help.aliyun.com/document_detail/163515.htm?spm=a2c4g.11186623.0.0.401d15c73Z0dZh
> ## # 参考页面中的Metric Id 填入下面的metricName ,页面中包含中文的Metric Name对应接口中的Description
> ## metric_names=["cpu_cores","vm.TcpCount"]
> #metric_names=["cpu_cores","cpu_total","vm.TcpCount"]
> #namespace=""
> #ratelimit=25
> #catch_ttl="1h"
> #timeout="5s"
> ```
> 
> ### Logs from categraf
> ```
> Aug 15 10:20:44 vpc-rancher-01 categraf[15363]: Message: code: 503, The request has failed due to a temporary failure of the server. request id: 
> Aug 15 10:20:44 vpc-rancher-01 categraf[15363]: Data: {"Code":"ServiceUnavailable","HostId":"metrics-vpc.cn-hangzhou.aliyuncs.com","Message":"The request has failed due to a temporary failure of the server.","Recommend":"https://api.aliyun.com/troubleshoot?q=ServiceUnavailable\u0026product=Cms","RequestId":"","statusCode":503}
> Aug 15 10:20:44 vpc-rancher-01 categraf[15363]: 2023/08/15 10:20:44 cloud.go:315: E! get metrics error, SDKError:
> Aug 15 10:20:44 vpc-rancher-01 categraf[15363]: StatusCode: 503
> Aug 15 10:20:44 vpc-rancher-01 categraf[15363]: Code: ServiceUnavailable
> ```
> 
> ### System info
> categraf-v0.3.22,CentOS Linux release 7.9.2009
> 
> ### Docker
> _No response_
> 
> ### Steps to reproduce
> 1. 修改配置文件，重启
> 
> ...
> 
> ### Expected behavior
> 正常
> 
> ### Actual behavior
> 正常
> 
> ### Additional info
> _No response_

检查下请求的endpoint 是否正确？看报错是你请求的阿里云不可用，对照文档的region和endpoint再检查下

**Comment by kongfei605** [comment]
> 配置和部署和文档一样 ，https://flashcat.cloud/docs/content/flashcat-monitor/categraf/plugin/aliyun/
> 
> ```
> interval = 60
> [[instances]]
> region="cn-hangzhou"
> endpoint="metrics.cn-hangzhou.aliyuncs.com"
> access_key_id="xxx"
> access_key_secret="xxx"
> delay="5m"  
> period="60s"
> namespaces=["acs_vpc_eip", "acs_ecs_dashboard"]
> ratelimit=25
> batch_size=500  
> timeout="5s" 
> [[instances.metric_filters]]
> namespaces=""
> metric_names=["cpu_cores","vm.TcpCount", "cpu_idle"]
> ```

可以先去掉metrics_filter试试。

**Comment by Yuaninga** [comment]
我把metrics_filter的部分去掉了：

<img width="419" alt="image" src="https://github.com/flashcatcloud/categraf/assets/64267484/0c1f105c-f813-4381-b3cf-d77c6ff197b7">


这个是categraf的status：

<img width="1364" alt="image" src="https://github.com/flashcatcloud/categraf/assets/64267484/2d884940-52d1-4ea3-99f1-9a80c5255ca1">

**Comment by Yuaninga** [comment]
重新部署运行了下日志显示：

日志上显示说限制了请求了，aliyun超过了每秒最大调用数（默认为10）

<img width="1374" alt="image" src="https://github.com/flashcatcloud/categraf/assets/64267484/80b18d3f-5a66-4a6d-abb1-1b8d970860af">

**Comment by kongfei605** [comment]
关于限流
1 调大配置中的ratelimit
2 每个namespace 拆分到一个instance内
3 server端如果再限流，那要联系阿里云或者使用企业云监控了

**Comment by fedocx** [comment]
> > ### Relevant config.toml
> > ```toml
> > # # collect interval
> > # interval = 60
> > [[instances]]
> > # # endpoint region 参考 https://help.aliyun.com/document_detail/28616.html#section-72p-xhs-6qt
> > # region="cn-beijing"
> > region="cn-hangzhou"
> > # endpoint="metrics.cn-hangzhou.aliyuncs.com"
> > endpoint="metrics-vpc.cn-hangzhou.aliyuncs.com"
> > access_key_id="your-access-key-id"
> > 
> > access_key_secret="your-access-key-secret"
> > 
> > interval_times=4
> > delay="10m"
> > period="60s"
> > # # namespace 参考 https://help.aliyun.com/document_detail/163515.htm?spm=a2c4g.11186623.0.0.44d65c58mhgNw3
> > namespaces=["acs_ecs_dashboard"]
> > #[[instances.metric_filters]]
> > ## # metric name 参考 https://help.aliyun.com/document_detail/163515.htm?spm=a2c4g.11186623.0.0.401d15c73Z0dZh
> > ## # 参考页面中的Metric Id 填入下面的metricName ,页面中包含中文的Metric Name对应接口中的Description
> > ## metric_names=["cpu_cores","vm.TcpCount"]
> > #metric_names=["cpu_cores","cpu_total","vm.TcpCount"]
> > #namespace=""
> > #ratelimit=25
> > #catch_ttl="1h"
> > #timeout="5s"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Logs from categraf
> > ```
> > Aug 15 10:20:44 vpc-rancher-01 categraf[15363]: Message: code: 503, The request has failed due to a temporary failure of the server. request id: 
> > Aug 15 10:20:44 vpc-rancher-01 categraf[15363]: Data: {"Code":"ServiceUnavailable","HostId":"metrics-vpc.cn-hangzhou.aliyuncs.com","Message":"The request has failed due to a temporary failure of the server.","Recommend":"https://api.aliyun.com/troubleshoot?q=ServiceUnavailable\u0026product=Cms","RequestId":"","statusCode":503}
> > Aug 15 10:20:44 vpc-rancher-01 categraf[15363]: 2023/08/15 10:20:44 cloud.go:315: E! get metrics error, SDKError:
> > Aug 15 10:20:44 vpc-rancher-01 categraf[15363]: StatusCode: 503
> > Aug 15 10:20:44 vpc-rancher-01 categraf[15363]: Code: ServiceUnavailable
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### System info
> > categraf-v0.3.22,CentOS Linux release 7.9.2009
> > ### Docker
> > _No response_
> > ### Steps to reproduce
> > 
> > 1. 修改配置文件，重启
> > 
> > ...
> > ### Expected behavior
> > 正常
> > ### Actual behavior
> > 正常
> > ### Additional info
> > _No response_
> 
> 检查下请求的endpoint 是否正确？看报错是你请求的阿里云不可用，对照文档的region和endpoint再检查下

核对了region和endpoint都是cn-hangzhou，我这能采集到数据，这个报错偶尔会报，应该是aliyun调用次数限制导致。看了下retelimit是在instances.metric_filters下面，由于云监控指标太多，且一个个metric去添加不够灵活，所以不太希望去开启这个功能。

**Comment by fedocx** [comment]
当采集process开始的指标的情况下会报错503的问题，如process.expend, process.cpu等。下面附一个具体请求和返回。
`2023/08/17 17:43:59 cms.go:125: describemetriclist: {
   "EndTime": "2023-08-17 17:41:39",
   "MetricName": "process.cpu",
   "Namespace": "acs_ecs_dashboard",
   "StartTime": "2023-08-17 17:40:39"
} SDKError:
   StatusCode: 503
   Code: ServiceUnavailable
   Message: code: 503, The request has failed due to a temporary failure of the server. request id: 09F8E9F4-64C9-5E80-9AA4-BE9A32AAD7D4
   Data: {"Code":"ServiceUnavailable","HostId":"metrics.cn-hangzhou.aliyuncs.com","Message":"The request has failed due to a temporary failure of the server.","Recommend":"https://api.aliyun.com/troubleshoot?q=ServiceUnavailable\u0026product=Cms","RequestId":"09F8E9F4-64C9-5E80-9AA4-BE9A32AAD7D4","statusCode":503}`

**Comment by fedocx** [comment]
windows的机器指标采集的时候会报
2023/08/17 17:57:29 cms.go:130: datapointcoverter
2023/08/17 17:57:29 cloud.go:315: E! get metrics error, json: cannot unmarshal string into Go struct field Point.Value of type float64。

有下面的数据导致不能转换
{"timestamp":1692263715000,"instanceId":"i-xxxxxx","userId":"111111111","Value":""}

**Comment by kongfei605** [comment]
这个value为空字符串？./categraf --version看看版本， 然后./categraf --debug --inputs aliyun 把报错截个图 看看

**Comment by kongfei605** [comment]
哪个namespace  value 会返回  ”“ ?  方便的话 截个图？

**Comment by kongfei605** [comment]
> it是在instances.metric_filte

filter可以不配置，默认是采集所有。

**Comment by kongfei605** [comment]
这个issue还有后续吗？

**Comment by fedocx** [comment]
先不管了，process.cpu这种指标采集问了阿里需要instanceid，我这用不着。空值的问题我已经提pr修复了。

**Comment by kongfei605** [comment]
那issue 先关掉了。这个PR之前，我们给商业客户采集的指标也没遇到过空值的问题，限流倒是遇到过。
