### ISSUE TITLE
是否可以抓取springboot应用输出的metrics

### ISSUE THREAD

**Issue by jingzhao-self** [flashcatcloud/categraf#61]
我找了相关文档，没有发现要通过哪个input插件来读取用户自定义应用的metrics指标，请给出提示。

**Comment by UlricQin** [comment]
Springboot程序是怎么暴露指标的？用的类似micrometer那样的库？通过/metrics接口暴露的？那就直接用prometheus插件来抓就行了

**Comment by UlricQin** [comment]
使用categraf的prometheus采集器，作为sidecar和业务进程部署在一起，抓取本机的业务指标，抓到之后categraf会推给远端夜莺server

**Comment by jingzhao-self** [comment]
ok，试了一下input.prometheus，确实可以抓取指标并推送给远端，简单记录一下：

> vim conf/input.prometheus/prometheus.toml  #单服务器中的配置
`
[[instances]]
urls = [
    "http://localhost:9104/metrics"
]
url_label_key = "instance"
url_label_value = "{{.Host}}"
`
> ./categraf --test --inputs prometheus

**Comment by UlricQin** [comment]
使用 categraf 0.1.11 版本以上的版本：https://github.com/flashcatcloud/categraf/releases/tag/v0.1.11
