### ISSUE TITLE
Categraf数据采集时导致cpu增高

### ISSUE THREAD

**Issue by zimu312500** [flashcatcloud/categraf#617]
**What would you like to be added**:
在设定一样的采集间隔时，比如60s，则在每分钟时主机cpu会增高，希望各个采集任务进行随机，避免cpu突刺
**Why is this needed**:

**Describe the solution you'd like**

**Additional context**
版本：v0.3.17

**Comment by kongfei605** [comment]
用了什么插件？采集了多少目标？每个目标返回时间多少？是否设置超时时间？ cpu飙升到多少？

**Comment by kongfei605** [comment]
这个issue还有后续没？

**Comment by zimu312500** [comment]
观察了一段时间，后面监控没有发现。
