### ISSUE TITLE
snmp报错getting table columns: Was that a table

### ISSUE THREAD

**Issue by lddlww** [flashcatcloud/categraf#625]
### Relevant config.toml

```toml
no
```

### Logs from categraf

```text
failed to init input: local.snmp error: initializing table hwCBQoSMultiPolicyStatClassifierName ins: getting table columns: Was that a table? SNMPv2-SMI::enterprises.2011.5.25.32.1.1.5.6.8.1.3: exit status 1
```

### System info

no

### Steps to reproduce

no

### Expected behavior

正常

### Actual behavior

异常

### Additional info

categraf貌似会使用snmptable去判断是否是table，如果不是标准的mib，会导致报错

**Comment by kongfei605** [comment]
> categraf貌似会使用snmptable去判断是否是table，如果不是标准的mib，会导致报错

感谢反馈，目前是这个逻辑，可以先将mib文件加入到系统mib路径内。

**Comment by kongfei605** [comment]
以centos为例
1. 将文件解压到 /usr/share/snmp/mibs目录下 ，得到如下文件 
ABC-MIB.txt

2. vi /etc/snmp/snmp.conf  添加以下内容
mibs +ABC-MIB


3. 重启snmpd 
systemctl restart snmpd.service

**Comment by lddlww** [comment]
多谢回复，我们测试下
