### ISSUE TITLE
input.http_response插件使用post请求的body如何设置，配置body启动报错，各位大佬求解。

### ISSUE THREAD

**Issue by IT-Forerunner** [flashcatcloud/categraf#642]
input.http_response插件使用post请求的body如何设置，配置body启动报错。配置如下图：
![4WMCdiL6fYQ](https://github.com/flashcatcloud/categraf/assets/116343416/085894db-061e-40fa-b89c-2edaed38d967)
启动得时候报错。如下图
![4WMCjwxtu3U](https://github.com/flashcatcloud/categraf/assets/116343416/a35dd7ea-2be8-4785-af75-ba61abb2d458)

**Comment by kongfei605** [comment]
```
body = '''
 {'fake':'data'}
'''
```
少了3个单引号，再仔细看下原始的配置。 然后body的格式不需要写什么form-data

**Comment by IT-Forerunner** [comment]
> ```
> body = '''
>  {'fake':'data'}
> '''
> ```
> 
> 少了3个单引号，再仔细看下原始的配置。 然后body的格式不需要写什么form-data

大佬 你说的对，确实是这样的，麻烦请教一下您，如果多个参数，要以什么格式写呢。文件太少找不到多个参数的示例。

**Comment by kongfei605** [comment]
> > ```
> > body = '''
> >  {'fake':'data'}
> > '''
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 少了3个单引号，再仔细看下原始的配置。 然后body的格式不需要写什么form-data
> 
> 大佬 你说的对，确实是这样的，麻烦请教一下您，如果多个参数，要以什么格式写呢。文件太少找不到多个参数的示例。

```
body = '''
 {'fake':'data', 'fake2':'data2'}
'''
```
