### ISSUE TITLE
categraf 添加nginx vst监控之后，点击夜莺监控界面上的“未归组对象”和“全部对象”报语法错误

### ISSUE THREAD

**Issue by shaojiechao** [flashcatcloud/categraf#643]
categraf添加nginx vts模块数据，prometheus.toml 内容如下：

[[instances]]
urls = [
     "http://xxxxxx/vts_status/format/prometheus"
]

url_label_key = "instance"
url_label_value = "{{.Host}}"

添加了之后，发现点击夜莺监控界面上的“未归组对象”和“全部对象”报语法错误，且导致结果出不来，报错信息如下所示：
<img width="1401" alt="image" src="https://github.com/flashcatcloud/categraf/assets/95906788/8979d8bb-45c1-473a-8efa-6c615693ab62">

<img width="1402" alt="image" src="https://github.com/flashcatcloud/categraf/assets/95906788/c122cc25-6877-46eb-b73a-f32a1860b786">

**Comment by shaojiechao** [comment]
nginx vts监控数据中有这个“ * ”，如下所示：
<img width="1291" alt="image" src="https://github.com/flashcatcloud/categraf/assets/95906788/f72213a8-6d05-4067-8a4f-f27b7c7ccbec">

夜莺的版本：
前端版本：5.15.0
后端版本：v5.15.0-87899cbedbc7bfcfff61052ebeed945a57a418d2

categraf 版本：
v0.2.32

**Comment by kongfei605** [comment]
这个是因为有host=*的数据， 夜莺v6 修复了这个问题。可以搜一下类似的issue，answer.flashcat.cloud也有类似的问答。

**Comment by Jerry-fmcheng** [comment]
可使用prometheus agent方式进行采集，不会报错
