### ISSUE TITLE
用http_response插件监控一个url，当这个url所在的服务关闭之后，夜莺就无法查询到结果，导致告警无法发送

### ISSUE THREAD

**Issue by shaojiechao** [flashcatcloud/categraf#654]
通过http_response插件监控向量数据库的6333端口，当关闭这个服务之后，再通过夜莺就无法查询这个url的监控结果，只会在日志中打印出该url无法连接，猜测应该当某些服务关闭的时候，它就没有数据上报进而导致告警无法发送，那么问一下http_response有没有心跳检测机制呢，比如机器down机，理论上也没有数据上报了，但它就会检测出这个机器宕机了，从而正常发送告警

**Comment by shaojiechao** [comment]
<img width="1432" alt="image" src="https://github.com/flashcatcloud/categraf/assets/95906788/1d6d3921-9739-428e-bb2d-119bf2ffcb69">

**Comment by wthahaha** [comment]
telegraf有个tcp端口监控的插件，不知categraf有没有

**Comment by fedocx** [comment]
net_response 网络探测插件，通常用于监控本机某个端口是否在监听，或远端某个端口是否能连通  
这个应该可以

**Comment by lesteryou** [comment]
你根据http_response的哪个指标去触发告警的？
我这边是根据 http_response_result_code 这指标做监控的，只要值!=0就告警。
看源码，无论是dns、地址错误、超时、连接失败、http-status-code有问题，都会有相应的值（只有success，才为0）
	Success          uint64 = 0
	ConnectionFailed uint64 = 1
	Timeout          uint64 = 2
	DNSError         uint64 = 3
	AddressError     uint64 = 4
	BodyMismatch     uint64 = 5
	CodeMismatch     uint64 = 6

**Comment by shaojiechao** [comment]
<img width="579" alt="image" src="https://github.com/flashcatcloud/categraf/assets/95906788/646a1776-40b4-48ff-9f14-eb4a2d72708a">

就是按照如图配置的了一个url tag，当这个url所对应的服务关闭之后，在夜莺里就搜索不到值了
