### ISSUE TITLE
categraf exec模块自定义脚本为什么和open falcon plugin差别那么大呢

### ISSUE THREAD

**Issue by wangteng0906** [flashcatcloud/categraf#663]
**What would you like to be added**:
执行效果同open falcon保持一致
**Why is this needed**:
![image](https://github.com/flashcatcloud/categraf/assets/72957138/1e1ef321-4e8e-45e2-8b39-1dd8802fd196)

**Describe the solution you'd like**
相同的背景下，执行的结果根本就不同，categraf有毛刺现象，也不知道为啥会出现，falcon中就没有，求解
**Additional context**

**Comment by wangteng0906** [comment]
> 看看采集周期是否相同

采集周期是一致的都是三秒，刚刚破案，是falcon自身的问题（但是不清楚他为啥会出现那样的情况）。

**Comment by kongfei605** [comment]
好的，感谢回复。 如果没问题，我把issue close掉。
