### ISSUE TITLE
已监控的机器列表中指标为unknow

### ISSUE THREAD

**Issue by shaojiechao** [flashcatcloud/categraf#668]
categraf版本： v0.2.32
nightingale版本： v6.1.0

已监控的机器列表中的一些指标unknow，如下所示：
<img width="853" alt="image" src="https://github.com/flashcatcloud/categraf/assets/95906788/3ea4e538-78cc-4f32-a976-6a6737839f1d">

**Comment by shaojiechao** [comment]
顺便再咨询一下categraf的input.http_response插件除了post、get请求外，是否支持head请求

**Comment by kongfei605** [comment]
1. 更新到v0.3.31测试下。
2. 支持 。

**Comment by shaojiechao** [comment]
感谢支持
