### ISSUE TITLE
通过/prometheus/v1/write接口推送数据异常

### ISSUE THREAD

**Issue by shaojiechao** [flashcatcloud/categraf#670]
推送案例如下所示：
curl -H 'content-Encoding: gzip' http://127.0.0.1:17000/prometheus/v1/write -d '{"metric": "cpu-test","timestamp": 1637732157,"tags": {"cpu": "cpu-totglin-test"},"value": 30.5}'

报错信息如下所示：
snappy: corrupt input

夜莺版本：6.2.0

请问一下这个有相关接口推送的案例可以参考么

**Comment by shaojiechao** [comment]
顺便咨询一下以下两个接口推送数据是否有相关案例参考：

/api/push/remotewrite 走的是 Prometheus RemoteWrite 的传输协议，使用 Protobuf 编码
/api/push/pushgateway 走的是 Prometheus Pushgateway 的传输协议，文本的传输协议

**Comment by interfacekun** [comment]
我的6.3也是报这个错误，好像是promethrus报的，目前也不知道怎么解决

**Comment by interfacekun** [comment]
升级到6.3.1就解决了
