### ISSUE TITLE
categraf 采集ceph 暴露的标准metrics时，无法解析某指标格式

### ISSUE THREAD

**Issue by wzq0824** [flashcatcloud/categraf#673]
categraf 版本: v0.3.21

ceph mgr module enable prometheus

现象：
![image](https://github.com/flashcatcloud/categraf/assets/81143005/92ddb5f7-5c7d-45c7-b7f7-ca36639b07c3)
 
ceph metrics 1938行格式无明显问题:
![image](https://github.com/flashcatcloud/categraf/assets/81143005/7ff60990-0261-4733-83c8-e5495257716c)

导致ceph无法正常采集

**Comment by wzq0824** [comment]
应该是注释的问题，相同指标只用注释一次， 唯独这个指标每行都加了注释， 报错是 Second HELP line... 
categraf 这块解析的时候可能就有问题了， 我试试prometheus能不能采集

**Comment by UlricQin** [comment]
> 应该是注释的问题，相同指标只用注释一次， 唯独这个指标每行都加了注释， 报错是 Second HELP line... categraf 这块解析的时候可能就有问题了， 我试试prometheus能不能采集

Prometheus 可以采集么？这个其实应该提哥 issue 给 ceph 社区，让他们改改

**Comment by kongfei605** [comment]
你用promtoll check 一下，也是报相同的错。 

v0.3.40 设置 duplication_allowed=true  ，可以处理这种重复指标说明的情况。
