### ISSUE TITLE
categraf有没有windows 32位版本

### ISSUE THREAD

**Issue by Hmm-zhang** [flashcatcloud/categraf#682]
请问目前有没有Windows32位版本的categraf,源码编译的32位版本运行有问题。

**Comment by kongfei605** [comment]
没有哈，只能自行编译了。

**Comment by Hmm-zhang** [comment]
32位编译后有问题，能提供指引吗？谢谢！

**Comment by kongfei605** [comment]
有报错没？ 你用哪些插件 编译那些插件吧。不敢保证一定编译通过，因为很多依赖的库都是amd64版本的
