### ISSUE TITLE
夜莺拿不到数据，求助

### ISSUE THREAD

**Issue by grandwill** [flashcatcloud/categraf#683]
环境是 aws eks
[daemonset.yaml](https://github.com/flashcatcloud/categraf/blob/main/k8s/daemonset.yaml) 修改镜像版本为 0.3.33
夜莺为 6.3.0 独立机器

daemonset 启动日志
<img width="738" alt="image" src="https://github.com/flashcatcloud/categraf/assets/141031825/0f66229c-7da6-4846-85cc-64b24052cbda">

夜莺日志：
<img width="1628" alt="image" src="https://github.com/flashcatcloud/categraf/assets/141031825/e49b534f-7601-4d6a-8f91-7401bdb73a36">

拿不到时序数据诶，是我哪里搞错了吗

**Comment by interfacekun** [comment]
我跟你一样拿不到，我的是6.3

**Comment by haigeek** [comment]
@grandwill @interfacekun 我也遇到了一样的问题，升级到6.3.1 就可以了

**Comment by grandwill** [comment]
确实，更新夜莺之后就能拿到了。。。。

**Comment by grandwill** [comment]
> 我跟你一样拿不到，我的是6.3

更新夜莺就好了
