### ISSUE TITLE
whois 插件问题

### ISSUE THREAD

**Issue by aaluopy** [flashcatcloud/categraf#684]
### Relevant config.toml

```toml
。
```

### Logs from categraf

```text
。
```

### System info

categraf:v0.3.32, n9e:v6.1.0-4a358f5cffdbdb6934ebeb11efe2018966b878ea, prometheus:v2.47.0

### Docker

。

### Steps to reproduce

配置监控了.com和.cn的域名，但是查询结果中只有.com的信息，没有.cn的信息。
<img width="166" alt="企业微信截图_169728500059" src="https://github.com/flashcatcloud/categraf/assets/121002916/aa53fdaa-162e-4940-9790-f6569bd6428b">
<img width="928" alt="企业微信截图_1697285134519" src="https://github.com/flashcatcloud/categraf/assets/121002916/4f1300cf-0380-4a3e-a353-a6afff0f00fc">
![image](https://github.com/flashcatcloud/categraf/assets/121002916/5ee967b2-5a8e-4a21-aa14-e4ea76ce1fd1)

### Expected behavior

。

### Actual behavior

。

**Comment by tanxiao1990** [comment]
可提供几个用于测试的 .cn 域名出来看看
