### ISSUE TITLE
snmpwalk命令可以正确获取到oid值，插件获取却失败

### ISSUE THREAD

**Issue by bestsiyue** [flashcatcloud/categraf#686]
### Relevant config.toml

```toml
[[instances.table]]
oid = ".1.3.6.1.4.1.674.10892.5.4.1100.50.1.5"
name = "memorystatus"
```

### Logs from categraf

```text
2023/10/16 13:43:23 I! tracing disabled
2023/10/16 13:43:23 main.go:130: I! runner.binarydir: /opt/categraf
2023/10/16 13:43:23 main.go:131: I! runner.hostname: EM-6CU622VC6D
2023/10/16 13:43:23 main.go:132: I! runner.fd_limits: (soft=4096, hard=4096)
2023/10/16 13:43:23 main.go:133: I! runner.vm_limits: (soft=unlimited, hard=unlimited)
2023/10/16 13:43:23 provider_manager.go:60: I! use input provider: [local]
2023/10/16 13:43:23 traces_agent.go:19: I! traces agent disabled!
2023/10/16 13:43:23 prometheus_agent.go:19: I! prometheus scraping disabled!
2023/10/16 13:43:23 ibex_agent.go:19: I! ibex agent disabled!
2023/10/16 13:43:23 agent.go:39: I! agent starting
2023/10/16 13:43:23 metrics_agent.go:279: E! failed to init input: local.snmp error: initializing table memorystatus ins: getting table columns: Was that a table? IDRAC-MIB-SMIv2::memoryDeviceStatus: exit status 1
2023/10/16 13:43:23 agent.go:47: I! [*agent.MetricsAgent] started
2023/10/16 13:43:23 agent.go:50: I! agent started
```

### System info

v0.3.34-ea4ed7a88b2f0da31e306652a68f68b6721a0a14

### Steps to reproduce

这是一个查看内存状态的oid，使用snmpwalk可以正确获取到数据。
![image](https://github.com/flashcatcloud/categraf/assets/50395020/02f68c59-26c9-4956-a90c-3c464fb8abf2)

snmp.toml配置如下
![image](https://github.com/flashcatcloud/categraf/assets/50395020/d043a834-fe15-43c6-bd24-b03a963196ab)

测试提示我无法初始化输入。如下
![image](https://github.com/flashcatcloud/categraf/assets/50395020/a12c6d8b-383c-4bd6-a538-e98868915fc2)

这个是什么问题？

### Expected behavior

。。。

### Actual behavior

。。。

**Comment by kongfei605** [comment]
需要导入你的私有mib库。 可以翻一下之前的issue，有导入mib库的步骤。

**Comment by kongfei605** [comment]
你这个oid是真的一个table ？ 还是一个field ？

**Comment by bestsiyue** [comment]
理解问题了，不是mib库的问题，而是这个oid不是一个table类型，不被识别。需要更上层的table oid来获取数据。但这样意味着更大的开销，整个table的数据都会被写入。
![image](https://github.com/flashcatcloud/categraf/assets/50395020/e58928a2-6f0d-46f1-94da-c80f065b13da)

**Comment by bestsiyue** [comment]
按照插件的逻辑，应该都不算，因为不管是table类型还是field类型，都会报错。

table
![image](https://github.com/flashcatcloud/categraf/assets/50395020/c41967f7-de9c-4df0-aa5e-97f138cdf9b9)

field
![image](https://github.com/flashcatcloud/categraf/assets/50395020/46d88e31-2b40-48be-a9ec-9462775f6731)


而且我想用取巧的方式，使用更上层的table oid，然后使用metrics_pass参数过滤出想要的memoryDeviceStatus结果，发现过滤没有效果，依然输出了全部数据。
![image](https://github.com/flashcatcloud/categraf/assets/50395020/7e11f47b-7071-43a6-8bd6-d9f55475bdae)

![image](https://github.com/flashcatcloud/categraf/assets/50395020/4cc1634e-a895-44f6-92eb-66ae8793846f)

**Comment by kongfei605** [comment]
不是table 类型，用instances.field配置 
````
[[instances.field]]
oid = "RFC1213-MIB::sysUpTime.0"
name = "uptime"
```

**Comment by bestsiyue** [comment]
field类型一样报错
![image](https://github.com/flashcatcloud/categraf/assets/50395020/49e5a466-cd14-475c-a2d8-d0507480d051)

![image](https://github.com/flashcatcloud/categraf/assets/50395020/052e5b37-7b75-4d8c-9aae-ee9286ecae1b)

**Comment by kongfei605** [comment]
这个报错就是要导入mib库了， 参考这个issue的方法导入 https://github.com/flashcatcloud/categraf/issues/625

**Comment by bestsiyue** [comment]
mib库是有的，只是命令不一致，结果输出就会报错。
![image](https://github.com/flashcatcloud/categraf/assets/50395020/3754bf9c-ebfa-431d-be9d-4e4ef6d405e0)

**Comment by bestsiyue** [comment]
另外如上的问题，metrics_pass参数为什么没有生效，并没有过滤到不想要的指标数据。

**Comment by kongfei605** [comment]
```
[[instances.table]]
name="memorystatus"
### table可以是虚拟表，只写name ，负责组织数据

[[instances.table.fields]]
oid=".1.3.6.1.4.1.674.10892.5.4.1100.50.1.5"
name="xxxx"
```

metrics_pass 是生效到instances级别的 ，按照你的思路 
```
[[instances]]
 agents = ["xxxx"]
metrics_pass = ["yyyy"]

[[instances.table]]
name="memorystatus"
oid=".1.3.6.1.4.1.674.10892.5.4.1100.50"
```

**Comment by bestsiyue** [comment]
table虚拟表是ok的，非常感谢。
