### ISSUE TITLE
请问如何在数据指标里添加ip字段

### ISSUE THREAD

**Issue by pangpeng** [flashcatcloud/categraf#689]
请问如何在数据指标里添加ip字段:
现在数据
mem_free{ident="aliyun-sh-ops-monitor-1"}
期望数据
mem_free{ident="aliyun-sh-ops-monitor-1", ip="192.168.100.10"}
如果相要添加ip字段如何配置,或者改哪部分代码加上ip的信息.

**Comment by kongfei605** [comment]
https://flashcat.cloud/docs/content/flashcat-monitor/categraf/3-configuration/  用labels

**Comment by pangpeng** [comment]
> https://flashcat.cloud/docs/content/flashcat-monitor/categraf/3-configuration/ 用labels
了解,非常感谢

**Comment by pangpeng** [comment]
> > https://flashcat.cloud/docs/content/flashcat-monitor/categraf/3-configuration/ 用labels
你好, config.toml 已添加
[global.labels]
hostname = "xxx"
ip = "xx"
别的数据指标有hostname,ip字段. 但target_up没有,只有1个ident. 请问target_up怎么也加上标签数据
数据如下所示
target_up{ident="aliyun-sh-ops-monitor-1"}
cpu_usage_idle{cpu="cpu-total", hostname="xxx", ident="aliyun-sh-ops-monitor-1", ip="xx"}

**Comment by kongfei605** [comment]
你用的哪个插件？

**Comment by pangpeng** [comment]
> 你用的哪个插件？
没有用什么插件,就是categraf的config.toml配置加了些全局标签global.labels
别的数据指标都有这个全局标签, target_up没有这俩标签,服务端是n9e服务端

**Comment by pangpeng** [comment]
我尝试删除Prometheus的data目录,和n9e后台删除监控主机对象, target_up指标还是没有添加进全局标签
