### ISSUE TITLE
能否添加在收集指标中去掉某个 label 的功能。

### ISSUE THREAD

**Issue by hulkRfp** [flashcatcloud/categraf#691]
我在使用 http_response 插件监控我的网站时发现，偶然的网络不稳定会导致请求 timeout，此时这条指标的 labels 中就会少了“证书名称”这个标签，这导致在配置监控规则时，聚合查询指标的时候这条不带证书名称标签的记录就成为了脏数据，会导致报警规则被触发。最终我会经常收到这种误报的消息。
而证书名称这个标签我并不需要，所以如果收集指标时能去掉这个标签应该就能解决我的问题了。

**Comment by kongfei605** [comment]
新版本instances下支持relabel能力（放到instances的最下面）， 比如要去除index这个lable ，可以这么写。

[[instances.relabel_configs]]
regex = "index"
action = "labeldrop"

**Comment by hulkRfp** [comment]
测试过了，从 v0.3.31 开始支持了，非常感谢作者支持。

**Comment by hulkRfp** [comment]
在每个 [instances] 下添加：
[[instances.relabel_configs]]
regex = "index"
action = "labeldrop"

再说下，catagraf 牛逼，Nightingale 威武！

**Comment by allenz92** [comment]
> 新版本instances下支持relabel能力（放到instances的最下面）， 比如要去除index这个lable ，可以这么写。
> 
> [[instances.relabel_configs]] regex = "index" action = "labeldrop"

必须要放到instances下吗？有些配置文件里面是没有instances 的

**Comment by UlricQin** [comment]
> > 新版本instances下支持relabel能力（放到instances的最下面）， 比如要去除index这个lable ，可以这么写。
> > [[instances.relabel_configs]] regex = "index" action = "labeldrop"
> 
> 必须要放到instances下吗？有些配置文件里面是没有instances 的

没有 instances 的，就直接放 `[[relabel_configs]]` 应该也可以
