### ISSUE TITLE
Categraf有收集ActiveOpens:主动打开的tcp连接数量和PassiveOpens:被动打开的tcp连接数量的插件吗？

### ISSUE THREAD

**Issue by allenz92** [flashcatcloud/categraf#711]
找了下没找到

**Comment by kongfei605** [comment]
<img width="196" alt="image" src="https://github.com/flashcatcloud/categraf/assets/12164762/0ac23a10-0295-410a-a2b1-b3ef352afb97">
可以到flashcat官网文档里找找。看看netstat插件。

**Comment by kongfei605** [comment]
后续找了下没找到，可以反馈下，在哪里没找到。看看我是否有权限，补充到大家好找的地方。

**Comment by allenz92** [comment]
https://gist.github.com/wych42/5146bb0acd0aa05adf076a449d795890#%E7%BD%91%E7%BB%9C 这个页面有写，从/proc/net/snmp获取的；
netstat插件是从/proc/net/netstat获取的数据，是有差别的。

**Comment by kongfei605** [comment]
> https://gist.github.com/wych42/5146bb0acd0aa05adf076a449d795890#%E7%BD%91%E7%BB%9C 这个页面有写，从/proc/net/snmp获取的； netstat插件是从/proc/net/netstat获取的数据，是有差别的。

netstat是从/proc/net/sockstat 统计的，而且会有udp的指标统计。 另外，你要区分主动和被动连接数，是在什么场景下，能举个例子吗？
