### ISSUE TITLE
categraf与n9e edge经常timeout

### ISSUE THREAD

**Issue by bestsiyue** [flashcatcloud/categraf#712]
### Relevant config.toml

```toml
无
```

### Logs from categraf

```text
2023/11/15 09:34:42 heartbeat.go:148: E! failed to do heartbeat: Post "http://10.150.249.24:19000/v1/n9e/edge/heartbeat": net/http: timeout awaiting response headers (Client.Timeout exceeded while awaiting headers)
```

### System info

categraf v0.3.37, n9e-edge v6.2.0

### Steps to reproduce

n9e做了下沉部署，n9e-edge和分支的categraf部署在一台设备上，categraf日志里经常出现心跳timeout。

2023/11/15 09:48:23 heartbeat.go:148: E! failed to do heartbeat: Post "http://10.150.249.24:19000/v1/n9e/edge/heartbeat": net/http: timeout awaiting response headers (Client.Timeout exceeded while awaiting headers)

### Expected behavior

无

### Actual behavior

无

**Comment by kongfei605** [comment]
可以先检查一下categraf到edge的网络状况, 网络状况不好控制那就调大超时时间

**Comment by kongfei605** [comment]
> 您好，categraf 和edge在同一台设备上。

同一台设备上，用localhost 127.0.0.1

**Comment by kongfei605** [comment]
用localhost 和 127.0.0.1 测试结果如何？

**Comment by bestsiyue** [comment]
hi，配置文件已改为127.0.0.1，日志里依然出现timeout

![image](https://github.com/flashcatcloud/categraf/assets/50395020/3fdcb61d-2ac9-44b7-a1c9-bac932bb663e)


![image](https://github.com/flashcatcloud/categraf/assets/50395020/a511519d-a69c-40d5-8aa0-02c385316053)

**Comment by UlricQin** [comment]
如果n9e-edge没有异常日志，大概率就是环境问题，可能的原因比如firewalld配置不合理，iptables配置不合理等等，当然也可能是其他原因，摸不到环境无法判断。建议更换个机器测试

**Comment by bestsiyue** [comment]
我停用了firewalld服务，categraf日志出现了IPVS services服务错误。
![image](https://github.com/flashcatcloud/categraf/assets/50395020/ecfbfb9a-05f0-4b4c-936f-94645dcd72eb)

**Comment by bestsiyue** [comment]
停用firewalld只有timeout依然存在。

**Comment by UlricQin** [comment]
你的writer也要设置为127.0.0.1，另外还要检查iptables和selinux，如果还搞不定，建议更换机器测试，或者找你们公司擅长网络的同事给看看

**Comment by bestsiyue** [comment]
经测试，不是防火墙和selinux的问题。
像是n9e-edge的writers接口被categraf打死了，我的categraf下挂了1000多台设备的snmp指标监控，减少设备数量之后就没有timeout错误出现了。

**Comment by bestsiyue** [comment]
@kongfei605

**Comment by kongfei605** [comment]
检查下fd的限制

**Comment by bestsiyue** [comment]
@kongfei605  
kernel: neighbour: arp_cache: neighbor table overflow!

系统日志告警arp缓存表溢出，使用sysctl -w net.ipv4.neigh.default.gc_thresh3=2048调整缓存表大小就不timeout了。

**Comment by kongfei605** [comment]
感谢反馈~
