### ISSUE TITLE
Categraf插件通过SNMP协议获取网络设备指标，是否可以支持导入mib库，然后采集指标

### ISSUE THREAD

**Issue by robotneo** [flashcatcloud/categraf#714]
**What would you like to be added**:
SNMP协议采集网络设备指标，支持通过批量导入MIB库，然后生成对应OID库指标
**Why is this needed**:
目前好像只支持把mib文件导入到系统snmpd目录中，然后编辑配置文件，mibs +MIB名称。这样稍微有些麻烦，能否通过指定的文件夹上传mib文件目录，比如在Categraf的snnmp配置目录下包含mibs文件，个人使用者直接上传私有mib库到这个目录，然后其他不用管，程序自动实现加载，用户直接可以关注指标即可。
**Describe the solution you'd like**
类似snmp exporter的配置生成器mibs目录，用户上传mib库即可，然后snmp的目录路径，环境变量即可。
**Additional context**
1、新建mibs目录，这个目录是用户上传的mib库目录
2、用户直接关注配置文件的指标配置即可，其他程序自动实现
3、我能想到的就是，程序把mibs目录中的mib库自动扫码拷贝到 /usr/share/snmp/mibs （centos系统）
4、自动编辑这个文件 /etc/snmp/snmp.conf （centos系统）批量添加：mibs +mib库文件名
5、重启snmpd  systemctl restart snmpd.service

**Comment by kongfei605** [comment]
对，现在是需要导入到系统snmpd目录中，因为用的也是netsnmp， 后续会做实现，配置中预留的path项。

**Comment by robotneo** [comment]
好的，等待功能实现，目前我就用脚本批量实现一下，私有mib库（100+）很多的情况下  这个动作很繁琐

**Comment by kongfei605** [comment]
从v0.3.44-pre 已经开始支持load mib了

**Comment by kongfei605** [comment]
v0.3.45 支持gosmi + path 配置mib路径（也要包含系统的mib路径，这里面包含了基础的标准mib库）

**Comment by robotneo** [comment]
配置中如何配置，比如我有一批mib文件 放在/opt/mibs/目录下 categraf配置文件如何配置只加载这个配置目录下的mib。

**Comment by kongfei605** [comment]
> 如：/opt/h3c/mibs目录下 配置如下 path = ["/opt/h3c/mibs"] translator = "gosmi"
path = ["标准mib目录", "/opt/h3c/mibs"]
translator = "gosmi"

缺少标准mib 会导致一些解析失败，除非你把标准mib也放到了 /opt/h3c/mibs

**Comment by robotneo** [comment]
path = ["/opt/h3c/mibs"]
translator = "netsnmp"

是否支持设置path？还是需要通过环境变量导入设置呢？环境变量导入设置如何操作？

**Comment by robotneo** [comment]
已经测试出来了 export MIBDIRS="/opt/h3c/mibs" 谢谢

**Comment by kongfei605** [comment]
> path = ["/opt/h3c/mibs"] translator = "netsnmp"
> 
> 是否支持设置path？还是需要通过环境变量导入设置呢？环境变量导入设置如何操作？

支持path
