### ISSUE TITLE
建议针对Windows进行优化

### ISSUE THREAD

**Issue by samgang** [flashcatcloud/categraf#721]
现版本对Windows采集出现大量错误日志
'''
netstat_summary is only supported on linux
'''

**Comment by samgang** [comment]
经查阅其他 Issues 和 https://flashcat.cloud/docs/content/flashcat-monitor/categraf/plugin/netstat/ ，对其关闭，之后发现 Windows 机器出现了 `netstat_tcp_*` 相关指标。填充了  **Windows Host by Categraf**  仪表盘里 tcp 的数据。



但是其他无法获取指标的无法关闭

```
E! input: local.amd_rocm_smi not supported
E! input: local.arp_packet not supported
I! input: local.greenplum started
E! input: local.ipvs not supported
E! input: local.jolokia_agent_kafka not supported
E! input: local.jolokia_agent_misc not supported
E! input: local.kernel not supported
E! input: local.kernel_vmstat not supported
E! input: local.linux_sysctl_fs not supported
```

建议在 Windows 安装包下对不支持的进行默认关闭。

**Comment by kongfei605** [comment]
> 经查阅其他 Issues 和 https://flashcat.cloud/docs/content/flashcat-monitor/categraf/plugin/netstat/ ，对其关闭，之后发现 Windows 机器出现了 `netstat_tcp_*` 相关指标。填充了 **Windows Host by Categraf** 仪表盘里 tcp 的数据。
> 
> 但是其他无法获取指标的无法关闭
> 
> ```
> E! input: local.amd_rocm_smi not supported
> E! input: local.arp_packet not supported
> I! input: local.greenplum started
> E! input: local.ipvs not supported
> E! input: local.jolokia_agent_kafka not supported
> E! input: local.jolokia_agent_misc not supported
> E! input: local.kernel not supported
> E! input: local.kernel_vmstat not supported
> E! input: local.linux_sysctl_fs not supported
> ```
> 
> 建议在 Windows 安装包下对不支持的进行默认关闭。

不是这么设计的。用哪些插件就开哪些插件，conf目录放了很多插件是给小白留的。不用的插件放到里面还不让打个日志告诉你一声？而且这个只是启动时候打印一次。
