### ISSUE TITLE
prometheus wal目录数据不会自动删除

### ISSUE THREAD

**Issue by 46797536** [flashcatcloud/categraf#726]
![1701768387283](https://github.com/flashcatcloud/categraf/assets/46241382/ec6586ba-6254-42c0-839f-1c66dd58a662)
![image](https://github.com/flashcatcloud/categraf/assets/46241382/dbddabd9-754c-4823-a5c8-33492078bba6)

这个目录下的数据会被一直保存，有哪个参数设置可以定时清理

**Comment by kongfei605** [comment]
是设置了 wal_min_duration 没生效吗？ ./categraf --version 看看版本信息

**Comment by 46797536** [comment]
版本是v0.3.37
wal_min_duration 这个值没设置默认注释掉的

**Comment by kongfei605** [comment]
v0.3.46 将清理参数暴露出来了，可以配置了
