### ISSUE TITLE
InputProvider如何使用？

### ISSUE THREAD

**Issue by robotneo** [flashcatcloud/categraf#732]
InputProvider 我应该如何正确使用？比如 input.snmp文件夹默认读取snmp.toml 但是想分开写 snmp01.toml snmp02.toml如何实现？配置文件泛读取。

categraf的读取插件的多个配置文件如何写啊？相当于我不同类型的设备读取不同的采集模板

**Comment by kongfei605** [comment]
保证[[instances]]之上的配置不重复即可

**Comment by kongfei605** [comment]
snmp01.toml 
```[[instances]]
xxxxx
````

snmp02.toml
```
[[instances]]
xxxxxxx
````

**Comment by robotneo** [comment]
我已经摸索出来，感谢，还有个问题，默认解析mib文件的后端是使用netsnmp吧，是否支持gosmi？

**Comment by kongfei605** [comment]
现在只支持netsnmp

**Comment by robotneo** [comment]
好的，我刚刚想把其中一个索引的table中的某个指标插入到另外一个table（和前的表索引不一致）中，发现无法做到？是否可以做到不同索引表连接呢？

**Comment by kongfei605** [comment]
支持，但是这块中文文档还没写全。这个插件是从telegraf fork并做了增强，基础功能可以参考telegraf的用法

**Comment by robotneo** [comment]
好的 感谢支持 我去研究一下 后续以实际案例贡献文档

**Comment by robotneo** [comment]
没有成功：
secondary_index_table = true
secondary_index_use = true
secondary_outer_join = true

这三个参数支持吗？

**Comment by kongfei605** [comment]
支持的

> 没有成功： secondary_index_table = true secondary_index_use = true secondary_outer_join = true
> 
> 这三个参数支持吗？

**Comment by kongfei605** [comment]
v0.3.45支持gosmi +path
