### ISSUE TITLE
switch_legacy监控交换机聚合端口后添加95值线

### ISSUE THREAD

**Issue by fanohn** [flashcatcloud/categraf#746]
使用switch_legacy插件添加交换机聚合端口后使用quantile添加95计费值失败，如何配置可以像cacti一样可以显示95值并在流量图上显示95值线，辛苦解答下

**Comment by kongfei605** [comment]
编辑图标可以添加分位值线

**Comment by fanohn** [comment]
> 编辑图表可以添加分位值线

![fa159a509de73b5e63f470397a812eb](https://github.com/flashcatcloud/categraf/assets/154949118/ca55f3d8-d0b1-4f5d-92ca-0c1dcde6ce13)
编辑哪个选项，辛苦您指导下

**Comment by UlricQin** [comment]
categraf 只是采集器，没法画图。采集了数据进入时序库之后则可以通过可视化工具画图，比如 Nightingale、Grafana，我确认 Nightingale 不支持画 95 分位的线，你可以看看 Grafana 是否支持

**Comment by fanohn** [comment]
> categraf 只是采集器，没法画图。采集了数据进入时序库之后则可以通过可视化工具画图，比如 Nightingale、Grafana，我确认 Nightingale 不支持画 95 分位的线，你可以看看 Grafana 是否支持

十分感谢您的解答。
