### ISSUE TITLE
监控指定文件目录文件是否存在

### ISSUE THREAD

**Issue by Merbeleue** [flashcatcloud/categraf#747]
您好，能不能监控指定目录下指定文件是否存在，如果不存在从而发出告警？

**Comment by kongfei605** [comment]
exec插件支持自定义脚本 ，脚本中实现判断文件存在的逻辑即可 https://flashcat.cloud/docs/content/flashcat-monitor/categraf/plugin/exec/

**Comment by tanxiao1990** [comment]
https://github.com/flashcatcloud/categraf/tree/main/inputs/filecount    这个插件就是监控此指标的   包括文件数量  文件大小  最后修改的时间戳  均可以监控

**Comment by Merbeleue** [comment]
> exec插件支持自定义脚本 ，脚本中实现判断文件存在的逻辑即可 https://flashcat.cloud/docs/content/flashcat-monitor/categraf/plugin/exec/

您好，我脚本判断后，输出到什么地方与告警结合呢？

**Comment by kongfei605** [comment]
如果是不知道exec插件的用法，看我发的文档链接。
如果是问时序数据存储： categraf 只是一个采集端，采集了指标，可以传给nightingale vm prometheus 都行，告警用nightingale 、alert-manager等都可以，找一个自己喜欢的就行。

**Comment by kongfei605** [comment]
filecount插件 
node expoter也集成到categraf（v0.3.49开始） 中了， 可以配置file collector 

```
--collector.file.notifylist=”etc/passwd,/etc/shadow“ 
```
