### ISSUE TITLE
inputs.nvidia_smi中执行smi命令超时时间可配置

### ISSUE THREAD

**Issue by devtjun** [flashcatcloud/categraf#759]
**What would you like to be added**: 
nvidia-smi命令超时时间可配置

**Why is this needed**: 
由于gpu卡通常使用节能模式以延长GPU使用寿命，闲置后再使用nvidia-smi命令会重新初始化gpu卡再执行命令，这样导致命令执行结果会延迟，查看源码发现执行命令时硬编码写的5秒超时时间，最终导致无法正常采集GPU信息

**Describe the solution you'd like**
期望执行采集命令的超时时间可配置

**Additional context**

**Comment by xmh1011** [comment]
fixed by #779 . You can set query timeout in config file `conf/input.nvidia_smi/nvidia_smi.toml`.

**Comment by devtjun** [comment]
> @devtjun fixed by #779 . You can set query timeout in config file `conf/input.nvidia_smi/nvidia_smi.toml`.

thanks
