### ISSUE TITLE
windows server2003 上无法启动

### ISSUE THREAD

**Issue by lostvip-com** [flashcatcloud/categraf#775]
### Relevant config.toml

```toml
windows server2003 上无法启动

D:\1-robvi\categraf-v0.3.47-windows-amd64>categraf.exe --install
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall()
        /opt/hostedtoolcache/go/1.21.5/x64/src/runtime/sys_windows_amd64.s:65 +0
x75 fp=0x22fca0 sp=0x22fc80 pc=0x474bf5
rax     0x0
rbx     0x88d43a0
rcx     0x8938240
rdi     0x7fffffdd000
rsi     0x22fea0
rbp     0x22fde0
rsp     0x22fc78
r8      0x0
r9      0x22fee0
r10     0x89084d8
r11     0x21
r12     0x22fec0
r13     0x1
r14     0x88d36c0
r15     0x0
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b

D:\1-robvi\categraf-v0.3.47-windows-amd64>pause
请按任意键继续. . .
```

### Logs from categraf

```text
D:\1-robvi\categraf-v0.3.47-windows-amd64>categraf.exe --install
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall()
        /opt/hostedtoolcache/go/1.21.5/x64/src/runtime/sys_windows_amd64.s:65 +0
x75 fp=0x22fca0 sp=0x22fc80 pc=0x474bf5
rax     0x0
rbx     0x88d43a0
rcx     0x8938240
rdi     0x7fffffdd000
rsi     0x22fea0
rbp     0x22fde0
rsp     0x22fc78
r8      0x0
r9      0x22fee0
r10     0x89084d8
r11     0x21
r12     0x22fec0
r13     0x1
r14     0x88d36c0
r15     0x0
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b

D:\1-robvi\categraf-v0.3.47-windows-amd64>pause
请按任意键继续. . .
```

### System info

windows server 2003

### Steps to reproduce

D:\1-robvi\categraf-v0.3.47-windows-amd64>categraf.exe --install
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall()
        /opt/hostedtoolcache/go/1.21.5/x64/src/runtime/sys_windows_amd64.s:65 +0
x75 fp=0x22fca0 sp=0x22fc80 pc=0x474bf5
rax     0x0
rbx     0x88d43a0
rcx     0x8938240
rdi     0x7fffffdd000
rsi     0x22fea0
rbp     0x22fde0
rsp     0x22fc78
r8      0x0
r9      0x22fee0
r10     0x89084d8
r11     0x21
r12     0x22fec0
r13     0x1
r14     0x88d36c0
r15     0x0
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b

D:\1-robvi\categraf-v0.3.47-windows-amd64>pause
请按任意键继续. . .

### Expected behavior

D:\1-robvi\categraf-v0.3.47-windows-amd64>categraf.exe --install
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall()
        /opt/hostedtoolcache/go/1.21.5/x64/src/runtime/sys_windows_amd64.s:65 +0
x75 fp=0x22fca0 sp=0x22fc80 pc=0x474bf5
rax     0x0
rbx     0x88d43a0
rcx     0x8938240
rdi     0x7fffffdd000
rsi     0x22fea0
rbp     0x22fde0
rsp     0x22fc78
r8      0x0
r9      0x22fee0
r10     0x89084d8
r11     0x21
r12     0x22fec0
r13     0x1
r14     0x88d36c0
r15     0x0
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b

D:\1-robvi\categraf-v0.3.47-windows-amd64>pause
请按任意键继续. . .

### Actual behavior

D:\1-robvi\categraf-v0.3.47-windows-amd64>categraf.exe --install
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall()
        /opt/hostedtoolcache/go/1.21.5/x64/src/runtime/sys_windows_amd64.s:65 +0
x75 fp=0x22fca0 sp=0x22fc80 pc=0x474bf5
rax     0x0
rbx     0x88d43a0
rcx     0x8938240
rdi     0x7fffffdd000
rsi     0x22fea0
rbp     0x22fde0
rsp     0x22fc78
r8      0x0
r9      0x22fee0
r10     0x89084d8
r11     0x21
r12     0x22fec0
r13     0x1
r14     0x88d36c0
r15     0x0
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b

D:\1-robvi\categraf-v0.3.47-windows-amd64>pause
请按任意键继续. . .

### Additional info

D:\1-robvi\categraf-v0.3.47-windows-amd64>categraf.exe --install
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall()
        /opt/hostedtoolcache/go/1.21.5/x64/src/runtime/sys_windows_amd64.s:65 +0
x75 fp=0x22fca0 sp=0x22fc80 pc=0x474bf5
rax     0x0
rbx     0x88d43a0
rcx     0x8938240
rdi     0x7fffffdd000
rsi     0x22fea0
rbp     0x22fde0
rsp     0x22fc78
r8      0x0
r9      0x22fee0
r10     0x89084d8
r11     0x21
r12     0x22fec0
r13     0x1
r14     0x88d36c0
r15     0x0
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b

D:\1-robvi\categraf-v0.3.47-windows-amd64>pause
请按任意键继续. . .

**Comment by UlricQin** [comment]
2003 版本太低了，Categraf 不支持

**Comment by lostvip-com** [comment]
自己编译了一个版本可以了
