### ISSUE TITLE
把mtail的能力内置集成进来

### ISSUE THREAD

**Issue by UlricQin** [flashcatcloud/categraf#79]
和metrics-agent、logs-agent、trace-agent同级别的存在，支持从日志中提取metrics，直接转发给后端时序库，省的再去部署mtail了

**Comment by ice-gzz** [comment]
请问  logs.toml 提取日志中的metrics 关于这个[[logs.Processing_rules]]有没有样例可以参考的

**Comment by kongfei605** [comment]
1 exclude_at_match
    type = "exclude_at_match"
    name = "exclude_xxx_users"
    pattern="\w+@flashcat.cloud"
表示日志中匹配到@flashcat.cloud 的行 不发送

2 include_at_match
    type = "include_at_match"
    name = "include_demo"
    pattern="^2022*"
表示日志中匹配到2022开头的行 才发送
3 
    type = "mask_sequences“
    name = "mask_phone_number"
    replace_placeholder = "[****]
    pattern="186\\d{8}"
表示手机的后8位会被[****] 代替

**Comment by kongfei605** [comment]
mtail 已经集成 说明见 https://flashcat.cloud/blog/log-monitoring-mtail/
