### ISSUE TITLE
Windows Server 2008 R2 启动报错

### ISSUE THREAD

**Issue by JUNQINGV587** [flashcatcloud/categraf#810]
### Relevant config.toml

```toml
报错信息：
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall()
        /opt/hostedtoolcache/go/1.21.7/x64/src/runtime/sys_windows_amd64.s:65 +0x75 fp=0x22fca0 sp=0x22fc80 pc=0x474e35
rax     0x0
rbx     0x89a9300
rcx     0x8a0d1e0
rdi     0x7fffffde000
rsi     0x22fea0
rbp     0x22fde0
rsp     0x22fc78
r8      0x0
r9      0x22fee0
r10     0x89dd438
r11     0x21
r12     0x22fec0
r13     0x1
r14     0x89a8620
r15     0x0
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0
```

### Logs from categraf

```text
启动失败，日志都来不及生成
```

### System info

Windows Server 2008 R2

### Steps to reproduce

Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall()
        /opt/hostedtoolcache/go/1.21.7/x64/src/runtime/sys_windows_amd64.s:65 +0x75 fp=0x22fca0 sp=0x22fc80 pc=0x474e35
rax     0x0
rbx     0x89a9300
rcx     0x8a0d1e0
rdi     0x7fffffde000
rsi     0x22fea0
rbp     0x22fde0
rsp     0x22fc78
r8      0x0
r9      0x22fee0
r10     0x89dd438
r11     0x21
r12     0x22fec0
r13     0x1
r14     0x89a8620
r15     0x0
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

### Expected behavior

Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall()
        /opt/hostedtoolcache/go/1.21.7/x64/src/runtime/sys_windows_amd64.s:65 +0x75 fp=0x22fca0 sp=0x22fc80 pc=0x474e35
rax     0x0
rbx     0x89a9300
rcx     0x8a0d1e0
rdi     0x7fffffde000
rsi     0x22fea0
rbp     0x22fde0
rsp     0x22fc78
r8      0x0
r9      0x22fee0
r10     0x89dd438
r11     0x21
r12     0x22fec0
r13     0x1
r14     0x89a8620
r15     0x0
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

### Actual behavior

Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall()
        /opt/hostedtoolcache/go/1.21.7/x64/src/runtime/sys_windows_amd64.s:65 +0x75 fp=0x22fca0 sp=0x22fc80 pc=0x474e35
rax     0x0
rbx     0x89a9300
rcx     0x8a0d1e0
rdi     0x7fffffde000
rsi     0x22fea0
rbp     0x22fde0
rsp     0x22fc78
r8      0x0
r9      0x22fee0
r10     0x89dd438
r11     0x21
r12     0x22fec0
r13     0x1
r14     0x89a8620
r15     0x0
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

**Comment by kongfei605** [comment]
升级了golang版本，windows server 2008 不支持了

**Comment by kongfei605** [comment]
https://answer.flashcat.cloud/questions/10010000000004560
