### ISSUE TITLE
categraf web端口 9100 推送metrics报错

### ISSUE THREAD

**Issue by worker24h** [flashcatcloud/categraf#818]
### Relevant config.toml

```toml
默认配置
```

### Logs from categraf

```text
没有异常日志
```

### System info

v0.3.47-dfeedea000e8a147eeddbb893610e0c40d4fcc50

### Steps to reproduce

curl脚本
```bash 
#!/bin/bash

url="http://localhost:9100/api/push/remotewrite" # Categraf API URL
metrics='my_metric{label="value"} 42'   # 要发送的指标数据

response=$(curl -X POST \
    --data-binary "$metrics" \
    $url)
echo "Response from Prometheus server:"
echo "$response"
```

### Expected behavior

数据

### Actual behavior

返回：snappy: corrupt input

**Comment by worker24h** [comment]
categraf不支持 主动写入吗？

**Comment by kongfei605** [comment]
支持. 格式不对，按照格式来 。categraf跟n9e的数据格式是一样的 https://flashcat.cloud/docs/content/flashcat-monitor/nightingale-v6/api/push/

**Comment by worker24h** [comment]
> 支持. 格式不对，按照格式来 。categraf跟n9e的数据格式是一样的 https://flashcat.cloud/docs/content/flashcat-monitor/nightingale-v6/api/push/

嗯已经通过代码分析出来了
