### ISSUE TITLE
input.snmp是否可以更改不同监控项[[instances.table.field]] 的采集频率？

### ISSUE THREAD

**Issue by zhangchi2217** [flashcatcloud/categraf#824]
[[instances.table]] 这类walk方式只需要几小时遍历一下，
[[instances.table.field]] 这类指标也需要分类采集，是否可以配置不同采集项的采集频率？

**Comment by kongfei605** [comment]
设置采集周期目前只支持到instance级别。 
可以将不同周期的field分别放到两个instance.table中，instance.table 支持虚拟表（不设置oid就是虚拟表）

**Comment by zhangchi2217** [comment]
> 设置采集周期目前只支持到instance级别。 可以将不同周期的field分别放到两个instance.table中，instance.table 支持虚拟表（不设置oid就是虚拟表）

是采用这样的方式吗？


[[instances.table]]
oid = "oid"
name = "name"
index_as_tag = true
filters = ["A:hwEntityFanReg:1"]
filters_expression = "A"
interval_time = 3

[[instances.table.filed]]
...

[[instances.table]]
name = "name"
index_as_tag = true
filters = ["A:hwEntityFanReg:1"]
filters_expression = "A"
interval_time = 10

[[instances.table.filed]]
...

**Comment by kongfei605** [comment]
[[instances]]
interval_times=3
...
[[instances.table]]
oid = "oid"
name = "name"
index_as_tag = true
filters = ["A:hwEntityFanReg:1"]
filters_expression = "A"


[[instances.table.filed]]
...



[[instances]]
interval_times=10
...
[[instances.table]]
name = "name"
index_as_tag = true
filters = ["A:hwEntityFanReg:1"]
filters_expression = "A"


[[instances.table.filed]]

**Comment by zhangchi2217** [comment]
> [[instances]] interval_times=3 ... [[instances.table]] oid = "oid" name = "name" index_as_tag = true filters = ["A:hwEntityFanReg:1"] filters_expression = "A"
> 
> [[instances.table.filed]] ...
> 
> [[instances]] interval_times=10 ... [[instances.table]] name = "name" index_as_tag = true filters = ["A:hwEntityFanReg:1"] filters_expression = "A"
> 
> [[instances.table.filed]]

感谢，那这样filters里的判断条件指标hwEntityFanReg就需要在每个instances里重复写了是吧？

**Comment by zhangchi2217** [comment]
> [[instances.table]]

这样的写法agents以及snmp的配置都要重复写一遍吗。。。？

**Comment by kongfei605** [comment]
instances 级别的内容都需要重复写一遍。
