### ISSUE TITLE
支持python flask框架项目服务监控

### ISSUE THREAD

**Issue by nondevops** [flashcatcloud/categraf#827]
**What would you like to be added**:
支持python flask框架项目服务监控

**Why is this needed**:
python作为TOP10主流编程语言，当前无法探知python语言在各个业务项目的运行健康状态。Java有类似micrometer依赖可以解决。但python语言没有类似的集成依赖库。一旦接入后，将更加全面了解项目的性能问题，更能从监控层面定位到更多的业务问题。同时也继续补齐categraf在语言构建系的空白（用inputs.prometheus实现JVM监控）

**Describe the solution you'd like**
采集最常用的监控指标：
RED(速率、错误率、延迟)、进程消耗、文件句柄、GC、进程内存消耗、CPU使用率、核心数、版本

**Additional context**

**Comment by kongfei605** [comment]
这个场景可以直接用procstat插件采集
