### ISSUE TITLE
通过input.snmp采集交换机数据，会大大提高设备cpu的使用率

### ISSUE THREAD

**Issue by zhangchi2217** [flashcatcloud/categraf#831]
应该是由于interval无法灵活定义导致很多采集频率大的指标也要缩短；
例如
1、[[instances.table]]需要根据interval重复获取指标index，
2、[[instances.field]]无法单独定义interval，若通过多个[[instances]]来区分interval，那么[[instances.table]]也需要多个了，这样是不是也会加大cpu压力？
不知道此类场景是否有建议的解决方法？

**Comment by kongfei605** [comment]
拆分多个insance，两个instance中的table用虚拟表，不设置oid。 table.field  不重叠怎么会增大cpu压力？

**Comment by zhangchi2217** [comment]
> 拆分多个insance，两个instance中的table用虚拟表，不设置oid。 table.field 不重叠怎么会增大cpu压力？

例如interface模块，interval有区分的需求，目前是通过这种方式进行筛选
[[instances]]
interval_times=4

# 接口
[[instances.table]]
oid = "IF-MIB::ifTable"
name = "interface"
index_as_tag = true
filters = ["A:ifDescr:^(10GE*|GE*|Eth-Trunk*)"]
filters_expression = "A"

# 描述
[[instances.table.field]]
oid = "IF-MIB::ifDescr"
name = "ifDescr"
is_tag = true

[[instances.table.field]]
...

如果下面的field需要更长的采集间隔，空table通过什么方式可以继承接口index呢，name吗？可否给个书写案例，感谢
[[instances]]
interval_times=10

[[instances.table]]
？

[[instances.table.field]]
oid = "IF-MIB::ifAdminStatus"
name = "ifAdminStatus"
is_tag = true

**Comment by kongfei605** [comment]
下面的table这么写就行
[[instances.table]]
name = "interface"
index_as_tag = true
