### ISSUE TITLE
Heartbeat 连接https n9e日志报错

### ISSUE THREAD

**Issue by taoyang987** [flashcatcloud/categraf#838]
### Relevant config.toml

```toml
1
```

### Logs from categraf

```text
2024/03/19 15:48:13 heartbeat.go:175: E! failed to do heartbeat: Post "https://n9e.hzguode.com/v1/n9e/heartbeat": tls: failed to verify certificate: x509: certificate relies on legacy Common Name field, use SANs instead
```

### System info

0.3.55

### Steps to reproduce

1. 参考issues:https://github.com/flashcatcloud/categraf/issues/653
2. 根据文章https://cloud.tencent.com/developer/article/1160294生成的自签名证书:
3. writer配置https,然后再设置insecure_skip_verify = true,正常上传数据
4. 但是heatbeat配置文件里默认没有insecure_skip_verify = true,无论是否添加上该项,都会提示.
2024/03/19 15:48:13 heartbeat.go:175: E! failed to do heartbeat: Post "https://n9e.hzguode.com/v1/n9e/heartbeat": tls: failed to verify certificate: x509: certificate relies on legacy Common Name field, use SANs instead
不断重复打印该日志.
但是服务端机器列表里收到心跳了
![image](https://github.com/flashcatcloud/categraf/assets/872386/86c7b13a-6829-425a-968a-f0c7ab1a3146)

6.
7.
...

### Expected behavior

1

### Actual behavior

1

**Comment by kongfei605** [comment]
heartbeat 用的是老配置 
```
use_tls=true
insecure_skip_verify = true
```

**Comment by taoyang987** [comment]
可以了,谢谢
