### ISSUE TITLE
filters不起作用，多个instances共用1个instance table

### ISSUE THREAD

**Issue by zhangchi2217** [flashcatcloud/categraf#841]
问题update

**Comment by zhangchi2217** [comment]
采集周期30s
[[instances]]
interval_times = 2

agents = [
    "udp://172.20.189.4:161",
    "udp://172.20.189.91:161",
]

timeout = "5s"
version = 2
community = "111"
agent_host_tag = "ip"
retries = 3
max_repetitions = 50

[[instances.field]]
oid = "SNMPv2-MIB::sysUpTime.0"
name = "sysUpTime"

[[instances.field]]
oid = "HUAWEI-DEVICE-EXT-MIB::hwDeviceEsn.0"
name = "hwDeviceEsn"

[[instances.table]]
name = "entitystate"
index_as_tag = true
filters = ["A:entPhysicalName:^S"]
filters_expression = "A"

[[instances.table.field]]
oid = "ENTITY-MIB::entPhysicalName"
name = "entPhysicalName"

[[instances.table.field]]
...

采集周期60s
[[instances]]
interval_times = 4

agents = [
    "udp://172.20.189.4:161",
    "udp://172.20.189.91:161",
]

timeout = "5s"
version = 2
community = "111"
agent_host_tag = "ip"
retries = 3
max_repetitions = 50

[[instances.table]]
name = "entitystate"
index_as_tag = true
filters = ["A:entPhysicalName:^S"]
filters_expression = "A"

[[instances.table.field]]
oid = "ENTITY-MIB::entPhysicalName"
name = "entPhysicalName"

[[instances.table.field]]
...


按照此方法可以获取到对应的值，但是filters要重复过滤且被过滤的内容也要重复获取，是否可以简化，[[instances.table]]一次获取，多次使用？

**Comment by kongfei605** [comment]
filters必须配置到instance.table下，当前的设计，不支持两个instance 共享信息

**Comment by zhangchi2217** [comment]
> filters必须配置到instance.table下，当前的设计，不支持两个instance 共享信息

get～
