### ISSUE TITLE
snmp 获取到的内容mapping ,怎么设置默认值，比如我把所有查询的数据全部mapping为1

### ISSUE THREAD

**Issue by jack-zhuhua** [flashcatcloud/categraf#844]
[[processor_enum]]
  metrics = ["*status"]
  [processor_enum.value_mappings]
    up = 1
    down = 0

**Comment by kongfei605** [comment]
这个就是个枚举值，你有up down 两个值，那就 up=1 down=1 。 你有a /b /c  ，那就 a=1 b=1 c=1
