### ISSUE TITLE
支持resin指标采集吗？

### ISSUE THREAD

**Issue by W-Jie** [flashcatcloud/categraf#845]
**What would you like to be added**:

**Why is this needed**:
支持resin指标采集吗？
**Describe the solution you'd like**

**Additional context**

**Comment by kongfei605** [comment]
resin是什么？他本身提供metrics接口吗？

**Comment by W-Jie** [comment]
resin是一个类似tomcat的中间件
这是官网：https://caucho.com/products/resin

本身不提供metrics接口，好像可以通过jolokia agent方式采集，但是这块也不清楚要怎么配置

**Comment by kongfei605** [comment]
可以先按照jolokia的配置尝试下

**Comment by kongfei605** [comment]
https://time.geekbang.org/column/article/628498

**Comment by W-Jie** [comment]
感谢感谢
