### ISSUE TITLE
oracle.go:184: E! failed to query: ORA-01000:

### ISSUE THREAD

**Issue by shawnloong** [flashcatcloud/categraf#849]
### Relevant config.toml

```toml
oracle插件连接池cursors 未正常回收
```

### Logs from categraf

```text
2024/03/22 13:47:49 oracle.go:184: E! failed to query: ORA-00604: error occurred at recursive SQL level 1
ORA-01000: maximum open cursors exceeded
ORA-00604: error occurred at recursive SQL level 1
ORA-01000: maximum open cursors exceeded
ORA-01000: maximum open cursors exceeded
```

### System info

Windows 2012 R2 X64

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

oracle.go:184: E! failed to query: ORA-01000:

### Actual behavior

oracle.go:184: E! failed to query: ORA-01000:

**Comment by kongfei605** [comment]
配置呢？

**Comment by kongfei605** [comment]
版本信息呢？

**Comment by shawnloong** [comment]
> 版本信息呢？


[[instances]]
 address = "192.168.1.1:1521/orcl"
 username = "categraf"
 password = "xxxx"
 is_sys_dba = false
 is_sys_oper = false
 disable_connection_pool = false
 max_open_connections = 20
# # interval = global.interval * interval_times
 interval_times = 1
 debug = true
 labels = { dbname="xxxx" }

操作系统版本
Microsoft Windows Server 2008 R2 Standard
数据库版本
Oracle 11.2.0.1

**Comment by kongfei605** [comment]
categraf的版本？metrics.toml 中做了哪些修改？

**Comment by kongfei605** [comment]
> categraf的版本？metrics.toml 中做了哪些修改？

./categraf --version  直接截个图。

**Comment by shawnloong** [comment]
metrics.toml 新增过小部分sql查询表空间及用户状态，sql优化过基本是耖秒级返回

**Comment by shawnloong** [comment]
版本：[v0.3.47]

**Comment by zhwq1216** [comment]
找到原因了，是oracle11.2.0.4.0 的bug。同一个会话查询dba_tablespace_usage_metrics这个视图多次就会提示ORA-01000: maximum open cursors exceeded错误。

https://stackoverflow.com/questions/27347982/selecting-from-dba-tablespace-usage-metrics-causes-ora-1000?newreg=4cd3e82f938842a5a04d88e68a0aab86
