### ISSUE TITLE
snmp_ 默认指标前缀是否可以关闭？

### ISSUE THREAD

**Issue by robotneo** [flashcatcloud/categraf#853]
snmp_ 是属于默认增加的前缀吗？

测试添加指标前缀参数：
metrics_name_prefix = "snmp_huawei_"

最终结果是：
snmp_huawei_snmp_name* 

是否可以关闭系统自带的snmp_指标前缀，然后我通过自定义指标前缀参数。

最终是想这样的结果：
snmp_huawei_name*

这种情况是代码写死了嘛？

**Comment by kongfei605** [comment]
snmp 插件前缀 snmp 固定，剩下的是你配置中 name 定义的。  
[[instances.field]]
oid="xxx"
name="abc_def" 

那最终指标是snmp_abc_def

**Comment by robotneo** [comment]
那我需要对所有指标加前缀，只有：metrics_name_prefix = "huawei_" 得到的指标就是：huawei_snmp_abc_def

**Comment by kongfei605** [comment]
对，但你这种做法不是最佳实践。设备标识可以加到label中，比如device=“huawei” ，指标统一，大盘 告警规则统一。

**Comment by robotneo** [comment]
嗯嗯 你说的也没错

**Comment by kongfei605** [comment]
每个插件都会附带插件名称作为前缀。 还有一个方案，你可以 
[[instances.field]]
oid="xxx"
name="huawei_abc_def"

不配置metrics_name_prefix 。 这样指标就是snmp_huawei_abc_def 了
