### ISSUE TITLE
用systemctl管理启动不起来

### ISSUE THREAD

**Issue by lxyqwer** [flashcatcloud/categraf#854]
### Relevant config.toml

```toml
默认
```

### Logs from categraf

```text
默认
```

### System info

v0.3.56-0c0e292b6964999048280c5087eb1e3147874d0f

### Steps to reproduce

1. categraf -install
2. systemctl start categraf

### Expected behavior

无

### Actual behavior

[root@xxx categraf]# systemctl  status categraf
● categraf.service - Opensource telemetry collector
   Loaded: loaded (/etc/systemd/system/categraf.service; enabled; vendor preset: disabled)
   Active: inactive (dead)

**3月 27 15:22:58 drerpb systemd[1]: Dependency failed for Opensource telemetry collector.
3月 27 15:22:58 drerpb systemd[1]: Job categraf.service/start failed with result 'dependency'.**

### Additional info

/opt/categraf/categraf "-configs" "/opt/categraf/conf" 启动没问题

**Comment by kongfei605** [comment]
版本呢？
