### ISSUE TITLE
oracle插件的address填写错误时，直接panic导致categraf异常退出

### ISSUE THREAD

**Issue by W-Jie** [flashcatcloud/categraf#861]
运行环境：
categraf v0.3.56, centos 7.5

oralce插件配置信息：
![21165799757_135435959604_BF0C1B0E-F09E-4b84-AC87-B8A85F936927](https://github.com/flashcatcloud/categraf/assets/9733682/fa359670-8708-4565-be4b-a8a42fd4eb81)

报错信息：
![21165799757_135436110100_C652692E-5D8D-4da3-AD9C-9FE4ECAA1427](https://github.com/flashcatcloud/categraf/assets/9733682/bdd8c8a2-c63a-46a0-af32-357aafbecaa3)

代码：
https://github.com/flashcatcloud/categraf/blob/0c0e292b6964999048280c5087eb1e3147874d0f/inputs/oracle/oracle.go#L280

**Comment by kongfei605** [comment]
是的，当前代码是这个逻辑。不过昨天有大牛提了个PR 做了一些修改。下个版本发布后，就是报错，不是panic的逻辑了。

**Comment by W-Jie** [comment]
好的，谢谢！
新版本大概什么时候会发布？

**Comment by kongfei605** [comment]
没有特殊情况，基本每周都会发布一个版本

**Comment by kongfei605** [comment]
https://github.com/flashcatcloud/categraf/releases/tag/v0.3.59
