### ISSUE TITLE
categraf有提供采集的指标汇聚上报的功能吗？

### ISSUE THREAD

**Issue by lvtaococo** [flashcatcloud/categraf#862]
**What would you like to be added**: 
汇聚指标成json，进行统一上报
**Why is this needed**: 
针对不直接对接夜莺的模式，直接上报指标数据到数据库，进行展示的场景
**Describe the solution you'd like** 
希望提供汇聚每次采集指标汇聚的能力，最终以json的形式进行固定频率指标的批次上报。
**Additional context**
汇聚指标功能，汇聚成json，进行统一上报

**Comment by kongfei605** [comment]
没有这个功能。现在是针对prometheus生态的，可以直接写入prometheus  vm n9e等
