### ISSUE TITLE
Categraf 0.3.58 使用 gosmi + path 模式初始化字段出错 netsnmp 正常

### ISSUE THREAD

**Issue by robotneo** [flashcatcloud/categraf#864]
root@alert:/opt/categraf# ./categraf --test --inputs snmp
2024/04/02 10:03:01 main.go:149: I! runner.binarydir: /opt/categraf
2024/04/02 10:03:01 main.go:150: I! runner.hostname: alert
2024/04/02 10:03:01 main.go:151: I! runner.fd_limits: (soft=1048576, hard=1048576)
2024/04/02 10:03:01 main.go:152: I! runner.vm_limits: (soft=unlimited, hard=unlimited)
2024/04/02 10:03:01 provider_manager.go:60: I! use input provider: [local]
2024/04/02 10:03:01 prometheus_agent.go:19: I! prometheus scraping disabled!
2024/04/02 10:03:01 ibex_agent.go:19: I! ibex agent disabled!
2024/04/02 10:03:01 agent.go:38: I! agent starting
Parse module: /opt/categraf/mibs/public/IPSEC-IKEACTION-MIB.mib:44:21: unexpected "20060905'" (expected <extutctime> ...)
2024/04/02 10:03:09 translate.go:84: W! Couldn't load module IPSEC-IKEACTION-MIB.mib: Could not load module at IPSEC-IKEACTION-MIB.mib
2024/04/02 10:03:13 metrics_agent.go:295: E! failed to init input: local.snmp error: initializing table ap ins: initializing field name: translating: cannot make HH3C-DOT11-APMT-MIB::hh3cDot11CurrAPName numeric, please ensure all imported mibs are in the path
2024/04/02 10:03:13 agent.go:46: I! [*agent.MetricsAgent] started
2024/04/02 10:03:13 agent.go:49: I! agent started
^C2024/04/02 10:03:53 main.go:131: I! received signal: interrupt
2024/04/02 10:03:53 agent.go:53: I! agent stopping
2024/04/02 10:03:53 agent.go:61: I! [*agent.MetricsAgent] stopped
2024/04/02 10:03:53 agent.go:64: I! agent stopped
2024/04/02 10:03:53 main.go:144: I! exited

**Comment by kongfei605** [comment]
配置没贴，盲猜，path中不包含标准mib 。这个功能我们商业客户都在用了，功能没问题。再让我猜，就不回复了。

**Comment by robotneo** [comment]
我说下吧，标准mib肯定是包含的，像华三华为提供的mib都是把私有包依赖公共mib包含进去了，（华三提供的RFC1155.smi和RFC1212.smi是不行的，已经通过下载官方公共的mib得到修复）。

上面的问题我给你们找到了，snmp_xx.toml的配置中的有些配置写成 [mib名::指标名]的格式是不行的，非要改成oid格式。这个问题只在gosmi模式中存在，netsnmp模式没有问题，你们可以测试下，我把我的配置也可以贴出来，你测试下。

比如华三的设备，gomsi模式，写出oid是可以的：
# AP别名 hh3cDot11CurrAPName
[[instances.table.field]]
oid = "1.3.6.1.4.1.25506.2.75.2.1.2.1.8"
name = "name"
is_tag = true

写出下面的这个模式是不行的，但是使用 netsnmp 是可以的：
# AP别名 hh3cDot11CurrAPName
[[instances.table.field]]
oid = "HH3C-DOT11-APMT-MIB::hh3cDot11CurrAPName"
name = "name"
is_tag = true

**Comment by robotneo** [comment]
让你费心了，我刚刚测试出来的，你确定下，我猜测应该是gosmi的代码解析出现什么问题了，还是华三提供的mib文件不规范嘛？

**Comment by kongfei605** [comment]
> 我说下吧，标准mib肯定是包含的，像华三华为提供的mib都是把私有包依赖公共mib包含进去了，（华三提供的RFC1155.smi和RFC1212.smi是不行的，已经通过下载官方公共的mib得到修复）。
> 
> 上面的问题我给你们找到了，snmp_xx.toml的配置中的有些配置写成 [mib名::指标名]的格式是不行的，非要改成oid格式。这个问题只在gosmi模式中存在，netsnmp模式没有问题，你们可以测试下，我把我的配置也可以贴出来，你测试下。
> 
> 比如华三的设备，gomsi模式，写出oid是可以的：
> 
> # AP别名 hh3cDot11CurrAPName
> [[instances.table.field]] oid = "1.3.6.1.4.1.25506.2.75.2.1.2.1.8" name = "name" is_tag = true
> 
> 写出下面的这个模式是不行的，但是使用 netsnmp 是可以的：
> 
> # AP别名 hh3cDot11CurrAPName
> [[instances.table.field]] oid = "HH3C-DOT11-APMT-MIB::hh3cDot11CurrAPName" name = "name" is_tag = true

既然这么肯定都包含了,那path肯定不用贴出来了。  用HH3C-DOT11-APMT-MIB::hh3cDot11CurrAPName 这种格式没问题，只要按我说的，标准mib 包含了（比如netsnmp里面那些基础的公共的都在） 就没问题。 或者你自己找个mib依赖分析，看看依赖的mib文件是否包含再你现在path指定的路径中。

**Comment by kongfei605** [comment]
或者这么说，你用netsnmp的时候，是不是netsnmpd本身带了标准mib，然后你再把H3c的mib放到那个/usr/share/snmp/mib/xxxx 下。 然后用gosmi的时候也要包含这两部分mib的路径。或者你把标准mib文件都放到你的H3C目录下，这样path才可以只配置一个路径。

**Comment by robotneo** [comment]
netsnmp和gosmi 我都是指定目录的 不会用到系统默认的目录，如ubuntu系统的 /usr/share/snmp/mib 目录。

**Comment by kongfei605** [comment]
那你要确定，你指定的目录中是否已经包含基础的mib了。搜一下有网站可以分析mib依赖，一查就知道你指定的路径中是否缺少了mib（大概率就是系统默认目录中的mib）

**Comment by robotneo** [comment]
那为啥 netsnmp 可以呢？如果是缺少mib依赖的话

**Comment by kongfei605** [comment]
> 那为啥 netsnmp 可以呢？如果是缺少mib依赖的话

netsnmp 默认就加载/usr/share/xxx   。 你netsnmp怎么禁止不读取默认目录的？

**Comment by robotneo** [comment]
netsnmp 可以引入环境变量 修改默认的 mib 文件读取目录路径啊，如下所示：
Environment="MIBDIRS=/opt/categraf/mibs/public:/opt/categraf/mibs/private" 可以把这个加入你们 categraf.service

或者设置临时环境变量：主要做测试使用 ./categraf --test --inputs snmp
export MIBDIRS="/opt/categraf/mibs/h3c/public:/opt/categraf/mibs/h3c/private"

**Comment by kongfei605** [comment]
你继续按照你的理解做吧，gosmi+path没问题。
