### ISSUE TITLE
categraf 是否可以支持 pushgateway 协议

### ISSUE THREAD

**Issue by JellyTony** [flashcatcloud/categraf#87]
categraf 是否可以支持 pushgateway 协议，这样每台机器的指标先上报到 categraf，然后再由 categraf 上报到 nightingale server

**Comment by UlricQin** [comment]
你们现在是有哪些场景用了pushgateway？

**Comment by JellyTony** [comment]
如果要做业务自定义监控，就需要将业务的指标上报给 nightingale server, 和 夜莺 v4 差不多，v4 之前有个 agent, 框架会上报指标给 agent， 然后 agent 在上报给 nightingale server，用作 v5 上报的话，直接上报给 nightingale server 吗 ？ 还是像 v4 agent 打包再上报给 server

**Comment by UlricQin** [comment]
那你这都不是pushgateway的场景。目前版本来看，业务监控，可以埋prometheus sdk，用Categraf作为sidecar来抓，也可以用statsd的sdk，推给telegraf，telegraf再推给n9e-server。我们后面会在Categraf里支持数据推送的接口，不过得排到1个月之后了
