### ISSUE TITLE
input.snmp 部分指标无法写入VictoriaMetrics

### ISSUE THREAD

**Issue by luweijun1992** [flashcatcloud/categraf#882]
### Relevant config.toml

```toml
# collect interval, unit: second
interval = 60

# Retrieves SNMP values from remote agents
[[instances]]
agents = ["udp://192.168.255.121"]

## Timeout for each request.
timeout = "5s"

## SNMP version; can be 1, 2, or 3.
version = 2

## Path to mib files
#path = ["/etc/categraf/mibs"]
path = ["/opt/categraf/mibs"]
translator = "gosmi"

## SNMP community string.
community = "public"

## Agent host tag
# agent_host_tag = "agent_host"

## Number of retries to attempt.
retries = 3

## The GETBULK max-repetitions parameter.
max_repetitions = 50

## Add fields and tables defining the variables you wish to collect.

# HUAWEI-WLAN-GLOBAL-MIB
[[instances.field]]
oid = ".1.3.6.1.4.1.2011.6.139.12.1.2.1.0" # hwWlanCurJointApNum 当前连接到AC的AP数量的统计。
name = "hwWlanCurJointApNum"
[[instances.field]]
oid = ".1.3.6.1.4.1.2011.6.139.12.1.2.2.0" # hwWlanCurAssocStaNum 基于AC的当前关联总用户数。
name = "hwWlanCurAssocStaNum"
[[instances.field]]
oid = ".1.3.6.1.4.1.2011.6.139.12.1.2.5.0" # hwWlanCurAssoc2gStaNum AC上2.4G用户总数。
name = "hwWlanCurAssoc2gStaNum"
[[instances.field]]
oid = ".1.3.6.1.4.1.2011.6.139.12.1.2.6.0" # hwWlanCurAssoc5gStaNum AC上5G用户总数。
name = "hwWlanCurAssoc5gStaNum"
[[instances.field]]
oid = ".1.3.6.1.4.1.2011.6.139.12.1.2.8.0" # hwWlanGlobalUpSpeed 系统上行速率(上行吞吐量)。单位：Kbps。
name = "hwWlanGlobalUpSpeed"
[[instances.field]]
oid = ".1.3.6.1.4.1.2011.6.139.12.1.2.9.0" # hwWlanGlobalDownSpeed 系统下行速率(下行吞吐量)。单位：Kbps。
name = "hwWlanGlobalDownSpeed"
[[instances.field]]
oid = ".1.3.6.1.4.1.2011.6.139.12.1.5.1.0" # hwWlanApNormalRatio 状态正常（normal或commit）的AP的占比。单位：%
name = "hwWlanApNormalRatio"
[[instances.field]]
oid = ".1.3.6.1.4.1.2011.6.139.12.1.5.6.0" # hwWlanServiceNormalAPCount 状态为normal，standby，committing和download的AP数。
name = "hwWlanServiceNormalAPCount"
[[instances.field]]
oid = ".1.3.6.1.4.1.2011.6.139.12.1.5.7.0" # hwWlanApCount AP总数。
name = "hwWlanApCount"
[[instances.field]]
oid = ".1.3.6.1.4.1.2011.6.139.12.3.2.6.0" # hwWlanStaCurNum 当前无线用户数。
name = "hwWlanStaCurNum"
```

### Logs from categraf

```text
root@debian:/opt/categraf# ./categraf  -debug
2024/04/17 17:28:09 main.go:149: I! runner.binarydir: /opt/categraf
2024/04/17 17:28:09 main.go:150: I! runner.hostname: debian
2024/04/17 17:28:09 main.go:151: I! runner.fd_limits: (soft=1048576, hard=1048576)
2024/04/17 17:28:09 main.go:152: I! runner.vm_limits: (soft=unlimited, hard=unlimited)
2024/04/17 17:28:09 provider_manager.go:60: I! use input provider: [local]
2024/04/17 17:28:09 prometheus_agent.go:19: I! prometheus scraping disabled!
2024/04/17 17:28:09 ibex_agent.go:19: I! ibex agent disabled!
2024/04/17 17:28:09 agent.go:38: I! agent starting
2024/04/17 17:28:24 metrics_agent.go:315: I! input: local.snmp started
2024/04/17 17:28:24 agent.go:46: I! [*agent.MetricsAgent] started
2024/04/17 17:28:24 agent.go:49: I! agent started
2024/04/17 17:28:24 metrics_reader.go:54: D! local.snmp : before gather once
2024/04/17 17:28:25 instances.go:163: agent udp://192.168.255.121 ins: get info for oid .1.3.6.1.4.1.2011.6.139.12.1.5.1.0 error NoSuchInstance
17:28:25 snmp_icmp_up agent_host=192.168.255.121 agent_hostname=debian 1
17:28:25 snmp_up agent_host=192.168.255.121 agent_hostname=debian 1
2024/04/17 17:28:25 metrics_reader.go:60: D! local.snmp : after gather once, duration: 622.392716ms
2024/04/17 17:28:25 writers.go:139: D!, write 2 time series to all writers, cost: 1 ms
2024/04/17 17:29:24 metrics_reader.go:54: D! local.snmp : before gather once
2024/04/17 17:29:25 instances.go:163: agent udp://192.168.255.121 ins: get info for oid .1.3.6.1.4.1.2011.6.139.12.1.5.1.0 error NoSuchInstance
17:29:25 snmp_icmp_up agent_host=192.168.255.121 agent_hostname=debian 1
17:29:25 snmp_up agent_host=192.168.255.121 agent_hostname=debian 1
2024/04/17 17:29:25 metrics_reader.go:60: D! local.snmp : after gather once, duration: 622.978861ms
2024/04/17 17:29:25 writers.go:139: D!, write 2 time series to all writers, cost: 0 ms
```

### System info

Docker 26.0.1

### Steps to reproduce

1. 上述提供的input.snmp下的配置的指标无法写入数据库
2. 并不是所有哦，其他是正常的。
3. 使用snmpwalk oid 是可以正常获取
...

### Expected behavior

需要写入数据库

### Actual behavior

在vmui上查不到对应指标

### Additional info

请问我需要怎么进一步排查

**Comment by luweijun1992** [comment]
更新测试结果：
设备对于上面配置文件中某几个oid不支持的情况。就会导致以上的全部单节点oid都无法写入vm数据库
![630c3cd73d80c56b37747d9593d3055](https://github.com/flashcatcloud/categraf/assets/58923704/eb969275-91cd-433b-a8ed-199566c5220c)

**Comment by kongfei605** [comment]
> 更新测试结果： 设备对于上面配置文件中某几个oid不支持的情况。就会导致以上的全部单节点oid都无法写入vm数据库 ![630c3cd73d80c56b37747d9593d3055](https://private-user-images.githubusercontent.com/58923704/323299477-eb969275-91cd-433b-a8ed-199566c5220c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NzQ2MDQsIm5iZiI6MTcxMzQ3NDMwNCwicGF0aCI6Ii81ODkyMzcwNC8zMjMyOTk0NzctZWI5NjkyNzUtOTFjZC00MzNiLWE4ZWQtMTk5NTY2YzUyMjBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDIxMDUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjYTE2MzNjNTc3NmRkMTdhYzgwZTQ3MTQ2MjE4NTZiYTdlZjdmOGFiMjdkODgyMDI3ZDk5MWI2MjE0ZGNiZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hjq4nhDYAU5CoMy7sjjmbpv5VYebo-ZR6QGBgCehW7Q)

看这个描述可能是个bug ，我来确认下

**Comment by luweijun1992** [comment]
> 可能是

好的，谢谢。是否需要我再提供信息协助处理

**Comment by luweijun1992** [comment]
> > 更新测试结果： 设备对于上面配置文件中某几个oid不支持的情况。就会导致以上的全部单节点oid都无法写入vm数据库 ![630c3cd73d80c56b37747d9593d3055](https://private-user-images.githubusercontent.com/58923704/323299477-eb969275-91cd-433b-a8ed-199566c5220c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NzQ2MDQsIm5iZiI6MTcxMzQ3NDMwNCwicGF0aCI6Ii81ODkyMzcwNC8zMjMyOTk0NzctZWI5NjkyNzUtOTFjZC00MzNiLWE4ZWQtMTk5NTY2YzUyMjBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDIxMDUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjYTE2MzNjNTc3NmRkMTdhYzgwZTQ3MTQ2MjE4NTZiYTdlZjdmOGFiMjdkODgyMDI3ZDk5MWI2MjE0ZGNiZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hjq4nhDYAU5CoMy7sjjmbpv5VYebo-ZR6QGBgCehW7Q)
> 
> 看这个描述可能是个bug ，我来确认下

我使用Telegraf测试是正常的，使用相同的OID
问题出在Categraf

**Comment by luweijun1992** [comment]
@kongfei605 请问这个问题啥时候出版本解决，谢谢。

**Comment by kongfei605** [comment]
问题已修复 https://github.com/flashcatcloud/categraf/pull/906

**Comment by kongfei605** [comment]
可以用v0.3.62 再跑一下

**Comment by luweijun1992** [comment]
> 可以用v0.3.62 再跑一下

应该是正常了
提示变成下面截图
![image](https://github.com/flashcatcloud/categraf/assets/58923704/f157af3b-a201-4138-8342-e0a9e831d003)

**Comment by luweijun1992** [comment]
@kongfei605 请在日志中增加对应agents
比如：
```
2024/04/30 13:46:09 table.go:347: W! {agent} no info for oid .1.3.6.1.4.1.2011.6.139.12.1.3.2.0
2024/04/30 13:46:09 table.go:347: W! 192.168.1.100 no info for oid .1.3.6.1.4.1.2011.6.139.12.1.3.2.0
```

**Comment by kongfei605** [comment]
https://github.com/flashcatcloud/categraf/pull/914
