### ISSUE TITLE
input.snmp 配置文件规范疑问

### ISSUE THREAD

**Issue by luweijun1992** [flashcatcloud/categraf#884]
请问input.snmp 插件配置文件的规范写法。

Categraf snmp 需要导入MIB文件

如下两种配置文件写法
配置1：
```
[[instances.field]]
oid = "RFC1213-MIB::sysUpTime.0"
name = "uptime"
```

配置2：
```
[[instances.field]]
oid = ".1.3.6.1.2.1.1.3.0" # RFC1213-MIB::sysUpTime OID 1.3.6.1.2.1.1.3
name = "uptime"
```

1、请问两种差异是怎么样，且针对性能，请求速度是否有差异。
2、如果采用配置2的写法，直接写的就是OID数字方式而非“节点名称”，请还有必要导入MIB文件吗？

---
是否有更加全面的配置文件模板可以参考的。

**Comment by kongfei605** [comment]
1 配置1 的写法会多一次 snmptranslate，将文本oid转为数字型oid。 这个translate是请求采集端所在机器的snmpd，所以实践下来几乎没什么速度差异
2 配置2 的方式没有必要导入mib文件

**Comment by luweijun1992** [comment]
> 1 配置1 的写法会多一次 snmptranslate，将文本oid转为数字型oid。 这个translate是请求采集端所在机器的snmpd，所以实践下来几乎没什么速度差异 2 配置2 的方式没有必要导入mib文件

好的，谢谢。
另外请问下Table表的配置，如何用数字型OID，而不是使用文本OID。
比如ifTable，那数字型OID应该是多少？
```
[[instances.table]]
oid = "IF-MIB::ifTable"
name = "interface"
```

**Comment by kongfei605** [comment]
google it
