### ISSUE TITLE
通过DCGM做GPU监控提示libdcgm.so not Found

### ISSUE THREAD

**Issue by zhouyewll1981** [flashcatcloud/categraf#886]
服务器版本ubuntu22.04  GPU：2080ti，已经安装驱动（545.29.02）和cuda（12.3）
categraf版本：v0.3.60
插件：input.dcgm
配置文件：
[[instances]]
collectors = "conf/input.dcgm/default-counters.csv"
kubernetes=false
  cpu-devices = "f"
  devices = "f"
  switch-devices = "f"
  configmap-data = "none"
在使用命令./categraf --test inputs dcgm测试的时候提示：
exporter.go:167: libdcgm.so not Found
请问是什么问题？
是有什么组件没有安装吗？

**Comment by kongfei605** [comment]
先find一下 libdcgm.so ，如果能找到，一般是在 /usr/lib/x86_64-linux-gnu/下 
```
find / -name libdcgm.so*
...
/usr/lib/x86_64-linux-gnu/libdcgm.so.6
```
然后 export LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu/:${LD_LIBRARY_PATH}" 
或者修改 /etc/ld.so.conf   追加 /usr/lib/x86_64-linux-gnu/ 并 ldconfig

如果没找到libdcgm.so.x
```
apt-get install -y datacenter-gpu-manage=1:3.3.5
```

**Comment by zhoubingdata** [comment]
datacenter-gpu-manage 下载地址：https://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/

**Comment by kongfei605** [comment]
> apt-get install -y datacenter-gpu-manage=1:3.3.5

少了一个r  ,应该是 =》  ```apt-get install -y datacenter-gpu-manager=1:3.3.5```
