### ISSUE TITLE
发布的版本包期望支持mac m1版本

### ISSUE THREAD

**Issue by wego-xuchang** [flashcatcloud/categraf#890]
xuchang@Xu categraf-v0.3.61-linux-arm64 % sudo ./categraf  --start
Password:
./categraf: ./categraf: cannot execute binary file

无法执行

**Comment by kongfei605** [comment]
git colone  https://github.com/flashcatcloud/categraf  && make build

**Comment by wego-xuchang** [comment]
目前我的把源代码拉下来打包解决此问题，我提这个的意思就是发布包的可以根据makefile中构建不同个os和处理器打包，对使用不同的用户跟我遇到问题一样又不懂go的有希望体验

**Comment by kongfei605** [comment]
主要是针对linux目标客户，可以找台linux测试和体验，mac上有很多插件没办法体验
