### ISSUE TITLE
是否计划支持SSH协议收集Linux 操作系统指标

### ISSUE THREAD

**Issue by wego-xuchang** [flashcatcloud/categraf#892]
通过SSH协议收集Linux 操作系统的通用性能指标 (系统信息、CPU、内存、磁盘、网卡、文件系统、TOP资源进程等) 进行采集监控

**Comment by kongfei605** [comment]
如果目标系统不适合安装categraf，可以找一台适合安装categraf的机器用exec插件+ssh。

**Comment by wego-xuchang** [comment]
针对监控上百台Linux服务器，categraf要收集这些目标Linux服务器的指标，使用exec插件只能收集当前主机的，是否计划支持SSH协议收集多个Linux 操作系统实例的指标

案例：
[[instances]]
address = "127.0.0.1:22"
username = "root"
password = "root"

[[instances.queries]]
mesurement = "linux_mem"
metric_fields = [ "total" ]
timeout = "3s"
request = '''
  free -m
  '''

**Comment by kongfei605** [comment]
不支持哈

**Comment by wego-xuchang** [comment]
请我怎么收集多个目标Linux 操作系统实例的指标呢

**Comment by kongfei605** [comment]
每个实例上部署一个categraf 。通过ssh预计也要调用每个实例上的采集cpu  io 等命令，这个我没试过

**Comment by luoyuLianga** [comment]
> 请问怎么收集多个目标Linux 操作系统实例的指标呢

正常情况下，机器只要部署categraf就会采集OS 指标。想了解下，什么情况下，不支持部署categraf呢？

**Comment by wego-xuchang** [comment]
理由如下：
1、每台机器都部署一个agent或者exporter，对运维来说比较麻烦，需要关注每个节点以及每台机器，在多数据中心情况下持续发布集成或者哪个服务器挂了比较麻烦。
2、categraf 的 all in one 的风格支持ssh协议是对收集器的补充。
3、Windows服务可以通过snmp协议抓取监控指标，目前是支持的，这样方式也能够减少agent或者exporter

**Comment by kongfei605** [comment]
不支持哈，all in one 也要做取舍，也会有变化，现在已经把traces-agent去掉了。

**Comment by luoyuLianga** [comment]
> 理由如下： 1、每台机器都部署一个agent或者exporter，对运维来说比较麻烦，需要关注每个节点以及每台机器，在多数据中心情况下持续发布集成或者哪个服务器挂了比较麻烦。 2、categraf 的 all in one 的风格支持ssh协议是对收集器的补充。 3、Windows服务可以通过snmp协议抓取监控指标，目前是支持的，这样方式也能够减少agent或者exporter

明白了，你说的这种情况压根不需要agent
可以了解下https://hertzbeat.apache.org/zh-cn/   无agent超轻量化采集，远程ssh获取获取主机指标
