### ISSUE TITLE
怎么才能配置自动发现K8S中的redis 实例，动态的进行监控

### ISSUE THREAD

**Issue by szy345** [flashcatcloud/categraf#893]
k8s中，动态的创建删除redis，或者其他某种类型的pod。
要想监控，不可能每次创建一个实例，就来更新一下categraf的配置文件吧。

有没有办法配置成，比如根据某个svc label，或者pod label ，自动发现redis 实例，实际pod的ip，port都是可以获取到的，理论上是可行的。
这样更贴近K8S的弹性Feature吧， 类似prometheus 的serviceMonitor/podMonitor

<img width="714" alt="image" src="https://github.com/flashcatcloud/categraf/assets/14071421/fddcac12-4415-4ab5-b3d7-2713a49734f7">

**Comment by kongfei605** [comment]
redis插件还没有自动发现能力

**Comment by szy345** [comment]
> redis插件还没有自动发现能力

不能自动发现，这种就很难在k8s里部署，生态上对比exporter，感觉也没有明细的优势了。

尽管categraf 是all in one了

**Comment by kongfei605** [comment]
是的

**Comment by szy345** [comment]
> 是的

哈哈，有这样的排期吗？有可能的话，也可以合作，或者定制

**Comment by kongfei605** [comment]
自动发现和relabel在categraf最初几个版本就准备做了，截止目前只加了relabel，自动发现还得等等

**Comment by eryajf** [comment]
> 自动发现和relabel在categraf最初几个版本就准备做了，截止目前只加了relabel，自动发现还得等等

请问下现在自动发现功能是否支持了呢
