### ISSUE TITLE
categraf采集的时候没加-l lanplus 

### ISSUE THREAD

**Issue by cinoliu** [flashcatcloud/categraf#894]
### Relevant config.toml

```toml
大佬，我自己手动执行了一下命令，在原本的命令上加上-l lanplus就不报错了，但是问题是categraf采集的时候没加-l lanplus ，这咋搞[捂脸]
```

### Logs from categraf

```text
无
```

### System info

0.10

### Steps to reproduce

![97E37A34-3DA9-4D62-8265-524B66FF3B83](https://github.com/flashcatcloud/categraf/assets/18730677/48978276-ca3e-454d-a1b7-6126c74fb37c)
![3644C9F5-DFEF-4944-82ED-550C41F34995](https://github.com/flashcatcloud/categraf/assets/18730677/8ba7f387-7a1a-4522-9177-b84a84039d08)

### Expected behavior

大佬，我自己手动执行了一下命令，在原本的命令上加上-l lanplus就不报错了，但是问题是categraf采集的时候没加-l lanplus ，这咋搞[捂脸]

### Actual behavior

无

**Comment by kongfei605** [comment]
没贴配置，没贴版本，那只能自己多看看了 https://flashcat.cloud/docs/content/flashcat-monitor/categraf/plugin/ipmi/
