### ISSUE TITLE
mtail.toml什么时候可以将prog_content从企业版下放到开源版吗？

### ISSUE THREAD

**Issue by luoyuLianga** [flashcatcloud/categraf#900]
![image](https://github.com/flashcatcloud/categraf/assets/155722980/7e14c944-d899-42df-a5ab-ebb2caf1c914)

**Comment by luoyuLianga** [comment]
> 最近1-2个版本 会同步到开源版

期待一下

**Comment by kongfei605** [comment]
v0.3.62 已发布
