### ISSUE TITLE
windows server 2008R2 安装categraf-v0.3.61-windows-amd64 失败

### ISSUE THREAD

**Issue by liuxinglan13** [flashcatcloud/categraf#911]
C:\categraf-v0.3.61-windows-amd64>categraf.exe --win-service-install
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall()
        /opt/hostedtoolcache/go/1.21.9/x64/src/runtime/sys_windows_amd64.s:65 +0
x75 fp=0x22fca0 sp=0x22fc80 pc=0x474db5
rax     0x0
rbx     0x8882b20
rcx     0x88e6980
rdi     0x7fffffdd000
rsi     0x22fea0
rbp     0x22fde0
rsp     0x22fc78
r8      0x0
r9      0x22fee0
r10     0x88b6c58
r11     0x21
r12     0x22fec0
r13     0x1
r14     0x8881ca0
r15     0x0
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b

C:\categraf-v0.3.61-windows-amd64>

**Comment by kongfei605** [comment]
不支持2008，用v0.3.48 之前的版本 。  https://github.com/flashcatcloud/categraf/issues/810

**Comment by taoyang987** [comment]
用v0.3.45才行
