### ISSUE TITLE
input.snmp多个toml无法进[mapping]配置

### ISSUE THREAD

**Issue by zhangchi2217** [flashcatcloud/categraf#917]
# 描述
在snmp.inputs文件夹下创建了2个toml文件，采集的主机不重复，但配置[mappings]后无法正常运行，通过test测试存在报错，提示[mappings]已存在

# 目录：
[root@Nightingale categraf]# ll conf/input.snmp
total 16
-rw-r--r-- 1 root root 2817 May 11 11:02 snmp_input_firewall.toml
-rw-r--r-- 1 root root 9973 Apr 29 14:56 snmp_input_switch.toml

# 配置
## snmp_input_firewall.toml
`# 基本时间10s
interval = 15

[mappings]
 "udp://172.20.189.2:161" = {name = "FW0109A3302", region = "sohu", role = "firewall", floor = "9", u = "A33"}
 "udp://172.20.189.3:161" = {name = "FW0209B3303", region = "sohu", role = "firewall", floor = "9", u = "B33"}

[[instances]]

interval_times = 1

agents = [
    "udp://172.20.189.2:161",
    "udp://172.20.189.3:161",
]`

## snmp_input_switch.toml
`# 基本时间10s
interval = 60 

[mappings]
"udp://172.20.189.81:161" = {name = "AP08A36U81", role = "poe", floor = "8", u = "A36"}
"udp://172.20.189.82:161" = {name = "M08A34U82", role = "monitor", floor = "8", u = "A34"}
"udp://172.20.189.83:161" = {name = "L08A32U83", role = "lan", floor = "8", u = "A32"}
"udp://172.20.189.84:161" = {name = "L08A30U84",  role = "lan", floor = "8", u = "A30"}
"udp://172.20.189.85:161" = {name = "L08A28U85", role = "lan", floor = "8", u = "A28"}
"udp://172.20.189.86:161" = {name = "L08A26U86", role = "lan", floor = "8", u = "A26"}
"udp://172.20.189.87:161" = {name = "L08A24U87", role = "lan", floor = "8", u = "A24"}
"udp://172.20.189.88:161" = {name = "L08A22U88", role = "lan", floor = "8", u = "A22"}`

# test报错
`[root@Nightingale categraf]# ./categraf -test --inputs snmp
2024/05/11 11:02:54 metrics_agent.go:256: E! failed to load configuration of plugin: local.snmp error: toml: line 138: Key 'mappings' has already been defined.

**Comment by kongfei605** [comment]
一个input只能存在一份mappings

**Comment by kongfei605** [comment]
mapings 单独拆到一个文件好了

**Comment by UlricQin** [comment]
而且mappings配置应该在最上面，所以mappings的toml文件应该用a.toml 这样的文件名，排序的时候可以排在前面，对吧 @kongfei605
