### ISSUE TITLE
华为云K8S环境部署的n9e无法获取到k8s的指标

### ISSUE THREAD

**Issue by lyitt1987** [flashcatcloud/categraf#920]
n9e部署方式：helm
categraf是以 DaemonSet运行
由于华为云k8s启动的10250端口未绑定在127.0.0.1，helm部署的n9e categraf日志报错如图
![image](https://github.com/flashcatcloud/categraf/assets/35764082/ed01d87c-d3a5-41a7-834b-6e4e9e4d1d07)

请问，如何配置让categraf 获取到本机IP，谢谢！

**Comment by kongfei605** [comment]
是未绑定在127 还是直接没开启这个端口？ 绑定的是node ip？

**Comment by lyitt1987** [comment]
未绑定在127.0.0.1，只绑定了node ip，如何配置categraf从node ip去获取指标



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月14日 15:02 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [flashcatcloud/categraf] 华为云K8S环境部署的n9e无法获取到k8s的指标 (Issue #920) |

是未绑定在127 还是直接没开启这个端口？ 绑定的是node ip？

**Comment by kongfei605** [comment]
目前都是configmap配置的，现在还不能差异化配置。可以放到启动脚本中，利用注入的环境变量替换配置中的127

**Comment by lyitt1987** [comment]
好的，谢谢

**Comment by lyitt1987** [comment]
> 目前都是configmap配置的，现在还不能差异化配置。可以放到启动脚本中，利用注入的环境变量替换配置中的127

![image](https://github.com/flashcatcloud/categraf/assets/35764082/e999ac1e-e863-46a8-899a-d23f6b9faa63)

**Comment by UlricQin** [comment]
你登录容器里看看是否有 NODE_IP 之类的环境变量，然后把 127.0.0.1 改成 `$NODE_IP` 之类的试试

**Comment by lyitt1987** [comment]
> 你登录容器里看看是否有 NODE_IP 之类的环境变量，然后把 127.0.0.1 改成 `$NODE_IP` 之类的试试

有，可以使用，变量名是 HOSTIP，把configmap为 input-kubernetes和 input-cadvisor 配置的127.0.0.1 改成 $HOSTIP 后，重启categraf就能正常获取了
谢谢大佬
