### ISSUE TITLE
snmp获取数据报错invalid OID length

### ISSUE THREAD

**Issue by zhangchi2217** [flashcatcloud/categraf#922]
# categraf版本：v0.3.61

# 通过categraf本机进行测试可以获取到值：
`[root@Nightingale categraf]# snmpwalk -v2c -c Zphz@snmp.cn 172.20.189.2 IF-MIB::ifHCInOctets
IF-MIB::ifHCInOctets.1 = Counter64: 50120
IF-MIB::ifHCInOctets.2 = Counter64: 0
IF-MIB::ifHCInOctets.3 = Counter64: 0
IF-MIB::ifHCInOctets.4 = Counter64: 35773894640
IF-MIB::ifHCInOctets.5 = Counter64: 297615
IF-MIB::ifHCInOctets.6 = Counter64: 9141645973
IF-MIB::ifHCInOctets.7 = Counter64: 10878024984
IF-MIB::ifHCInOctets.8 = Counter64: 0
IF-MIB::ifHCInOctets.9 = Counter64: 0
IF-MIB::ifHCInOctets.10 = Counter64: 0
IF-MIB::ifHCInOctets.11 = Counter64: 4348071017
IF-MIB::ifHCInOctets.12 = Counter64: 101952363212188
IF-MIB::ifHCInOctets.13 = Counter64: 0
IF-MIB::ifHCInOctets.14 = Counter64: 236619430220520
IF-MIB::ifHCInOctets.15 = Counter64: 146168635672459
IF-MIB::ifHCInOctets.16 = Counter64: 2322843
IF-MIB::ifHCInOctets.17 = Counter64: 0
IF-MIB::ifHCInOctets.18 = Counter64: 35774192539`

# 但是通过test会产生报错：
`
2024/05/13 17:24:54 table.go:405: E! snmp walk error:error in unmarshalResponse: error decoding value: error parsing OID Value: invalid OID length, oid:.1.3.6.1.2.1.31.1.1.1.6 
2024/05/13 17:24:54 instances.go:169: agent udp://172.20.189.3:161 ins: gathering table fw_interface error: performing bulk walk for field ifHCInOctets(.1.3.6.1.2.1.31.1.1.1.6): error in unmarshalResponse: error decoding value: error parsing OID Value: invalid OID length
2024/05/13 17:24:59 table.go:405: E! snmp walk error:error in unmarshalResponse: error decoding value: error parsing OID Value: invalid OID length, oid:.1.3.6.1.2.1.31.1.1.1.6 
2024/05/13 17:24:59 instances.go:169: agent udp://172.20.189.2:161 ins: gathering table fw_interface error: performing bulk walk for field ifHCInOctets(.1.3.6.1.2.1.31.1.1.1.6): error in unmarshalResponse: error decoding value: error parsing OID Value: invalid OID length
`

# 以下是配置文件：
`
interval = 15

[[instances]]

interval_times = 1

agents = [
    "udp://172.20.189.2:161",
    "udp://172.20.189.3:161",
]

timeout = "5s"
version = 2
community = "snmp"
agent_host_tag = "ip"
retries = 3
max_repetitions = 5000 

[[instances.table]]
oid = "IF-MIB::ifTable"
name = "fw_interface"
index_as_tag = true
filters = ["A:ifDescr:^(XGig*|Gigab*|WAN*)"]
filters_expression = "A"

[[instances.table.field]]
oid = "IF-MIB::ifDescr"
name = "ifDescr"
is_tag = true

[[instances.table.field]]
oid = "IF-MIB::ifHCInOctets"
name = "ifHCInOctets"

[[instances.table.field]]
oid = "IF-MIB::ifHCOutOctets"
name = "ifHCOutOctets"

[[instances.table.field]]
oid = "IF-MIB::ifOperStatus"
name = "ifOperStatus"

[[instances.table.field]]
oid = "IF-MIB::ifInOctets"
name = "ifInOctets"

[[instances.table.field]]
oid = "IF-MIB::ifOutOctets"
name = "ifOutOctets"`

**Comment by kongfei605** [comment]
max_repetitions = 10 
参数含义要和设备匹配

**Comment by luweijun1992** [comment]
> max_repetitions = 10 参数含义要和设备匹配

max_repetitions 参数使用多少合适，怎么计算评估？有啥公式或者建议值吗？

**Comment by kongfei605** [comment]
> > max_repetitions = 10 参数含义要和设备匹配
> 
> max_repetitions 参数使用多少合适，怎么计算评估？有啥公式或者建议值吗？

一般推荐bulk系列的命令的默认值，没记错的话是20。 想要知道最大多少，需要翻手册 ，看设备限制多少 。
