### ISSUE TITLE
【input.snmp】agents配置文件格式问题导致自带snmp_up/snmp_icmp* 指标异常

### ISSUE THREAD

**Issue by luweijun1992** [flashcatcloud/categraf#923]
### Relevant config.toml

```toml
[[instances]]
    agents = ["192.168.255.254", "172.17.0.253"]
```

### System info

categraf v0.3.61

### Additional info

agents配置只写IP地址的话，snmp_up、snmp_icmp开头的指标都不正常。
![image](https://github.com/flashcatcloud/categraf/assets/58923704/aff5dffc-88c7-416b-beb4-eef9f0fc4fb4)

---
修改为以下就正常了
```
[[instances]]
    agents = ["udp://192.168.255.254", "udp://172.17.0.253"]
```
![image](https://github.com/flashcatcloud/categraf/assets/58923704/9e719c65-6f8e-4dcd-9909-a82abfac3ed9)

---
Code
![image](https://github.com/flashcatcloud/categraf/assets/58923704/0f1f920a-3145-4b51-80cc-4c2bb4071379)

**Comment by kongfei605** [comment]
已经fix ， https://github.com/flashcatcloud/categraf/pull/926， 新版本v0.3.64

**Comment by luweijun1992** [comment]
> 已经fix ， #926 新版本v0.3.64

新版本正常
