### ISSUE TITLE
ping采集模块可以修改target显示么

### ISSUE THREAD

**Issue by CunHua123** [flashcatcloud/categraf#952]
<img width="772" alt="微信图片_20240603112259" src="https://github.com/flashcatcloud/categraf/assets/110003423/b330c650-b367-4e1c-af25-662504eae6df">
类似于target标签，怎么能在上传数据的时候，改变名称呢，因为要做过滤用，比如target改变为ident

**Comment by CunHua123** [comment]
已经换了个办法解决了

**Comment by kongfei605** [comment]
每个插件都支持relabel
