### ISSUE TITLE
dcgm 是不是还不支持 ./categraf --test --inputs dcgm

### ISSUE THREAD

**Issue by robotneo** [flashcatcloud/categraf#956]
目前在 GPU 服务器上测试采集失败，是不是因为还不支持测试呢？

**Comment by kongfei605** [comment]
是不是下错版本了？

**Comment by robotneo** [comment]
没有哦 最新版本

**Comment by robotneo** [comment]
我用 dcgm-exporter 采集正常，应该没有我没注意到的点吧

**Comment by robotneo** [comment]
/opt/categraf/categraf --test --inputs dcgm
2024/06/15 13:57:51 main.go:149: I! runner.binarydir: /opt/categraf
2024/06/15 13:57:51 main.go:150: I! runner.hostname: p-xxxxxxxxxxxxxxxxxx
2024/06/15 13:57:51 main.go:151: I! runner.fd_limits: (soft=1048576, hard=1048576)
2024/06/15 13:57:51 main.go:152: I! runner.vm_limits: (soft=unlimited, hard=unlimited)
2024/06/15 13:57:51 provider_manager.go:60: I! use input provider: [local]
2024/06/15 13:57:51 prometheus_agent.go:19: I! prometheus scraping disabled!
2024/06/15 13:57:51 ibex_agent.go:19: I! ibex agent disabled!
2024/06/15 13:57:51 agent.go:38: I! agent starting
2024/06/15 13:57:51 metrics_agent.go:242: E! input: local.dcgm not supported
2024/06/15 13:57:51 agent.go:46: I! [*agent.MetricsAgent] started

**Comment by kongfei605** [comment]
下错版本了，文档上有介绍，要用cgo版本
