### ISSUE TITLE
categraf采集redis/disk发现无法写入prometheus

### ISSUE THREAD

**Issue by mvpbang** [flashcatcloud/categraf#96]
### Relevant config.toml

```toml
[weblogic@ categraf]$ cat conf/input.disk/disk.toml 
# # collect interval
# interval = 15

# # By default stats will be gathered for all mount points.
# # Set mount_points will restrict the stats to only the specified mount points.
# mount_points = ["/"]

# Ignore mount points by filesystem type.
ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]

ignore_mount_points = ["/boot"]
```

### Logs from categraf

```text
[weblogic@ categraf]$ ./categraf -test inputs disk
2022/07/13 17:16:24 main.go:109: I! runner.binarydir: /servyou/n9e/agent/categraf
2022/07/13 17:16:24 main.go:110: I! runner.hostname: 
2022/07/13 17:16:24 main.go:111: I! runner.fd_limits: (soft=65535, hard=65535)
2022/07/13 17:16:24 main.go:112: I! runner.vm_limits: (soft=unlimited, hard=unlimited)
2022/07/13 17:16:24 config.go:33: I! tracing disabled
2022/07/13 17:16:24 agent.go:57: I! agent starting
2022/07/13 17:16:24 metrics_agent.go:60: I! input: disk started
2022/07/13 17:16:24 metrics_agent.go:60: I! input: redis started
2022/07/13 17:16:24 agent.go:61: I! agent started












2022/07/13 17:16:27 writers.go:76: >> count: 7
17:16:27 disk_inodes_total agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 2.0445184e+07
17:16:27 disk_inodes_free agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 2.0337309e+07
17:16:27 disk_inodes_used agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 107875
17:16:27 disk_total agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 4.1851293696e+10
17:16:27 disk_free agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 1.8069061632e+10
17:16:27 disk_used agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 2.3782232064e+10
17:16:27 disk_used_percent agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 56.825560129036155
2022/07/13 17:16:30 writers.go:76: >> count: 7
17:16:30 disk_inodes_free agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 2.0337309e+07
17:16:30 disk_inodes_used agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 107875
17:16:30 disk_total agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 4.1851293696e+10
17:16:30 disk_free agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 1.8069061632e+10
17:16:30 disk_used agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 2.3782232064e+10
17:16:30 disk_used_percent agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 56.825560129036155
17:16:30 disk_inodes_total agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 2.0445184e+07
2022/07/13 17:16:33 writers.go:76: >> count: 7
17:16:33 disk_total agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 4.1851293696e+10
17:16:33 disk_free agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 1.8069041152e+10
17:16:33 disk_used agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 2.3782252544e+10
17:16:33 disk_used_percent agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 56.825609064202055
17:16:33 disk_inodes_total agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 2.0445184e+07
17:16:33 disk_inodes_free agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 2.0337309e+07
17:16:33 disk_inodes_used agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 107875
2022/07/13 17:16:36 writers.go:76: >> count: 7
17:16:36 disk_used_percent agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 56.825609064202055
17:16:36 disk_inodes_total agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 2.0445184e+07
17:16:36 disk_inodes_free agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 2.0337309e+07
17:16:36 disk_inodes_used agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 107875
17:16:36 disk_total agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 4.1851293696e+10
17:16:36 disk_free agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 1.8069041152e+10
17:16:36 disk_used agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 2.3782252544e+10


[weblogic@ categraf]$ ./categraf  -inputs  disk
2022/07/13 17:18:58 main.go:109: I! runner.binarydir: /servyou/n9e/agent/categraf
2022/07/13 17:18:58 main.go:110: I! runner.hostname: 
2022/07/13 17:18:58 main.go:111: I! runner.fd_limits: (soft=65535, hard=65535)
2022/07/13 17:18:58 main.go:112: I! runner.vm_limits: (soft=unlimited, hard=unlimited)
2022/07/13 17:18:58 config.go:33: I! tracing disabled
2022/07/13 17:18:58 agent.go:57: I! agent starting
2022/07/13 17:18:58 metrics_agent.go:60: I! input: disk started
2022/07/13 17:18:58 agent.go:61: I! agent started
```

### System info

3.10.0-862.11.6.el7.x86_64

### Steps to reproduce

忽略

### Expected behavior

采集的指标可以正常写人prometheus

### Actual behavior

01、n9e server日志
2022-07-13 17:29:17.899211 WARNING writer/writer.go:43 example timeseries:labels:<name:"__name__" value:"disk_free" > labels:<name:"ident" value:"" > labels:<name:"path" value:"/" > labels:<name:"device" value:"dm-0" > labels:<name:"fstype" value:"xfs" > labels:<name:"mode" value:"rw" > samples:<value:1.7781137408e+10 timestamp:1657704556 > 
2022-07-13 17:29:17.899227 WARNING writer/writer.go:43 example timeseries:labels:<name:"__name__" value:"disk_total" > labels:<name:"path" value:"/" > labels:<name:"device" value:"dm-0" > labels:<name:"fstype" value:"xfs" > labels:<name:"mode" value:"rw" > labels:<name:"ident" value:"" > samples:<value:4.1851293696e+10 timestamp:1657704556 > 
2022-07-13 17:29:17.899271 WARNING writer/writer.go:42 post to http://127.0.0.1:9090/api/v1/write got error: push data with remote write request got status code: 400, response body: out of bounds
2022-07-13 17:29:17.899293 WARNING writer/writer.go:43 example timeseries:labels:<name:"__name__" value:"disk_used" > labels:<name:"ident" value:"" > labels:<name:"fstype" value:"xfs" > labels:<name:"mode" value:"rw" > labels:<name:"path" value:"/" > labels:<name:"device" value:"dm-0" > samples:<value:2.4070156288e+10 timestamp:1657704556 > 
2022-07-13 17:29:17.899272 WARNING writer/writer.go:42 post to http://127.0.0.1:9090/api/v1/write got error: push data with remote write request got status code: 400, response body: out of bounds
2022-07-13 17:29:17.899320 WARNING writer/writer.go:43 example timeseries:labels:<name:"__name__" value:"disk_inodes_total" > labels:<name:"mode" value:"rw" > labels:<name:"path" value:"/" > labels:<name:"device" value:"dm-0" > labels:<name:"fstype" value:"xfs" > labels:<name:"ident" value:"" > samples:<value:2.0445184e+07 timestamp:1657704556 > 
2022-07-13 17:29:17.899356 WARNING writer/writer.go:42 post to http://127.0.0.1:9090/api/v1/write got error: push data with remote write request got status code: 400, response body: out of bounds
2022-07-13 17:29:17.899417 WARNING writer/writer.go:43 example timeseries:labels:<name:"__name__" value:"disk_inodes_used" > labels:<name:"path" value:"/" > labels:<name:"device" value:"dm-0" > labels:<name:"fstype" value:"xfs" > labels:<name:"mode" value:"rw" > labels:<name:"ident" value:"" > samples:<value:107902 timestamp:1657704556 > 

02、prometheus日志
level=error ts=2022-07-13T09:17:02.077Z caller=write_handler.go:53 component=web msg="Out of order sample from remote write" err="out of bounds"
level=error ts=2022-07-13T09:17:02.077Z caller=write_handler.go:53 component=web msg="Out of order sample from remote write" err="out of bounds"
level=error ts=2022-07-13T09:17:02.077Z caller=write_handler.go:53 component=web msg="Out of order sample from remote write" err="out of bounds"
level=error ts=2022-07-13T09:17:02.077Z caller=write_handler.go:53 component=web msg="Out of order sample from remote write" err="out of bounds"
level=error ts=2022-07-13T09:17:02.077Z caller=write_handler.go:53 component=web msg="Out of order sample from remote write" err="out of bounds"

### Additional info

[weblogic@ prometheus-2.28.0.linux-amd64]$ ps aux |grep prome
weblogic 17427  1.3  0.3 778368 37220 pts/3    Sl   17:35   0:00 ./prometheus --config.file=./prometheus.yml --storage.tsdb.path=./data --web.enable-lifecycle --enable-feature=remote-write-receiver --query.lookback-delta=2m

**Comment by UlricQin** [comment]
```
17:16:27 disk_inodes_total agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 2.0445184e+07
17:16:27 disk_inodes_free agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 2.0337309e+07
17:16:27 disk_inodes_used agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 107875
```
agent_hostname 标签是空，是不正常的，检查你的config.toml，看看为啥没有成功获取hostname，也可以写死hostname的配置，录制了几个视频，自行学习一下 https://mp.weixin.qq.com/s/T69kkBzToHVh31D87xsrIg

**Comment by mvpbang** [comment]
> ```
> 17:16:27 disk_inodes_total agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 2.0445184e+07
> 17:16:27 disk_inodes_free agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 2.0337309e+07
> 17:16:27 disk_inodes_used agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 107875
> ```
> 
> agent_hostname 标签是空，是不正常的，检查你的config.toml，看看为啥没有成功获取hostname，也可以写死hostname的配置，录制了几个视频，自行学习一下 https://mp.weixin.qq.com/s/T69kkBzToHVh31D87xsrIg

不是这个agent_hostname为空的问题，这个有值还是一样的错误

**Comment by UlricQin** [comment]
response body: out of bounds 是时序库返回的，表示上报的监控数据时间太超前或者太滞后，删除 prometheus 的data目录，重启prometheus试试

**Comment by lijiext** [comment]
> > ```
> > 17:16:27 disk_inodes_total agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 2.0445184e+07
> > 17:16:27 disk_inodes_free agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 2.0337309e+07
> > 17:16:27 disk_inodes_used agent_hostname= device=dm-0 fstype=xfs mode=rw path=/ 107875
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > agent_hostname 标签是空，是不正常的，检查你的config.toml，看看为啥没有成功获取hostname，也可以写死hostname的配置，录制了几个视频，自行学习一下 https://mp.weixin.qq.com/s/T69kkBzToHVh31D87xsrIg
> 
> 不是这个agent_hostname为空的问题，这个有值还是一样的错误
你好，我也遇到同样的问题，删除 prometheus 数据目录后还是同样的 out of bounds 问题，请问你解决了吗？

**Comment by UlricQin** [comment]
升级到最新版本的夜莺，在server.conf第一行加一个配置：ForceUseServerTS = true，删除prometheus数据，重来就没问题了
