### ISSUE TITLE
input.procstat 配置多个，查询出的只有最后一个有结果，前几条都没有

### ISSUE THREAD

**Issue by hudachui1224** [flashcatcloud/categraf#966]
input.procstat  配置多个条目，但是 procstat_cpu_usage， procstat_mem_usage 等查询结果只有最后一个 redis_server_26373的记录。为什么没前面的几条记录？怎样才能 添加多个对象，每个对象 labels 不同的标签？

配置如下：
interval = 30

[[instances]]
search_cmdline_substring = "redis_server_26371"
labels = { app_server="lab_123", app="redis_server_26371" }

[[instances]]
search_cmdline_substring = "redis_server_26372"
labels = { app_server="lab_123", app="redis_server_26372" }

[[instances]]
search_cmdline_substring = "redis_server_26373"
labels = { app_server="lab_123", app="redis_server_26373" }

gather_total = false
gather_per_pid = true

gather_more_metrics = [
     "threads",
     "fd",
     "io",
     "uptime",
     "cpu",
     "mem",
     "limit"
]

**Comment by UlricQin** [comment]
下面这段配置需要出现在每一个 `[[instances]]` 配置段内：

```
gather_total = false
gather_per_pid = true

gather_more_metrics = [
"threads",
"fd",
"io",
"uptime",
"cpu",
"mem",
"limit"
]
```
