### ISSUE TITLE
categraf 的 input.zookeeper 插件是对端口进行探活吗？

### ISSUE THREAD

**Issue by ixiaoyi93** [flashcatcloud/categraf#990]
通过 input.zookeeper 插件进行 zookeeper 监控，发现只有3个指标：zk_ruok,zk_scrape_use_seconds,zk_up .我想知到该插件是如何抓去数据的，如果效果是这样的话，我感觉这个插件的意义不大呀。

**Comment by zzmark** [comment]
想知道细节不如去扫一眼代码，就两百来行，核心就几十行的程度。


zk_ruok 使用 ruok 命令
zk_scrape_use_seconds 是插件计算来的
zk_up 是端口存活检测，zk-client 就是基础的套接字，通了就算活

mntr 会逐个解析开，除掉三个特例 zk_version, zk_server_state, zk_peer_state ，其余的要求 value 为number，原样写入


你只拿到三个指标，而剩余的指标都要依赖 mntr。检查下是不是版本小于3.4.0，或者没开启4lw

**Comment by ixiaoyi93** [comment]
> 想知道细节不如去扫一眼代码，就两百来行，核心就几十行的程度。
> 
> zk_ruok 使用 ruok 命令 zk_scrape_use_seconds 是插件计算来的 zk_up 是端口存活检测，zk-client 就是基础的套接字，通了就算活
> 
> mntr 会逐个解析开，除掉三个特例 zk_version, zk_server_state, zk_peer_state ，其余的要求 value 为number，原样写入
> 
> 你只拿到三个指标，而剩余的指标都要依赖 mntr。检查下是不是版本小于3.4.0，或者没开启4lw

我悟了，哥。
